import { OFFICIAL } from './shared.js'

export const JAVA_FOUNDATION_CHAPTERS_01_03 = [
  {
    title: 'Java 语法、类型与参数语义',
    questions: [
      {
        title: 'Java 的基本类型、引用类型与变量默认值应怎样区分？',
        summary: 'Java 的类型先分基本类型与引用类型；默认值只由字段和数组元素自动获得，方法局部变量必须通过确定赋值检查后才能读取。',
        mechanism: '八种基本类型直接表示布尔值、整数、浮点数或 UTF-16 代码单元，引用类型的变量保存的是对对象或数组的引用，空引用用 null 表示。JLS 没有规定 boolean 的存储位数，也不能把整数直接当布尔值使用。实例字段、静态字段和新建数组元素会被初始化为零值、false 或 null；局部变量不会自动填默认值，编译器通过确定赋值规则分析每条控制流路径。引用变量本身可以重新指向别处，这与被引用对象是否可变是两件事；final 引用只禁止变量再次赋值，并不会递归冻结对象内部状态。',
        example: '例如 `class Box { int count; String name; }` 中，新建 Box 后 count 为 0、name 为 null；但方法内写 `int n; System.out.println(n);` 会编译失败。若写 `final List<String> names = new ArrayList<>();`，不能让 names 指向新列表，却仍可执行 `names.add("A")` 修改原列表。',
        followUps: [
          { question: '为什么局部变量没有默认值反而更安全？', answer: '编译期强制每条可达路径先赋值，可以尽早暴露遗漏分支，避免把无意的零值或 null 当成真实业务状态继续传播。' },
          { question: 'char 是否等同于一个完整的 Unicode 字符？', answer: '不等同。char 是单个 UTF-16 代码单元，补充平面字符需要一对代理项表示，按用户可见字符处理时应使用代码点相关 API。' },
        ],
        pitfalls: ['声称 boolean 固定占用一字节或四字节，混淆语言规范与 JVM 实现细节。', '把 final 引用理解成深度不可变，忽略对象字段和集合内容仍可能改变。'],
        sources: [OFFICIAL.jlsTypes, OFFICIAL.jlsStatements],
      },
      {
        title: '整数提升、窄化转换与溢出为什么容易制造隐藏错误？',
        summary: 'byte、short 与 char 参与多数算术运算时先提升为 int；窄化可能丢高位，整数溢出按固定宽度回绕而不会自动抛异常。',
        mechanism: '一元和二元数值提升决定表达式的计算类型：byte、short、char 通常先提升为 int，再与另一操作数共同转换，因此 `byte + byte` 的结果类型是 int。普通赋值不允许把 int 隐式窄化给 byte，但编译期可表示的整型常量存在受限的常量窄化规则；复合赋值则隐含一次转换，所以 `b += 1` 可编译而 `b = b + 1` 不行。整数运算只保留目标类型位宽，溢出不会产生语言级异常；除零会抛 ArithmeticException，但 `Integer.MIN_VALUE / -1` 是规范明确的特殊回绕结果。需要检测溢出时应使用 Math.addExact、multiplyExact 等方法。',
        example: '例如 `byte b = 127; b += 1;` 结果是 -128；而 `byte c = 127; c = c + 1;` 因右侧为 int 无法编译。计费系统若用 `int total = price * quantity`，大数可能静默变负，应先提升到 long，并在仍需严格边界时使用 `Math.multiplyExact((long) price, quantity)`。',
        followUps: [
          { question: '为什么 `short s = 1` 可以，而变量 int 赋给 short 不行？', answer: '前者是编译期可证明落在 short 范围内的常量表达式窄化；变量值运行时才确定，编译器不能无条件保证不丢失信息。' },
          { question: '无符号数据在 Java 中应该怎样处理？', answer: 'Java 的 byte、short、int、long 是有符号整数，必要时可用 Integer、Long 的无符号比较和转换 API，或提升后配合位掩码。' },
        ],
        pitfalls: ['认为 Java 整数溢出必然抛异常，导致金额、计数或容量计算静默产生错误值。', '只记住强制转换语法，却忽略复合赋值已经隐式执行了可能丢信息的窄化。'],
        sources: [OFFICIAL.jlsTypes, OFFICIAL.jlsConversions, OFFICIAL.jlsExpressions],
      },
      {
        title: '浮点数为何不能直接表示多数十进制小数，金额又该怎样计算？',
        summary: 'float 与 double 使用二进制浮点表示，很多有限十进制小数在二进制中是无限循环；精确十进制业务通常应使用 BigDecimal。',
        mechanism: 'Java 浮点运算遵循 IEEE 754 语义，有限位的符号、指数和有效数字只能近似保存多数十进制分数，因此 0.1 与 0.2 的内部值并非数学上的精确十分之一和五分之一。浮点还包含正负零、无穷大和 NaN；NaN 与任何值包括自身做 `==` 都为 false。BigDecimal 用任意精度整数加 scale 表示十进制值，构造时应优先传字符串或使用 valueOf，避免把 double 已有误差原样带入。除法可能得到无限小数，必须按业务指定精度与舍入模式；`equals` 同时比较数值和 scale，而 `compareTo` 比较数值大小。',
        example: '例如 `0.1 + 0.2 == 0.3` 通常为 false。订单金额可写 `new BigDecimal("19.90").multiply(BigDecimal.valueOf(3))`，分摊时显式调用 `divide(count, 2, RoundingMode.HALF_UP)`。`new BigDecimal("1.0").equals(new BigDecimal("1.00"))` 为 false，但 compareTo 返回 0。',
        followUps: [
          { question: '科学计算是否也应该全部换成 BigDecimal？', answer: '不一定。科学计算常接受可量化误差并重视硬件浮点吞吐，应根据误差模型比较容差，而不是追求十进制逐位相等。' },
          { question: 'BigDecimal 为什么不能直接用 `==` 比较？', answer: '`==` 比较两个引用是否指向同一对象，不比较数值内容；业务上应根据是否关心 scale 选择 equals 或 compareTo。' },
        ],
        pitfalls: ['用 `new BigDecimal(0.1)` 构造金额，把二进制近似值完整带进十进制对象。', '调用 BigDecimal.divide 时不指定无法整除情况下的精度或舍入策略。'],
        sources: [OFFICIAL.jlsTypes, OFFICIAL.bigDecimal],
      },
      {
        title: '自动装箱、拆箱与包装类缓存会怎样影响比较和空值？',
        summary: '装箱把基本值转换为包装对象，拆箱反向取值；引用相等、缓存区间与 null 拆箱共同构成常见的线上空指针和比较陷阱。',
        mechanism: '赋值、方法调用和运算上下文可触发装箱或拆箱。对 Integer 等包装类使用 `==` 时，如果两边都是引用，比较的是对象身份而非数值；规范要求部分常量装箱结果在一定范围内共享，例如 int 的 -128 到 127，但实现可以缓存更多，业务逻辑不能依赖范围外身份。只要包装值进入算术、关系运算或赋给基本类型，就会执行拆箱；null 没有可提取的基本值，因此会抛 NullPointerException。泛型集合只能保存引用类型，所以基本值进入 `List<Integer>` 会产生装箱，热点路径还需关注分配与拆箱成本。',
        example: '例如 `Integer a = 127, b = 127; a == b` 通常且按规范为 true，而值为 128 时不能依赖该结果；统一写 `Objects.equals(a, b)` 可处理 null。`Map<String,Integer> counts` 中 `int n = counts.get("x")` 在键不存在时会因 null 自动拆箱失败，可改用 `getOrDefault("x", 0)`。',
        followUps: [
          { question: '两个包装类做 `<` 比较时比较的是什么？', answer: '关系运算要求数值操作数，因此包装对象先拆箱，再按数值提升规则比较；若任一引用为 null，拆箱阶段就会失败。' },
          { question: '为什么方法重载中装箱与可变参数可能改变选择结果？', answer: '重载解析按适用阶段选择候选，固定元数且无需装箱的转换通常先于装箱，再先于可变参数，因此新增重载可能改变绑定。' },
        ],
        pitfalls: ['用包装对象的 `==` 判断业务数值相等，让结果偶然依赖缓存范围。', '把可能为 null 的包装值直接参与算术或赋给基本类型，忽略隐式拆箱。'],
        sources: [OFFICIAL.jlsConversions, OFFICIAL.jlsExpressions],
      },
      {
        title: 'Java 为什么只有值传递，修改对象却仍可能被调用方看见？',
        summary: 'Java 方法调用始终复制实参的值；对象参数复制的是引用值，因此双方可经各自引用访问同一对象，却不能替调用方重绑变量。',
        mechanism: '调用方法时，每个形参都会得到一个独立的参数变量。基本类型复制具体数值，引用类型复制指向对象的引用值；这仍然是值传递，而不是把调用方变量本身交给方法。方法内修改共享对象的字段或集合内容，调用方随后能观察到同一对象的状态变化；方法内把形参重新赋为新对象，只改变形参这份引用副本。数组也是对象，传入数组后修改元素可见，但把形参数组指向另一个数组不可见。想让方法显式返回新的绑定，应使用返回值、结果对象或可读的状态容器，而不是称其为“引用传递”。',
        example: '例如 `void rename(User u) { u.name = "Li"; u = new User("Wang"); }`：第一次修改作用于双方共享的原 User，第二次只让局部形参指向新对象。交换方法 `swap(User a, User b)` 即使交换 a、b，也无法交换调用方两个变量；应返回二元结果并由调用方重新赋值。',
        followUps: [
          { question: '传入不可变对象时为什么看起来完全不能修改？', answer: '传递规则没有变化，只是该对象没有可观察的原地修改操作；所谓修改通常会创建新对象并让局部引用重新绑定。' },
          { question: '可变参数是否属于特殊的引用传递？', answer: '不是。可变参数在调用处被组织成数组，方法得到的仍是数组引用值的副本，元素修改和形参重绑遵循同一规则。' },
        ],
        pitfalls: ['把“引用值被复制”简称为引用传递，错误推导出方法能够重绑调用方变量。', '为避免副作用只复制最外层引用或集合，实际仍与调用方共享内部可变元素。'],
        sources: [OFFICIAL.jlsExpressions, OFFICIAL.jlsArrays],
      },
      {
        title: 'final、finally 与 finalize 为什么不是同一类概念？',
        summary: 'final 是限制继承或再次赋值的语言修饰符，finally 是异常控制流结构，finalize 则是已弃用并等待移除的对象终结机制。',
        mechanism: 'final 可修饰变量、方法和类：变量只能完成一次赋值，但 final 引用指向的对象仍可能可变；实例方法不可被子类重写，类不可被继承。finally 属于 try 语句的清理分支，在 try 或 catch 正常结束、return 或抛异常时通常都会执行，但进程强制终止、JVM 崩溃等情况下不能保证运行；更危险的是 finally 自己 return 或抛异常会替代此前的返回值或异常。finalize 是 Object 上历史遗留的回调，在 Java 21 已弃用并标记待移除，执行时间和是否执行都没有可靠保证，还会带来对象复活、性能与安全问题，不能承担文件、连接等资源释放。确定性清理应使用 AutoCloseable 与 try-with-resources。',
        example: '例如 `final List<String> names = new ArrayList<>();` 禁止 names 重新指向别处，却允许 `names.add("A")`。`try { return 1; } finally { return 2; }` 最终返回 2，并吞掉前面的控制结果，因此应禁止在 finally 中 return。数据库连接应放进 try-with-resources，而不是等待重写 finalize 后由 GC 顺便关闭。',
        followUps: [
          { question: 'final 方法与 private 方法都不能重写，原因相同吗？', answer: '不同。final 方法是被继承但明确禁止重写；private 方法对子类不可继承，子类出现同名方法只是声明了一个无关的新成员。' },
          { question: 'finally 是否适合关闭多个可能抛异常的资源？', answer: '手写 finally 容易覆盖主异常并遗漏部分关闭动作；try-with-resources 能按逆序关闭，并把关闭异常保存为 suppressed，更适合该场景。' },
        ],
        pitfalls: ['把 final 引用误认为深度不可变，忽略其内部对象仍可被修改。', '在 finally 中 return 或抛出新异常，覆盖真正需要诊断的原始结果。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.jlsStatements, OFFICIAL.object, OFFICIAL.autoCloseable],
      },
      {
        title: '数组协变与泛型不变为什么采用不同的安全策略？',
        summary: 'Java 数组是具体化且协变的，错误写入通过运行时检查阻止；泛型通常不变且被擦除，类型不兼容会尽量在编译期被拒绝。',
        mechanism: '若 Dog 是 Animal 的子类型，Dog[] 也是 Animal[] 的子类型，所以可以把 Dog[] 赋给 Animal[]；但数组运行时知道真实组件类型，每次引用写入都要检查，写入 Cat 会抛 ArrayStoreException。这种协变保留了早期语言兼容性，却把部分错误推迟到运行时。`List<Dog>` 不是 `List<Animal>` 的子类型，因为若允许赋值，就能经后者加入 Cat，破坏原列表承诺。泛型通过通配符表达受控的型变视图：`? extends Animal` 适合读取生产者，不能安全加入具体 Animal；`? super Dog` 适合接收 Dog，读取时只能当 Object。',
        example: '例如 `Animal[] animals = new Dog[2]; animals[0] = new Cat();` 编译通过但运行抛 ArrayStoreException。批量复制可设计为 `static <T> void copy(List<? extends T> src, List<? super T> dst)`，源列表只读出 T，目标列表可写入 T，同时由编译器阻止不安全方向。',
        followUps: [
          { question: '为什么不能直接创建 `new List<String>[10]`？', answer: '数组必须在运行时检查真实组件类型，而泛型实参通常已擦除，无法可靠检查元素参数化类型，因此禁止这类泛型数组创建。' },
          { question: '`List<?>` 能加入 null 吗？', answer: '可以加入 null，因为它可转换为任意引用类型；但不能加入任何确定的非 null 对象，因为通配符代表的实际元素类型未知。' },
        ],
        pitfalls: ['把数组协变当成完全类型安全，忽略错误可能延迟到运行时写入检查。', '认为 `List<子类>` 天然是 `List<父类>`，从而试图绕过泛型不变性。'],
        sources: [OFFICIAL.jlsArrays, OFFICIAL.jlsTypes],
      },
      {
        title: '表达式求值顺序与短路规则怎样决定副作用发生时机？',
        summary: 'Java 明确采用从左到右的操作数求值顺序，`&&`、`||` 和条件运算符只执行必要分支，但复杂副作用仍会严重损害可读性。',
        mechanism: '方法调用时先求目标引用，再从左到右求各实参，最后进入方法；二元运算通常先完整求左操作数，再求右操作数。`&&` 在左侧为 false 时不求右侧，`||` 在左侧为 true 时不求右侧，条件运算符也只选择一个分支。普通 `&` 和 `|` 用于 boolean 时两侧都会求值。自增表达式同时包含旧值或新值结果与变量写回，和数组下标、方法调用混在一起虽然有确定结果，却容易形成难以审查的代码。异常发生后，尚未开始的右侧或后续实参不会执行。',
        example: '例如 `user != null && user.active()` 可以借短路避免空指针；换成单个 `&` 会继续调用右侧。`log(loadA(), loadB())` 保证先完整执行 loadA 再执行 loadB；若 loadA 抛异常，loadB 不执行。像 `a[i++] = i` 虽有规范结果，也应拆成独立语句明确索引与写入时机。',
        followUps: [
          { question: '`&` 与 `&&` 在 boolean 上除了短路还有什么差异？', answer: '两者都能做逻辑与，但 `&` 必定求值两侧，因此右侧副作用或异常一定有机会发生；`&&` 则按左值决定是否跳过。' },
          { question: '多线程中确定的求值顺序是否等于线程安全？', answer: '不等于。求值顺序只约束当前线程内动作，跨线程的可见性和排序还需要同步动作以及 happens-before 关系。' },
        ],
        pitfalls: ['借助自增、赋值和方法副作用写成一条复杂表达式，虽确定却难以维护。', '把短路条件仅当性能优化，忽略它经常承担空值和边界保护职责。'],
        sources: [OFFICIAL.jlsExpressions, OFFICIAL.jlsStatements],
      },
      {
        title: '重载调用中的基本类型转换、装箱与可变参数如何排序？',
        summary: '重载在编译期按分阶段适用性和最具体规则选择；通常先考虑无需装箱的固定参数，再考虑装箱，最后才使用可变参数。',
        mechanism: '编译器先根据方法名和编译期参数类型收集候选，不会根据运行时参数对象重新选择重载。解析分阶段进行：第一阶段允许子类型转换和基本类型宽化，但不做装箱或可变参数；之后才考虑装箱、拆箱结合允许的转换；最后考虑可变参数调用。进入同一阶段的多个候选还要比较谁更具体，无法确定唯一结果就编译失败。基本类型宽化与包装类继承不是同一条转换链，例如 int 可宽化为 long，也可装箱为 Integer，但不能在一次方法调用转换中先装箱再把 Integer 宽化成 Long。null 可匹配多个无关引用重载，常导致歧义。',
        example: '若同时有 `pick(long x)`、`pick(Integer x)`、`pick(int... x)`，调用 `pick(1)` 会选择 long，因为基本类型宽化在无需装箱阶段就适用；若只有后两者则选 Integer，最后才轮到可变参数。若存在 `pick(String)` 与 `pick(Integer)`，调用 `pick(null)` 无法判断谁更具体，会编译失败。',
        followUps: [
          { question: '运行时对象是子类时为何不选择子类参数的重载？', answer: '重载是静态绑定，候选由表达式的编译期类型决定；运行时类型参与的是已选签名下实例方法的重写分派。' },
          { question: '新增一个重载为什么可能破坏旧源码编译？', answer: '新候选可能比原方法更具体，也可能与现有候选对某些 null、lambda 或方法引用形成歧义，导致重新编译时绑定改变或失败。' },
        ],
        pitfalls: ['用“宽化永远优先装箱”替代完整阶段规则，忽略具体候选与适用性条件。', '认为返回值类型可以单独区分重载，实际方法签名解析不能只靠返回类型。'],
        sources: [OFFICIAL.jlsConversions, OFFICIAL.jlsExpressions],
      },
      {
        title: 'enum 为什么是受控实例类，怎样携带状态与行为？',
        summary: 'Java enum 不是整数常量集合，而是由声明预先创建有限实例的特殊类；每个枚举常量都能携带字段、实现行为并安全参与类型检查。',
        mechanism: '枚举类隐式继承 `java.lang.Enum<E>`，不能再继承其他类，但可以实现接口。常量是在枚举类初始化期间创建的 public static final 实例，构造器不能对外开放，因此普通业务代码无法随意 new 出额外实例；这使 `==` 可以可靠比较同一枚举常量。枚举可声明实例字段、构造器和方法，也可让常量提供专属类体重写行为，从而把稳定且封闭的策略放回类型内部。编译器还提供 values 与 valueOf 等成员。name 是声明标识，ordinal 只是当前声明次序，重排或插入常量就会变化，因此持久化和跨系统协议应使用明确且稳定的业务 code，而非 ordinal。',
        example: '例如 `enum Level { NORMAL(1) { int fee(){ return 0; } }, VIP(2) { int fee(){ return 10; } }; final int code; Level(int code){ this.code=code; } abstract int fee(); }` 把有限策略与实例绑定。数据库应保存显式 code 并做受控映射；若保存 ordinal，今后在常量中间插入新等级会把历史数据解释成错误值。',
        followUps: [
          { question: '为什么枚举比较推荐使用 `==`？', answer: '每个枚举常量在对应类加载器中只有声明创建的规范实例，引用身份就是常量身份；同时 `==` 不会因左侧为 null 而调用方法。' },
          { question: '枚举常量中的可变字段是否线程安全？', answer: '不是自动安全。常量虽然是单例式受控实例，但其中可变状态仍被所有调用者共享，应优先保持不可变或使用明确的并发同步策略。' },
        ],
        pitfalls: ['把 ordinal 持久化为业务编码，枚举重排后历史数据语义随之漂移。', '在枚举单例中保存无保护的请求级可变状态，制造跨线程数据污染。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.jlsExecution],
      },
    ],
  },
  {
    title: '面向对象与 Object 契约',
    questions: [
      {
        title: '封装、继承与多态应如何协作，而不是只背三个定义？',
        summary: '封装维护对象不变量，继承表达可替换的“是一个”关系，多态让调用方依赖稳定抽象；三者服务于降低变化传播范围。',
        mechanism: '封装不是简单把字段设为 private，而是把状态变化集中到能检查前置条件并维护不变量的方法中。继承同时复用实现并建立子类型关系，只有子类在父类所有有效使用场景中都可替换父类时才合理，否则组合通常更安全。多态包含实例方法的动态分派：调用点先按静态类型确定合法签名，运行时再按接收者实际类型选择重写实现。字段、静态方法和 private 方法不参与同样的动态分派。良好的抽象应隐藏容易变化的实现细节，并让失败条件、生命周期和并发约束进入契约，而不是只提供一组 getter/setter。',
        example: '支付模块可定义 `PaymentMethod.pay(Money)`，银行卡和余额实现各自校验；订单服务只依赖接口。若为了复用日志让 `OrderService extends Logger`，并不存在“订单服务是日志器”的替换关系，应改为组合 Logger。账户余额应通过 `debit` 校验后修改，而不是暴露 `setBalance` 破坏非负不变量。',
        followUps: [
          { question: '组合为什么通常比实现继承更稳健？', answer: '组合只依赖被组合对象的公开契约，不会继承受保护状态和可重写钩子的隐式耦合，也能在运行时更换策略。' },
          { question: '多态是否只存在于接口调用？', answer: '不是。普通类继承中的实例方法重写同样进行动态分派；接口只是更明确地把抽象契约与具体实现分离。' },
        ],
        pitfalls: ['把封装等同于自动生成 getter/setter，实际上仍把全部状态修改权交给外部。', '为了少写几行代码滥用继承，建立不满足可替换原则的脆弱层次。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.jlsInterfaces],
      },
      {
        title: '方法重写与方法隐藏在绑定时机上有什么根本区别？',
        summary: '实例方法重写根据运行时接收者动态分派；静态方法只能被隐藏，字段也按编译期类型解析，因此同名并不代表同一种多态。',
        mechanism: '子类实例方法在签名、返回类型协变、访问权限和受检异常约束满足时可以重写父类方法，调用点最终执行接收者实际类中最具体的实现。`@Override` 能让编译器验证开发者意图。static 方法属于声明它的类，子类同签名 static 方法只是隐藏，具体选择由限定表达式或引用的编译期类型决定；实例字段同样不存在重写。private 方法对子类不可继承，子类声明同名方法是全新成员。构造器也不被继承。调用 `super.m()` 可显式绕过动态选择，进入直接父类实现，但不能任意跨越层次。',
        example: '若 `Parent p = new Child()`，两类都定义实例 `name()`，则 `p.name()` 调 Child；若两类定义 static `kind()`，`p.kind()` 按 Parent 解析且不建议经实例调用。两类都有字段 label 时，`p.label` 也读 Parent 字段。给预期重写的方法加 `@Override` 可发现参数拼错造成的意外重载。',
        followUps: [
          { question: '重写方法为什么不能缩小访问权限？', answer: '调用方按父类型契约本来有权调用该方法，子类若缩小权限会破坏可替换性，因此只能保持或扩大可见性。' },
          { question: '返回类型协变是什么意思？', answer: '子类重写方法可返回父方法返回类型的子类型，让调用者仍满足原契约，同时获得更具体的结果类型。' },
        ],
        pitfalls: ['把 static 同名方法称为运行时多态，忽略它由编译期声明类型决定。', '省略 Override 注解后意外改变参数列表，把本想重写的方法变成新重载。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.jlsExpressions],
      },
      {
        title: '接口与抽象类该怎样按状态、契约和演进能力选择？',
        summary: '接口适合描述跨层次能力与公共契约，抽象类适合共享受控状态和构造逻辑；是否能写默认方法不是选型的唯一标准。',
        mechanism: '类只能直接继承一个类，却可实现多个接口，因此接口更适合把角色能力正交组合。接口字段隐含 public static final，不能保存每个实例的可变状态；可以声明抽象、default、static 和 private 辅助方法，但 default 方法主要用于兼容性演进和共享少量行为。抽象类可拥有构造器、实例字段、不同访问级别方法以及受保护的实现骨架，适合强关联类型共同维护状态。接口默认方法冲突时，类方法优先于接口默认方法，更具体的子接口优先；仍歧义则实现类必须显式重写并选择。选择时应先问调用方需要什么稳定契约，再看实现是否真有共同状态。',
        example: '缓存组件可暴露 `Cache<K,V>` 接口，让本地和远程实现并存；若多个文件解析器都要维护不可绕过的字符集、资源关闭状态和模板流程，可继承 `AbstractParser`。两个接口都提供同签名 default 方法时，实现类可写 `A.super.reset()` 明确选择，避免隐式歧义。',
        followUps: [
          { question: '接口新增 default 方法一定二进制兼容吗？', answer: '通常能避免旧实现立刻缺少方法，但可能与实现类现有方法或另一个接口默认方法冲突，仍需评估源兼容和行为变化。' },
          { question: '抽象类能否完全替代接口？', answer: '不能。单继承限制会占用类型层次，且抽象类往往携带实现和状态耦合，不适合表达可由无关类共同具备的能力。' },
        ],
        pitfalls: ['仅因接口支持 default 方法就把大量状态相关模板逻辑塞进接口。', '只按“能否多继承”背答案，忽略构造、不变量和版本演进等实际约束。'],
        sources: [OFFICIAL.jlsInterfaces, OFFICIAL.jlsClasses],
      },
      {
        title: '对象初始化顺序为何会让构造器调用可重写方法变得危险？',
        summary: '对象先完成存储默认初始化，再沿父类到子类执行实例初始化和构造器；父构造阶段动态调用可能进入尚未初始化完的子类方法。',
        mechanism: '创建对象时先为全部实例字段赋语言默认值，然后执行构造链。进入子类构造器后，显式或隐式 `super(...)` 必须先执行；父类实例字段初始化器、实例初始化块和构造器主体完成后，才轮到子类对应步骤，各类内部大体按源码顺序执行。static 初始化属于类初始化，只在类首次主动使用前按规范触发，并先初始化父类。危险点是实例方法即使在父类构造器中调用也会动态分派到子类重写，而此时子类字段仍可能是 0 或 null，子类不变量尚未建立。构造阶段应使用 private/final 辅助方法或只处理本层状态。',
        example: '若父构造器调用 `render()`，Child 重写的 render 读取 `config.length()`，而 config 的字段初始化要等父构造结束后才执行，就会空指针。更稳妥的做法是构造器只保存并校验参数，完整对象创建后由工厂调用初始化流程，或让构造期方法不可重写。',
        followUps: [
          { question: '字段初始化器与实例初始化块谁先执行？', answer: '在同一个类中按它们出现在源码中的顺序执行，并且都发生在父类构造完成之后、本类构造器主体之前。' },
          { question: '静态字段初始化失败后再次使用类会怎样？', answer: '初始化线程先收到 ExceptionInInitializerError 等错误，类会被标记为初始化失败，后续主动使用通常得到 NoClassDefFoundError。' },
        ],
        pitfalls: ['在构造器中调用可重写方法，让子类代码观察到仅完成一半的对象状态。', '把字段声明处初始化误认为发生在父类构造之前，错误推断子类字段已就绪。'],
        sources: [OFFICIAL.jlsExecution, OFFICIAL.jlsClasses],
      },
      {
        title: 'public、protected、包访问与 private 的可见边界如何精确判断？',
        summary: '访问控制同时受成员声明、包关系、继承关系和访问表达式静态类型影响；protected 在跨包子类中的规则尤其容易误判。',
        mechanism: 'public 对可读该模块导出包的代码开放，private 只在声明它的顶层类或其嵌套成员组成的 nest 内按语言规则访问；未写修饰符的包访问仅对同包代码可见。protected 包含两部分：同包代码可像包访问一样使用；跨包时只有子类代码可通过继承关系访问，并且对实例成员，访问所经引用必须是当前子类类型或其子类型，不能拿任意父类实例读取 protected 成员。顶层类只能是 public 或包访问。模块系统还会在 public 之外增加包是否 exports、反射是否 opens 的边界。',
        example: '包 a 的 Parent 有 protected `id`，包 b 的 Child 继承 Parent。Child 内可写 `this.id` 或通过 Child 引用访问，却不能写 `new Parent().id`。如果只是希望外部读取标识，应提供稳定 public 方法，而不是扩大字段权限；跨模块还需在 module-info.java 中导出相应包。',
        followUps: [
          { question: '子类对象为什么不代表子类代码一定能访问所有 private 成员？', answer: '访问权限由成员声明位置和当前代码位置决定，private 不因对象运行时类型而向子类开放，应通过父类公开或受保护行为访问。' },
          { question: 'public 类放在未导出的模块包中能被外部模块使用吗？', answer: '通常不能。成员和类的 public 只解决语言级可见性，命名模块还要求所在包被 exports 给调用方模块。' },
        ],
        pitfalls: ['把 protected 简化成“所有子类都能通过任意父类对象访问”。', '直接把字段设为 public 解决编译错误，破坏封装且忽略模块导出边界。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.modules],
      },
      {
        title: '`equals` 与 `hashCode` 契约为什么必须成对设计？',
        summary: '逻辑相等必须满足等价关系，并保证相等对象具有相同哈希值；否则基于哈希的集合会出现查找失败、重复元素等反直觉行为。',
        mechanism: 'Object.equals 默认是引用身份相等，值对象通常按参与身份的字段重写，并满足自反、对称、传递、一致以及对 null 返回 false。hashCode 要求一次执行中对象参与相等判断的状态不变时结果稳定，且 equals 为 true 的两个对象必须返回相同哈希；反向并不要求，不同对象允许碰撞。哈希集合先用 hash 定位区域，再在候选中调用 equals，因此只重写其中一个会破坏查找。可变对象若在加入 HashSet 或作为 HashMap 键后修改参与哈希的字段，条目物理位置不随之搬迁，之后即使拿同一引用也可能按新哈希找不到。',
        example: '用户值对象若以 tenantId 和 userId 定义身份，应让 equals 与 hashCode 使用同一组字段。`Set<UserKey>` 加入 key 后再修改 userId，会让 contains/remove 失败；更好的做法是让键不可变。数组字段不能直接依赖数组的 Object.equals，应按契约选择 Arrays.equals 或 deepEquals。',
        followUps: [
          { question: '为什么不同对象拥有相同 hashCode 并不违反契约？', answer: '哈希值空间有限而对象可能无限，碰撞不可避免；集合在哈希相同后还会调用 equals 区分真正相等与碰撞对象。' },
          { question: '继承层次中扩展 equals 为何容易破坏对称性？', answer: '父类可能接受任意父类型比较，而子类又加入新字段；父看子为相等、子看父为不等，就会破坏对称或传递，值类型常优先组合。' },
        ],
        pitfalls: ['只重写 equals 不重写 hashCode，让逻辑相等对象落入不同哈希区域。', '把可变业务字段放入哈希键，并在入表后继续修改这些字段。'],
        sources: [OFFICIAL.object, OFFICIAL.map, OFFICIAL.set],
      },
      {
        title: '浅拷贝、深拷贝与 `clone` 为什么不能只看对象是否换了地址？',
        summary: '浅拷贝只复制当前对象字段，内部引用仍共享；深拷贝要按领域边界复制可变对象图，Object.clone 本身不会自动完成这一语义。',
        mechanism: 'Object.clone 对可克隆类执行字段级复制：基本字段复制值，引用字段复制引用，所以结果与原对象仍指向同一内部集合或子对象。Cloneable 只是标记接口，没有声明 clone 方法；未实现它却调用 Object.clone 会抛 CloneNotSupportedException，且构造器通常不会按普通创建路径执行。这使 clone 在继承、final 字段和不变量维护上较难设计。深拷贝不是“递归复制一切”的通用动作，应明确哪些值对象可共享、哪些可变实体必须复制，以及循环引用和外部资源如何处理。实践中更常使用复制构造器、静态工厂或显式映射。',
        example: 'Order 含 `List<OrderLine>` 时，`new ArrayList<>(old.lines)` 只复制列表结构，OrderLine 若可变仍被共享。可写 `Order.copyOf`，逐个调用 `line.copy()`，同时共享不可变的 Currency。数据库连接、线程和文件句柄不能靠字段复制获得独立资源，应禁止复制或重新建立资源。',
        followUps: [
          { question: '序列化再反序列化是否是可靠的通用深拷贝？', answer: '通常不是。它要求整张对象图可序列化，成本高，还可能绕开构造不变量、丢失瞬态状态并扩大不可信数据反序列化风险。' },
          { question: '不可变子对象需要深拷贝吗？', answer: '通常可以安全共享，因为外部无法观察到其状态变化；深拷贝应围绕可变性和领域所有权，而不是机械复制每个节点。' },
        ],
        pitfalls: ['认为 clone 会自动递归复制内部对象，修改副本后意外污染原对象。', '用序列化充当所有对象的复制工具，忽略性能、不变量和安全边界。'],
        sources: [OFFICIAL.object, OFFICIAL.serialization],
      },
      {
        title: '怎样设计真正可用的不可变类，而不只是把字段标成 final？',
        summary: '不可变对象在构造完成后对外不再改变可观察状态，需要封闭修改入口、保护可变成员，并避免构造期间逸出。',
        mechanism: '常见做法是类本身不可被不受控继承，字段 private final，通过构造器一次建立并校验不变量，不提供修改内部状态的方法。若参数是可变集合、数组或日期对象，构造时要防御性复制，访问时返回不可变视图或再次复制；仅把引用设为 final 不能阻止外部修改同一对象。构造器中不应发布 this，例如注册监听器或启动线程，否则其他线程可能看到未完成状态。不可变类可以缓存派生值，但缓存字段的可见性与线程安全仍需设计。对深层对象图，应明确元素本身是否不可变，`List.copyOf` 只保证列表结构不可变，不会复制或冻结元素。',
        example: 'Money 可用 final amount、currency，在构造时校验非负并把 BigDecimal 规范到约定 scale；`add` 返回新 Money。Schedule 接收 `List<Slot>` 时应先确认 Slot 不可变，再保存 `List.copyOf(slots)`。若 getter 直接返回内部 Date 或 byte[]，调用方仍能修改内部状态，应返回副本。',
        followUps: [
          { question: '不可变对象为什么通常更适合并发共享？', answer: '构造完成并安全发布后状态不再变化，读取者无需协调后续写入，也不会发生迭代过程中内容被另一线程修改的问题。' },
          { question: '返回 Collections.unmodifiableList 就一定不可变吗？', answer: '不一定。它只是阻止经该视图修改结构；若原始列表仍被其他引用修改，视图会随之变化，元素自身也可能仍可变。' },
        ],
        pitfalls: ['字段虽是 final，却直接保存调用方传入的可变集合或数组。', '返回不可修改视图后宣称深度不可变，忽略后门引用与可变元素。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.collections],
      },
      {
        title: '静态嵌套类、内部类与局部类分别会捕获什么上下文？',
        summary: '静态嵌套类不隐含外部实例，非静态内部类绑定一个外部类对象；局部类和 lambda 只能捕获 final 或有效 final 的局部变量。',
        mechanism: '成员静态嵌套类在语义上接近普通类，只是名字和访问控制嵌套在外部类中，不需要外部实例即可创建。非静态成员内部类实例包含对直接外部实例的关联，可通过 `Outer.this` 访问外部成员，因此长生命周期内部对象可能意外延长外部对象存活。方法内局部类、匿名类和 lambda 可以捕获局部变量，但变量必须是 final 或赋值后从未改变的有效 final；原因是捕获保存的是值而非共享可变栈槽。lambda 的 this 指向词法外围对象，而匿名类拥有自己的 this，这会影响成员解析和生命周期。',
        example: 'Builder 若不需要访问外部对象，应声明为 `static class Builder`，避免每个 Builder 都携带外围实例。GUI 注册 `outer.new Listener()` 到全局事件总线后，即使页面关闭，监听器仍可能通过隐含引用阻止页面回收；应注销监听或改用不持有页面的静态嵌套实现。',
        followUps: [
          { question: '为什么 lambda 捕获的局部变量不能之后再自增？', answer: '局部变量生命周期与 lambda 可能不同，捕获的是其值；要求有效 final 可避免同名局部槽与捕获副本出现令人误解的可变共享语义。' },
          { question: '内部类能声明静态成员吗？', answer: '现代 Java 允许内部类声明静态成员；但它仍然是绑定外围实例的非静态嵌套类，是否需要外部上下文才是选型关键。' },
        ],
        pitfalls: ['默认使用非静态内部类，意外持有体积很大或生命周期更短的外部对象。', '把 lambda 与匿名类的 this 语义视为相同，导致成员访问和解绑逻辑出错。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.jlsExpressions],
      },
      {
        title: '组合优于继承何时成立，如何遵守可替换性？',
        summary: '当关系只是能力复用、策略可替换或生命周期独立时组合通常更稳；只有真正的子类型关系才适合继承，并须保持父类型全部可观察契约。',
        mechanism: '继承同时获得实现与子类型身份，子类会耦合父类受保护状态、构造顺序和可重写钩子，父类内部实现变化也可能破坏子类，这就是脆弱基类风险。组合只保存协作者引用并通过公开契约委托，能够独立替换策略、控制暴露面和分别测试，因此仅为代码复用时通常优先。继承成立的关键是可替换性：接受父类型的代码换成子类后仍应正确，子类不能加强前置条件、削弱后置保证、破坏不变量或引入父契约没有的可观察失败。Java 对访问权限、返回类型和受检异常只提供部分编译检查，业务语义仍需设计者用契约测试保证。',
        example: '正方形强行继承带独立 setWidth、setHeight 的可变矩形，会破坏调用方“只改宽不改高”的预期；应改成共享 Shape 接口或不可变值模型。订单服务需要折扣能力时，持有 `DiscountPolicy` 并委托计算，比继承某个 DiscountBase 更容易按租户替换，也不会暴露基类内部状态。',
        followUps: [
          { question: '模板方法模式是否说明继承仍然有价值？', answer: '是。若算法骨架稳定、扩展点有清晰不变量且类型确实同属一个层次，受控继承能表达设计；应限制可重写面并记录调用顺序。' },
          { question: '组合是否意味着每个方法都机械转发？', answer: '不应如此。组合对象应提供符合自身领域的接口，只在内部协调协作者；若完整暴露被组合对象，仍会泄漏实现并形成强耦合。' },
        ],
        pitfalls: ['仅为复用几行实现建立继承层次，把父类内部变化扩散给所有子类。', '只满足语法上的 extends，却让子类拒绝父类允许的输入或改变核心语义。'],
        sources: [OFFICIAL.jlsClasses, OFFICIAL.jlsInterfaces],
      },
    ],
  },
  {
    title: 'String、异常、泛型、反射与注解',
    questions: [
      {
        title: 'String 为什么不可变，这一设计带来了哪些能力与代价？',
        summary: 'String 创建后字符序列不可改变，使其可安全共享、稳定哈希并适合常量池；所谓修改都会产生新字符串或返回原实例。',
        mechanism: 'String 类是 final，公开 API 不提供修改内部字符序列的操作。不可变让同一字符串可在常量池、类元数据、集合键和多线程间共享，不必担心一方修改内容破坏另一方的安全检查或 hashCode。String 可以缓存哈希值，因为内容一旦建立就不再变化。不可变不等于每个操作必然创建对象：如果结果与原内容相同，某些方法可以返回 this；编译器也能折叠常量表达式。代价是循环拼接、反复替换等变换可能产生中间对象，应使用适合的构建或流式处理方式。敏感秘密若用 String 保存也无法主动擦除底层内容，可考虑受控 char[] 并及时覆盖。',
        example: '例如 `String s = "java"; s.toUpperCase();` 不会改变 s，必须接收返回值。字符串作为 HashMap 键后内容不会变化，因此哈希定位稳定。读取密码时若业务需要尽快清理内存，可使用 char[]，认证完成后 `Arrays.fill(password, (char) 0)`，而不是长期保存不可变 String。',
        followUps: [
          { question: 'String 的 final 是否单独就足以保证不可变？', answer: '不足。final 只阻止子类破坏契约，还需要内部状态不向外暴露、构造时不共享可变存储且所有操作都不原地修改内容。' },
          { question: '不可变 String 是否天然让任意字符串操作线程安全？', answer: '读取和派生新值无需保护原字符串，但共享变量如何重新赋值、多个结果如何组合仍可能需要同步或其他并发控制。' },
        ],
        pitfalls: ['调用 replace、concat 等方法却不接收返回值，误以为原字符串已被修改。', '把不可变等同于零分配，在高频循环中无条件使用连续加号拼接动态内容。'],
        sources: [OFFICIAL.string, OFFICIAL.jlsClasses],
      },
      {
        title: '字符串常量池、`new String` 与 `intern` 到底会产生什么引用关系？',
        summary: '字面量和常量表达式会复用规范化字符串，new String 明确创建普通对象；intern 返回与相同内容池条目关联的规范引用。',
        mechanism: '每个字符串字面量以及由常量表达式得到的字符串都会被 intern，相同内容的此类表达式引用同一规范对象。`new String("x")` 明确创建一个内容相同但身份不同的 String 对象，字面量池对象是否此前存在不改变 new 的身份语义。`s.intern()` 查询按 equals 相同的池条目：存在则返回已有规范引用，否则将该字符串的规范表示加入池并返回对应引用。业务相等应始终用 equals，不能靠 `==` 猜测编译器常量折叠或运行时拼接。主动 intern 可减少大量重复长生命周期字符串，却也会增加池查找、全局池管理与驻留分析成本，必须以真实基数和存活数据验证。',
        example: '例如 `String a = "ja" + "va"; String b = "java";` 因常量折叠，a 与 b 可为同一规范引用；但 `String part = "ja"; String c = part + "va";` 是运行时拼接，`c == b` 不应为 true 的业务假设。`new String("java").intern()` 返回与 b 内容对应的规范引用。',
        followUps: [
          { question: '为什么字符串比较永远优先 equals？', answer: 'equals 表达字符序列相等，符合业务语义；引用身份会受字面量、构造方式、常量折叠和 intern 影响，不稳定也不必要。' },
          { question: '是否应该给所有请求参数调用 intern？', answer: '不应该。高基数字符串会增加全局池压力和查找开销，只有大量重复且生命周期收益经过测量时才值得考虑。' },
        ],
        pitfalls: ['看到部分字面量 `==` 为 true，就把引用相等用于字符串业务判断。', '无指标地对外部高基数字符串全部 intern，增加内存驻留和全局竞争。'],
        sources: [OFFICIAL.string, OFFICIAL.jlsExpressions],
      },
      {
        title: '字符串拼接在编译期和运行期分别可能怎样实现？',
        summary: '编译期常量拼接可直接折叠，运行期拼接由编译器选择等价实现；性能判断应关注循环结构和中间结果，而非死记某个字节码模板。',
        mechanism: '只由常量表达式组成的字符串拼接可在编译期合并并进入常量池。包含变量的 `+` 由 Java 语言定义求值和字符串转换语义，但具体字节码实现不是稳定源码契约：现代 JDK 可使用 invokedynamic 和 StringConcatFactory 选择拼接策略，旧版本常见 StringBuilder 展开。单条表达式通常能被编译器整体优化；循环中 `result = result + item` 每轮都需要基于旧的不可变结果构造新字符串，累计复制可能显著增长。明确次数时可使用 StringBuilder，集合元素连接可用 String.join 或 Collectors.joining，并先确认 null 表示、分隔符和容量。',
        example: '日志标签写 `"order-" + orderId + "-" + status` 通常无需手工拆成构建器；但循环拼接一万行 CSV 应创建一次 StringBuilder，逐行 append，最后 toString。若只是连接名称列表，`String.join(",", names)` 更能直接表达分隔语义，也避免尾部分隔符处理错误。',
        followUps: [
          { question: '为什么不能断言加号一定编译成 StringBuilder？', answer: '语言规范约束结果与求值顺序，不固定编译器的字节码策略；不同 JDK 版本可以采用 invokedynamic 等更合适的实现。' },
          { question: '预估 StringBuilder 容量有什么作用？', answer: '合理初始容量可减少内部存储扩容和复制，但错误的超大预估也会浪费内存，应根据常见输出规模而非极端上限设置。' },
        ],
        pitfalls: ['把旧版本反编译结果当成所有 Java 版本必须遵循的语言规范。', '在循环中反复把不可变结果重新赋值拼接，造成大量累计复制与临时对象。'],
        sources: [OFFICIAL.jlsExpressions, OFFICIAL.string],
      },
      {
        title: '受检异常与非受检异常应如何映射到可恢复性和 API 契约？',
        summary: '受检异常强制调用方处理或声明，非受检异常不做该编译要求；选型应表达调用方能否合理恢复，而不是简单按错误严重程度。',
        mechanism: 'Throwable 下 Error 通常表示运行环境或系统级严重问题，应用一般不应泛化捕获后继续；Exception 中除 RuntimeException 及其子类外属于受检异常，可能抛出的受检异常必须被 catch 或出现在 throws 声明中。非受检异常常用于参数违反前置条件、对象状态非法或编程错误，但也可以表达某些无法在当前层恢复的运行故障。API 设计应给异常提供稳定语义和必要上下文，保持 cause 链，并在有能力增加处理策略的边界做转换。不能恢复的底层异常逐层机械声明会污染接口，而把所有异常包成 RuntimeException 又会丢失调用方可采取的重试、降级或纠正动作。',
        example: '解析用户上传文件格式错误时，可抛带行号的受检 ParseException，让调用方提示修正；向内部方法传负页数属于契约违规，可抛 IllegalArgumentException。仓储层捕获 SQLException 后可转换为领域 DataAccessException，但应保留 cause，并区分唯一键冲突与连接失败。',
        followUps: [
          { question: '捕获 Exception 统一返回失败有什么问题？', answer: '它会混淆可预期业务失败、编程错误和线程中断等不同语义，常导致错误重试、丢失诊断信息或系统带病继续运行。' },
          { question: '重写方法能否声明更宽的受检异常？', answer: '不能突破父方法契约声明更宽的新受检异常，否则按父类型调用的代码将无法预知；可声明更窄子类型或非受检异常。' },
        ],
        pitfalls: ['把受检异常等同于严重故障、非受检异常等同于轻微错误。', '转换异常时只保留消息不保留 cause，切断原始堆栈和诊断链路。'],
        sources: [OFFICIAL.jlsExceptions, OFFICIAL.jlsClasses],
      },
      {
        title: 'try-with-resources 如何处理关闭顺序与被抑制异常？',
        summary: 'try-with-resources 会按声明逆序自动关闭资源；业务异常优先传播，关闭阶段的异常通常作为 suppressed 附着而不是覆盖主因。',
        mechanism: '资源必须实现 AutoCloseable，并在进入 try 前或资源声明处成功初始化。多个资源按从左到右创建、从右到左关闭，适合表达包装流依赖。若 try 主体抛异常 A，close 又抛异常 B，A 作为主要异常传播，B 通过 A.getSuppressed 保存；传统 finally 直接 close 则可能让 B 覆盖 A。若主体正常而 close 失败，关闭异常本身传播。资源初始化到中途失败时，先前已成功创建的资源仍会被关闭。Java 9 起可在满足 final 或有效 final 条件时直接引用既有变量。close 的幂等性并非 AutoCloseable 通用保证，不能随意重复关闭。',
        example: '例如 `try (InputStream in = open(); BufferedInputStream buf = new BufferedInputStream(in)) { return parse(buf); }` 会先关 buf 再关 in。若 parse 抛格式异常且 buf.close 也失败，日志应同时输出主异常及 getSuppressed 内容，不能只打印 message，否则会遗漏资源故障线索。',
        followUps: [
          { question: 'AutoCloseable.close 是否必须幂等？', answer: '接口本身不作统一幂等保证，具体资源文档可能另有约定；调用方应让所有权清晰，避免多处重复关闭同一资源。' },
          { question: '资源构造到第二个时失败，第一个会泄漏吗？', answer: '不会。语法展开保证已成功初始化并纳入管理的前序资源被关闭，尚未成功创建的资源则不存在可关闭实例。' },
        ],
        pitfalls: ['只记录传播异常而不查看 suppressed，漏掉关闭阶段的重要故障。', '在 try-with-resources 外再次关闭同一资源，假设所有 close 都安全幂等。'],
        sources: [OFFICIAL.autoCloseable, OFFICIAL.jlsStatements, OFFICIAL.jlsExceptions],
      },
      {
        title: '泛型擦除后，编译器如何维持类型安全并生成桥接方法？',
        summary: 'Java 泛型主要在编译期检查，类型实参通常在字节码中擦除为边界；必要的强制转换和桥接方法由编译器补充以维持多态。',
        mechanism: '参数化类型在编译时阻止把错误元素写入集合，并在读取处插入所需转换。擦除会把类型变量替换为其最左边界，若无显式边界则通常为 Object，同时保留类文件中的泛型签名元数据供工具和反射读取，但运行时对象并不是每种实参各一份新类。子类用具体类型重写泛型父类方法时，擦除后的签名可能不一致，编译器会生成 synthetic bridge 方法，把擦除签名转发到具体方法，从而保持 JVM 层面的重写关系。擦除也解释了为何不能重载仅泛型实参不同的方法，且不能直接 `new T()` 或 `new T[]`。',
        example: '若 `class Box<T> { T get(); }`，擦除后核心返回类型近似 Object，使用 `Box<String>` 的调用点由编译器插入 String 转换。`class Name implements Comparable<Name>` 会有比较 Name 的方法，并可能生成接收 Object 的桥接方法转发；反射列方法时要留意 `isBridge()`。',
        followUps: [
          { question: '既然擦除，反射为何还能看到 List<String> 字段的 String？', answer: '类文件可保存 Signature 等泛型声明元数据，反射能读取声明信息；但普通 List 实例运行时仍不携带可可靠检查每个元素实参的具体化类型。' },
          { question: '为什么不能重载 `m(List<String>)` 与 `m(List<Integer>)`？', answer: '两者擦除后的 JVM 方法描述符相同，无法在同一个类文件中形成两个可区分的方法，因此编译器直接拒绝。' },
        ],
        pitfalls: ['把类型擦除误解为泛型完全不存在，忽略类文件签名和编译器插入的检查转换。', '把反射读到的声明实参当成任意运行时对象都保存了完整实际类型。'],
        sources: [OFFICIAL.jlsTypes, OFFICIAL.jlsInference, OFFICIAL.jvmsClassFile],
      },
      {
        title: '通配符中的 PECS 原则怎样指导集合 API 的读写边界？',
        summary: '生产 T 的参数使用 `? extends T`，消费 T 的参数使用 `? super T`；通配符描述的是调用方可见能力，而非集合自身可变性。',
        mechanism: '`List<? extends Number>` 表示某一种未知的 Number 子类型列表，可以安全把元素读成 Number，却不能写入 Integer 或 Double，因为实际列表可能是另一具体子类型。`List<? super Integer>` 表示元素类型是 Integer 的某个父类型，可以安全加入 Integer，读取时静态上只能保证 Object。PECS 是 Producer Extends、Consumer Super 的助记法，适合方法参数提高可复用性；一个参数若既读又写同一精确类型，通常直接用 `List<T>`。通配符捕获允许辅助泛型方法把未知类型临时命名，解决例如交换 `List<?>` 元素的问题。返回类型滥用通配符会把复杂性推给调用方，应优先返回清晰的抽象类型。',
        example: '复制 API 可写 `static <T> void copy(List<? extends T> src, List<? super T> dst)`，允许从 List<Integer> 复制到 List<Number>。求和方法只读可接受 `List<? extends Number>`。若要交换任意列表两个位置，可让公开 `swap(List<?> list)` 调用私有 `<T> swapCaptured(List<T> list)` 完成捕获。',
        followUps: [
          { question: '`? extends T` 列表为什么仍能写入 null？', answer: 'null 可转换为任意引用类型，不会违反未知实际元素类型；但它通常没有业务价值，且可能让后续读取产生空值风险。' },
          { question: '方法返回值是否也应该大量使用通配符？', answer: '通常应谨慎。返回通配符会限制调用方正常读写和组合；若没有隐藏型变的明确需求，返回 `List<T>` 等具体契约更友好。' },
        ],
        pitfalls: ['把 extends 列表简单称为“只读集合”，忽略结构仍可能由其他别名修改。', 'API 所有泛型位置都套通配符，令类型推断和调用方代码无谓复杂。'],
        sources: [OFFICIAL.jlsTypes, OFFICIAL.jlsInference],
      },
      {
        title: '原始类型、泛型可变参数与堆污染是怎样发生的？',
        summary: '堆污染指参数化变量引用了不符合其承诺的对象，常由原始类型、未检查转换或泛型可变参数与数组协变交叉造成。',
        mechanism: '原始类型为兼容旧代码而绕过部分泛型检查，例如把 List<String> 赋给原始 List 后可加入 Integer，错误通常延迟到读取处的编译器插入转换。可变参数在运行时以数组承载，但参数化类型通常不可具体化；`T...` 或 `List<String>...` 会产生未检查警告。若方法把该数组暴露、写入不相容参数化对象或交给不可信代码，就可能形成堆污染。`@SafeVarargs` 不是消除风险的开关，只能用于满足声明限制且实现确实不对泛型可变参数执行不安全操作的方法；调用方仍需审查方法体。应优先用 `List<T>` 参数或受控集合工厂。',
        example: '危险方法可把 `List<String>... lists` 先视作 Object[]，再写入 `List<Integer>`，随后读取 String 时抛 ClassCastException。旧接口返回原始 List 时，应在边界逐项校验并复制到类型化集合，而不是直接强转。仅遍历参数且不保存、不写数组的 final/static 方法才可能合理标 SafeVarargs。',
        followUps: [
          { question: '为什么错误常在读取处而不是污染发生处爆发？', answer: '原始写入或未检查转换绕过了编译器约束，运行时集合不检查泛型实参；直到读取处插入的具体类型转换才发现不匹配。' },
          { question: 'SuppressWarnings 能否证明转换安全？', answer: '不能。它只隐藏编译器警告，开发者必须在最小作用域内用外部不变量证明类型确实匹配，并最好在边界做显式验证。' },
        ],
        pitfalls: ['为消除告警大范围添加 SuppressWarnings，掩盖真正的堆污染入口。', '给任意泛型可变参数方法加 SafeVarargs，却仍保存或改写底层数组。'],
        sources: [OFFICIAL.jlsTypes, OFFICIAL.jlsArrays],
      },
      {
        title: '反射调用如何穿过类型检查，又会受到哪些访问与模块边界限制？',
        summary: '反射把类、字段、构造器和方法变成运行时对象，可做动态发现与调用；代价是检查后移，并仍受访问控制和模块封装约束。',
        mechanism: 'Class 可从实例、类字面量或受控类加载获得，再用 getMethod/getField 查询 public 且可继承成员，或用 getDeclaredMethod 等查询当前类声明成员。Method.invoke 会检查接收者、参数数量和可转换性，并把目标方法抛出的异常包装为 InvocationTargetException；调用方应解包 cause。`setAccessible(true)` 不能无条件突破 Java 9 之后的强模块封装，目标包通常还需向调用模块 open，且安全策略和运行环境可能继续限制。反射会削弱重构期检查、增加启动扫描和调用开销，框架常缓存元数据或转成 MethodHandle，但普通业务不应为“灵活”放弃显式接口。',
        example: 'JSON 框架可在启动时扫描 DTO 构造器和访问器，校验一次后缓存 Method，而不是每条记录重复查找。插件系统应先用 ServiceLoader 或公开接口约束实现；若必须访问非公开成员，应在 module-info.java 精确 `opens com.example.dto to framework.module`，不要把整个模块无差别开放。',
        followUps: [
          { question: 'getMethod 与 getDeclaredMethod 的主要区别是什么？', answer: 'getMethod 查找可访问的 public 成员并考虑继承；getDeclaredMethod 只查当前类声明且可返回非 public 成员，但后续调用仍受访问检查。' },
          { question: 'Method.invoke 抛 InvocationTargetException 时应记录哪一层？', answer: '包装异常说明反射调用边界，真正业务失败在 getCause 中；日志应保留两者关系，并按目标异常语义决定转换或传播。' },
        ],
        pitfalls: ['认为 setAccessible 可以在所有 JDK 21 模块配置中无条件突破私有边界。', '在热点循环中重复扫描和查找反射成员，不缓存已验证的元数据。'],
        sources: [OFFICIAL.reflection, OFFICIAL.modules, OFFICIAL.jlsExecution],
      },
      {
        title: '注解的 Retention、Target 与处理阶段如何决定它能做什么？',
        summary: '注解只是结构化元数据；Target 限制标注位置，Retention 决定保存阶段，真正行为来自编译期处理器、框架扫描或显式反射代码。',
        mechanism: '`@Target` 指定注解可用于类型、方法、字段、参数、TYPE_USE 等位置；`@Retention(SOURCE)` 只保留在源码，CLASS 写入类文件但运行时反射默认不可见，RUNTIME 才能被运行时反射读取。`@Inherited` 只影响类级注解沿父类被 getAnnotation 查询的行为，不会让方法注解、接口注解按同样方式普遍继承。重复注解通过 `@Repeatable` 和容器注解表达。注解本身不会拦截方法或校验参数：编译期 annotation processor 可生成源码或资源但不能直接改写既有源码语义；运行时框架则需扫描元数据并通过代理、反射或显式调用实现行为。',
        example: '定义运行时路由注解可写 `@Target(METHOD)` 与 `@Retention(RUNTIME)`，Web 框架启动时扫描并注册处理器。Lombok 风格代码生成发生在编译工具链，不是因为注解自己执行。若自定义 `@Audit` 只标在实现方法，而代理读取的是接口方法，就需明确扫描策略，否则注解存在却不生效。',
        followUps: [
          { question: 'RetentionPolicy.CLASS 何时有价值？', answer: '字节码分析器、编译后工具或代理生成器可以读取类文件元数据，而运行时普通反射无需暴露它，适合构建期或装载期处理。' },
          { question: '@Inherited 为什么对接口实现类通常不起作用？', answer: '其规范只针对类声明注解沿超类链的查询，不把接口注解自动传播给实现类，也不处理成员方法和字段的继承。' },
        ],
        pitfalls: ['给注解加 RUNTIME 就认为业务逻辑会自动执行，实际没有任何处理器读取它。', '依赖 Inherited 传播接口或方法注解，导致代理和实现类扫描结果不一致。'],
        sources: [OFFICIAL.annotations, OFFICIAL.reflection, OFFICIAL.jlsInterfaces],
      },
    ],
  },
]
