import { OFFICIAL } from './shared.js'

export const JAVA_FOUNDATION_CHAPTERS_09_10 = [
  {
    title: 'JVM 运行时、字节码与 GC 基础',
    questions: [
      {
        title: '一段 Java 源码从 javac 编译到 JVM 执行会经过哪些阶段？',
        summary: 'Java 源码先由编译器完成词法、语法、类型检查并生成 Class 文件，运行时再由类加载、验证、链接和初始化把字节码交给解释器或即时编译器执行。',
        mechanism: 'javac 的产物不是特定 CPU 的机器码，而是包含版本号、常量池、字段、方法、属性和字节码的 Class 文件。JVM 加载类后先完成验证与准备；符号引用可以提前解析，也可以在实际使用时按需解析。首次主动使用再触发类初始化。方法首次运行通常可以解释执行，热点代码会收集类型与分支信息并由 JIT 编译为本地机器码；假设失效时还可能去优化并回到较低层执行。因此“编译一次、到处运行”依赖目标 JVM 实现，而不是字节码自己直接被 CPU 执行。',
        example: '排查“本地能运行、服务器报 UnsupportedClassVersionError”时，应同时打印 `javac -version` 和 `java -version`，再用 `javap -verbose App.class` 查看 major version。源码语法通过并不代表目标运行时能识别该 Class 版本，CI 应明确 `--release` 和生产 JDK 基线。',
        followUps: [
          { question: '为什么只设置 `-source` 还不足以保证低版本运行？', answer: '`-source` 主要限制语言语法，不自动阻止引用高版本新增 API；使用 `--release` 才会同时约束语言级别、目标 Class 版本和可见标准库 API。' },
          { question: '字节码是否真的与操作系统完全无关？', answer: 'Class 格式具有平台中立性，但运行仍依赖对应平台的 JVM、标准库和本地组件；JNI、本地文件路径与默认字符集仍可能引入平台差异。' },
        ],
        pitfalls: ['把 javac 生成的字节码误称为可以被 CPU 直接执行的机器码。', '只看源码语法版本，不核对 Class 版本、API 基线和生产 JVM。'],
        sources: [OFFICIAL.jvmsClassFile, OFFICIAL.jlsExecution],
      },
      {
        title: 'Class 文件中的常量池、字段表和方法表分别保存什么？',
        summary: 'Class 文件用结构化表描述一个类型：常量池集中保存字面量与符号引用，字段表和方法表描述成员，Code 等属性再承载方法字节码、异常表和调试信息。',
        mechanism: '常量池中的 Class、NameAndType、Fieldref、Methodref 等条目使用索引互相连接，使字节码能够先表达“哪个类的哪个成员”，再在链接或首次使用时解析为运行时结构。字段表记录访问标志、名称、描述符及属性，并不保存每个实例字段的实际值；方法表同样描述签名和属性，非抽象、非 native 方法通常带 Code 属性，其中包含 max_stack、max_locals、指令序列与异常处理表。泛型签名、注解、行号和局部变量名属于可选属性，可能因编译参数或混淆被移除。',
        example: '面对桥接方法或泛型擦除疑问，可以运行 `javap -v -c Demo.class`，同时观察 descriptor、Signature、ACC_BRIDGE 和指令。不要从反编译出的近似源码倒推 Class 一定保存了完整 Java 源码，因为注释、局部格式和很多语法糖已经消失。',
        followUps: [
          { question: '运行时常量池与 Class 文件常量池完全相同吗？', answer: '不是。Class 文件常量池是静态二进制表，类加载后 JVM 会为类型建立运行时表示，并可把符号引用解析为可直接使用的运行时结构。' },
          { question: '字段的默认值存放在字段表里吗？', answer: '实例字段的实际值位于对象实例中；静态 final 编译期常量可通过 ConstantValue 属性表达，普通静态字段则在准备和初始化阶段处理。' },
        ],
        pitfalls: ['认为常量池只保存字符串和数字，忽略类、字段与方法的符号引用。', '把反编译源码当作原始源码的无损备份，忽略属性裁剪和语法糖还原。'],
        sources: [OFFICIAL.jvmsClassFile],
      },
      {
        title: '类的加载、链接与初始化为什么不能混为一个动作？',
        summary: '加载负责取得二进制并创建类型表示，链接包含验证、准备和解析，初始化才执行静态字段赋值与静态代码块；三者触发条件和失败方式都不同。',
        mechanism: '加载阶段由类加载器按二进制名寻找定义并创建 Class 对象。验证检查文件结构、字节码和类型安全；准备为静态字段分配存储并设置规范默认值；解析把常量池符号引用转换为运行时引用，实现可以选择延迟解析。初始化在首次主动使用前执行编译器合成的 `<clinit>`，并保证父类先初始化、同一个类的初始化在并发下受 JVM 协调。仅获得类字面量、声明数组类型或读取编译期常量不一定触发初始化，反射调用、new、读写非常量静态字段则通常会触发。',
        example: '若 `static final int LIMIT = 10` 被调用方编译期内联，修改提供方常量但不重新编译调用方，旧值仍可能保留。诊断静态初始化失败时，应定位最初的 ExceptionInInitializerError；同一 ClassLoader 中后续使用通常只会看到 NoClassDefFoundError，而不会反复重跑失败逻辑。',
        followUps: [
          { question: '`Class.forName` 与 `ClassLoader.loadClass` 的默认初始化行为有什么差异？', answer: '常用的 `Class.forName(String)` 会请求初始化；`loadClass` 通常只完成加载，是否链接或初始化取决于后续使用和具体调用方式。' },
          { question: '接口初始化是否要求先初始化所有父接口？', answer: '接口初始化规则不同于类；初始化接口不会仅因其父接口存在就把所有父接口依次初始化，但使用到父接口成员时仍可能单独触发。' },
        ],
        pitfalls: ['把准备阶段的默认值误说成源码中静态字段初始化表达式的最终值。', '认为只要拿到 Class 对象就必然执行了目标类的静态代码块。'],
        sources: [OFFICIAL.jlsExecution, OFFICIAL.jvmsRuntime],
      },
      {
        title: 'Java 方法调用时栈帧中的局部变量表和操作数栈如何协作？',
        summary: '每次方法调用都会创建栈帧，局部变量表按槽位保存参数和局部值，字节码再通过操作数栈完成取值、计算、调用与返回，帧还关联当前类的运行时常量池。',
        mechanism: 'Class 文件 Code 属性给出 max_locals 与 max_stack，JVM 据此为一次调用准备足够空间。实例方法的槽位 0 通常是 this，后续槽位依次容纳参数和局部变量；long、double 在 Class 文件局部变量表示中占两个槽位。诸如 iload、iadd、istore 会在局部变量表与操作数栈之间搬运或计算，invoke 指令按描述符从栈中取得接收者与参数并压入返回值。栈帧是抽象规范，具体 JVM 可以优化甚至消除对象或内联方法，不能据此假设固定物理布局。',
        example: '阅读 `int c = a + b` 的字节码时，可以看到加载 a、加载 b、执行 iadd、保存 c 的栈式过程。若递归深度不受控，增长的是线程调用栈而不是 Java 堆；应通过终止条件、迭代改写或显式数据结构解决，单纯增大 `-Xss` 只会推迟风险。',
        followUps: [
          { question: '为什么局部变量不一定按源码声明顺序一直占用槽位？', answer: '编译器可依据变量生命周期复用槽位，且调试信息可能被移除；槽位分配服务于字节码执行，不是源码变量布局的永久映射。' },
          { question: '方法内联后还会保留原来的物理栈帧吗？', answer: '规范描述的是可观察语义，JIT 可以把热点调用内联并消除实际调用开销；去优化时 JVM 仍需依据元数据恢复可解释状态。' },
        ],
        pitfalls: ['把 JVM 规范中的抽象栈帧结构当成所有实现固定不变的内存布局。', '误以为递归造成的 StackOverflowError 可以通过扩大 Java 堆解决。'],
        sources: [OFFICIAL.jvmsRuntime, OFFICIAL.jvmsClassFile],
      },
      {
        title: 'Java 堆、Metaspace 与直接内存分别由谁使用和限制？',
        summary: 'Java 堆主要承载对象实例，Metaspace 在 HotSpot 中承载类元数据，直接内存位于堆外并常被 NIO 使用；三者有不同上限、回收触发与诊断指标。',
        mechanism: '堆由垃圾收集器管理，通常受 `-Xms/-Xmx` 约束。Metaspace 使用本地内存保存类元数据，类卸载依赖其定义类加载器及相关 Class 不再可达，可用 `-XX:MaxMetaspaceSize` 限制。ByteBuffer.allocateDirect 等可能申请直接缓冲区，内存不计入 Java 堆已用量，但仍计入进程 RSS 和容器限额，并受直接内存上限及 Cleaner 回收时机影响。线程栈、代码缓存、GC 辅助结构与 native 库也消耗进程内存，因此 `Xmx` 不能等同于进程最大占用。',
        example: '容器限制 2GB 时把 `-Xmx2g` 设满很危险：直接缓冲区、线程栈和元数据没有余量，进程可能被 cgroup OOM 杀死且没有 Java heap dump。容量规划应同时观察 GC 堆指标、Native Memory Tracking、线程数量、direct buffer pool 和容器 memory.events。',
        followUps: [
          { question: 'Metaspace 满一定说明类数量很多吗？', answer: '不一定；也可能是反复创建无法卸载的类加载器、动态生成类或元数据上限过小，需要按类加载器和类数量继续定位。' },
          { question: 'DirectByteBuffer 对象本身完全位于堆外吗？', answer: '缓冲区引用与管理对象仍在 Java 堆中，真正的大块数据区域位于堆外；对象回收与 Cleaner 才会推进本地内存释放。' },
        ],
        pitfalls: ['把 `-Xmx` 直接当作 Java 进程或容器的总内存上限。', '只看 heap usage 就断言没有内存问题，忽略直接内存、线程栈和元数据。'],
        sources: [OFFICIAL.jvmsRuntime, OFFICIAL.nativeMemory, OFFICIAL.nio],
      },
      {
        title: '对象分配为什么常见 TLAB 快路径，逃逸分析又能优化什么？',
        summary: 'HotSpot 可让线程在自己的 TLAB 中通过移动指针快速分配小对象；JIT 的逃逸分析还可能做标量替换、锁消除等优化，但这些都不是 Java 语言层保证。',
        mechanism: '以 JDK 21 HotSpot 为例，多线程共享堆顶会产生竞争，因此实现通常给线程划分 Thread Local Allocation Buffer，线程在本地缓冲区内分配时只需更新私有指针；对象过大、TLAB 不足或特定布局会走较慢路径。逃逸分析判断对象引用是否可能离开方法或线程，如果证明不逃逸，JIT 可以把对象字段拆成标量、消除实际分配，或移除只保护线程私有对象的锁。分析是保守且依赖编译层级的，代码稍作改变就可能失去优化，业务正确性不能依赖对象一定被栈上分配。',
        example: '基准测试短生命周期 DTO 时，不要只用循环创建对象却不消费结果，JIT 可能把整个分配消除。应使用 JMH 和 Blackhole，配合 GC profiler 查看 allocation rate；生产优化先减少无界分配与大对象，再考虑是否需要分析 TLAB refill 或逃逸失败。',
        followUps: [
          { question: '启用逃逸分析是否意味着对象一定放到线程栈上？', answer: '不能这样保证。常见结果是标量替换或分配消除，具体物理实现由 JVM 决定，规范并没有“所有不逃逸对象必须栈分配”的承诺。' },
          { question: 'TLAB 是否让对象天然线程私有？', answer: 'TLAB 只优化分配过程；对象创建后仍可被发布到其他线程，后续可见性与同步仍必须遵守 Java 内存模型。' },
        ],
        pitfalls: ['把 TLAB 误解成独立小堆，认为其中对象不能被其他线程访问。', '用未防止死代码消除的微基准证明对象分配已经完全没有成本。'],
        sources: [OFFICIAL.hotspotPerformance, OFFICIAL.gcTuning],
      },
      {
        title: '解释执行、分层编译和去优化怎样共同运行热点代码？',
        summary: '以 JDK 21 HotSpot 为例，运行时可先解释字节码并收集画像，再把热点方法分层编译为机器码；当内联或类型假设失效时，通过去优化回到安全执行层。',
        mechanism: 'HotSpot 解释器逐条执行字节码，启动快且便于收集调用次数、分支概率和接收者类型。分层编译会在不同优化级别间迁移热点代码，C1 偏向较快编译与画像，C2 利用画像执行更激进的内联、逃逸分析和循环优化。若已编译代码依赖“这里只有一种实现”等假设，而后续加载的新类打破假设，运行时会使相关机器码失效并在安全点重建解释状态。C1、C2 和具体分层策略是 HotSpot 实现术语，不是所有 JVM 必须采用的 Java SE 语义。',
        example: '压测服务时把前 30 秒与稳态混在一起，会把类加载和 JIT 编译开销误认为业务 P99。应分别记录启动、预热和稳定窗口，并用 JFR 或编译日志观察热点编译与去优化；不要通过手写“预热循环”替代真实请求路径。',
        followUps: [
          { question: 'JIT 编译后方法是否永远不再解释执行？', answer: '不是。代码可能因依赖失效、代码缓存压力或其他运行时决策被去优化，随后回到解释或较低编译层，并有机会再次编译。' },
          { question: '为什么动态分派仍可能被内联？', answer: 'JVM 可根据运行画像发现调用点只有一种或少数接收者类型，生成带守卫的推测内联；新类型出现时再触发去优化。' },
        ],
        pitfalls: ['把 JVM 描述成只能解释或只能编译的二选一运行模式。', '只做单次短基准，不区分冷启动、编译活动和稳态性能。'],
        sources: [OFFICIAL.hotspotPerformance, OFFICIAL.jcmd],
      },
      {
        title: '强引用、软引用、弱引用与虚引用的可达性语义有什么不同？',
        summary: '强引用保持普通可达对象存活；软引用可在内存压力下被清理，弱引用会更积极地被处理，虚引用用于在对象进入 phantom reachable 后配合队列接收清理通知。',
        mechanism: '引用对象把业务引用包装成不同强度，垃圾收集器依据可达性级别处理 referent。SoftReference 的清理策略由实现和内存压力决定，不能承诺固定缓存时长；WeakReference 适合不应阻止 key 或元数据回收的关联，但读取后仍要处理 referent 已消失；PhantomReference 的 get 始终返回 null，必须配合 ReferenceQueue 和额外状态完成堆外资源等后处理。任何引用类型都不能替代显式 close，引用处理时间也不是实时调度。',
        example: '图片缓存若需要容量、命中率和过期时间可预测，应使用有界缓存策略，而不是把 SoftReference 当自动缓存。管理堆外句柄时仍以 try-with-resources 为主，Cleaner 或虚引用只作为调用方遗漏关闭时的兜底，并监控队列消费积压。',
        followUps: [
          { question: 'WeakHashMap 为什么仍可能泄漏 value？', answer: '它只弱引用 key；若 value 直接或间接强引用回 key，就会形成从 map 到 value 再到 key 的强路径，key 不能按预期回收。' },
          { question: '虚引用能否告诉业务对象精确的回收时刻？', answer: '不能。它只会在 GC 按规范处理可达性后进入队列，实际收集与队列消费都没有实时性保证，不应承担业务时序。' },
        ],
        pitfalls: ['使用软引用实现必须精确控制容量和 TTL 的核心业务缓存。', '依赖引用队列代替显式资源释放，却没有兜底线程和积压监控。'],
        sources: [OFFICIAL.references, OFFICIAL.gcTuning],
      },
      {
        title: '年轻代、老年代以及 Minor、Mixed、Full GC 应怎样准确表述？',
        summary: '分代假设利用多数对象短命的事实，把新对象优先放在年轻区域并按存活晋升；但 Minor、Mixed、Full 等术语与具体收集器相关，不能跨 JVM 一概而论。',
        mechanism: '典型分代收集器让 Eden 分配快速进行，年轻代回收复制存活对象并更新年龄，达到阈值或空间压力时晋升。老年代保存较长寿命对象，跨代引用通过记忆集或卡表避免每次扫描整个老年代。G1 使用 Region，但仍维护年轻与老年代角色，Young GC 回收年轻 Region，Mixed GC 在并发标记后同时选择部分老年代 Region；Full GC 通常意味着更重的全堆处理，但触发与停顿行为取决于收集器和版本。不能仅凭一次日志标签断言所有阶段都 Stop-The-World。',
        example: '看到频繁 Young GC 时，先结合分配速率、停顿、晋升量与吞吐判断，而不是立即扩大年轻代。若老年代持续增长且并发周期来不及完成，再检查长期存活对象、Humongous 分配和晋升失败；用统一 GC 日志和业务延迟对齐时间线。',
        followUps: [
          { question: '对象年龄达到阈值就一定晋升吗？', answer: '阈值只是策略输入之一，动态年龄判断、Survivor 空间和担保分配等因素也会影响晋升，具体取决于收集器实现。' },
          { question: 'Full GC 是否等于整段过程完全停顿？', answer: '术语没有跨实现的单一定义，应查看所用收集器和日志阶段；很多实现的 Full GC 很重，但不能仅凭名称推导每一步并发属性。' },
        ],
        pitfalls: ['背诵固定 Eden 与 Survivor 比例，却不说明收集器和版本差异。', '把所有 GC 名称都当作跨 JVM 规范定义的统一术语。'],
        sources: [OFFICIAL.gcTuning, OFFICIAL.jvmsRuntime],
      },
      {
        title: 'OutOfMemoryError 与 StackOverflowError 应如何按内存区域定位？',
        summary: '两类错误都不是简单的“机器没内存”：OOM 可能来自堆、Metaspace、直接内存或线程创建，StackOverflowError 通常来自单线程调用栈耗尽，证据与处理路径不同。',
        mechanism: 'Java heap space 常见于存活集超过堆容量或单次大分配失败；Metaspace 指向类元数据增长；Direct buffer memory 涉及堆外缓冲区；unable to create native thread 还受进程地址空间、线程栈和系统限额影响。StackOverflowError 多由无限递归、过深对象遍历或过大的单帧需求触发。错误消息不是完整根因，容器被内核直接杀死时甚至来不及抛 Java 异常。需要结合 heap dump、类直方图、线程数、NMT、GC 日志和系统事件逐层确认。',
        example: '接口发布后出现 StackOverflowError，应先从栈迹找重复调用链，常见原因包括双向对象 `toString`、递归映射和代理自调用；不要先改 `-Xss`。若报 heap OOM，则保留首个现场并比较 dominator tree 与到 GC Roots 路径，确认是泄漏还是容量确实不足。',
        followUps: [
          { question: '捕获 OutOfMemoryError 后继续提供服务可靠吗？', answer: '通常不可靠，因为关键分配可能继续失败且进程状态已受影响；最多做极小、预分配的诊断或受控退出，不应把捕获当常规恢复策略。' },
          { question: '减小每线程 `-Xss` 一定能解决 native thread OOM 吗？', answer: '它可能降低单线程地址空间占用，但若根因是线程无界创建、系统进程限制或容器内存不足，仍必须修复任务模型和容量约束。' },
        ],
        pitfalls: ['看到 OOM 就盲目增大 `-Xmx`，完全不区分具体内存区域。', '用扩大线程栈掩盖无限递归，导致每线程占用更大并降低可创建线程数。'],
        sources: [OFFICIAL.jvmsRuntime, OFFICIAL.jcmd],
      },
    ],
  },
  {
    title: '现代 Java 特性与版本演进',
    questions: [
      {
        title: '接口的 default、static 与 private 方法分别解决什么问题？',
        summary: 'Java 8 引入接口 default 与 static 方法以支持 API 演进，Java 9 再允许 private 辅助方法复用内部实现；它们都没有改变接口字段只能是常量的规则。',
        mechanism: 'default 方法可被实现类继承或重写，使已有实现类不必因接口新增方法立即修改。若类继承的方法与接口默认方法冲突，类方法优先；多个无关接口提供相同默认签名时，实现类必须显式消歧。接口 static 方法不被实现类继承，只能通过接口名调用。private 方法从 Java 9 起可供接口中的 default 或 static 方法复用，外部实现类不可见。默认方法主要服务 API 演进，不应把接口变成隐藏大量可变业务状态的基类。',
        example: '公共 SDK 给 `PaymentPlugin` 增加可选能力时，可提供无副作用的 default 实现保持二进制兼容；若新能力需要依赖数据库或配置，应优先新增协作对象或新接口，而不是在 default 方法中偷偷访问全局单例。',
        followUps: [
          { question: '两个接口有同名 default 方法时可以依赖导入顺序吗？', answer: '不可以。若没有更具体接口能够决定继承关系，实现类必须重写该方法，并可用 `InterfaceName.super.method()` 显式选择实现。' },
          { question: '接口 static 方法能被实现类对象调用吗？', answer: '不能按继承成员那样调用。它属于声明接口，应使用接口名限定；这也避免 static 工具行为与实例多态混淆。' },
        ],
        pitfalls: ['认为 default 方法会让接口拥有实例字段或构造器。', '把接口 static 方法当作会被实现类继承和动态分派的实例方法。'],
        sources: [OFFICIAL.jlsInterfaces],
      },
      {
        title: '局部变量类型推断 var 能推断什么，又刻意不允许什么？',
        summary: 'Java 10 的 `var` 只让编译器从局部初始化表达式推断静态类型，并不引入动态类型；它不能用于字段、方法参数、返回类型或没有初始化器的局部变量。',
        mechanism: '`var` 是保留类型名而非普通关键字，仅出现在允许的局部变量声明、增强 for 变量和部分 try-with-resources 声明中。推断结果仍是确定的编译期类型，后续赋值必须兼容；不会因为运行时值变化而改变。初始化器不能是裸 null，也不能缺少足够目标类型的数组初始化器或 lambda。匿名类和交叉类型等推断结果可能难以阅读，因此能写不等于应该写，变量名称和右侧表达式必须让类型与意图清楚。',
        example: '`var users = repository.findActiveUsers()` 在方法名与变量名清楚时可减少重复；`var x = service.call()` 若返回类型关系到资源关闭或精度，则显式类型更安全。代码评审应关注可读性和 API 边界，而不是强制全用或全禁。',
        followUps: [
          { question: '`var number = 1` 以后能赋值为 `1L` 吗？', answer: '不能，整数文字 1 使静态类型推断为 int，后续 long 值不能无条件窄化赋给它；运行期也不会重新推断类型。' },
          { question: '为什么 `var f = x -> x + 1` 不能直接编译？', answer: 'lambda 是需要目标函数式接口的多态表达式，单独使用 var 没有提供目标类型；应显式声明 Function 等接口或从方法参数上下文获得目标类型。' },
        ],
        pitfalls: ['把 var 解释为类似 JavaScript 的动态变量，认为类型可随赋值改变。', '在返回值语义不清的长调用链上滥用 var，降低资源和精度审查能力。'],
        sources: [OFFICIAL.jlsStatements, OFFICIAL.jlsInference],
      },
      {
        title: 'record 适合表达什么，为什么它不等于任意不可变对象？',
        summary: 'Java 16 正式提供 record，用紧凑语法声明以状态分量为核心的数据载体，并自动得到访问器、构造器契约及基于分量的 equals、hashCode、toString；但分量对象仍可能可变。',
        mechanism: 'record 隐式继承 java.lang.Record，不能再继承其他类，但可以实现接口。每个分量对应 private final 字段和同名访问器，规范构造器负责给全部分量赋值；紧凑构造器适合校验和规范化输入。自动 equals 比较相同 record 类的分量，hashCode 与 toString 也基于分量。final 只固定字段引用，若分量是可变 List、数组或 Date，外部仍可能修改内部状态，因此需要防御性复制。record 也不适合依赖无参构造、可变代理或实体身份的框架模型。',
        example: '`record Page<T>(List<T> items, int total) { Page { items = List.copyOf(items); } }` 能在构造时封住列表结构；若元素本身可变，还要评估元素复制。JPA 实体通常更需要稳定身份、生命周期与代理，不应仅为了少写 getter 强改为 record。',
        followUps: [
          { question: 'record 的访问器为什么不是传统 JavaBean getter？', answer: '分量 `name` 生成的是 `name()`，而非 `getName()`；依赖 Bean 命名约定的旧框架需要确认是否支持 record 元数据。' },
          { question: '可以在 record 中声明额外实例字段吗？', answer: '不能添加新的非静态实例字段，实例状态由 record header 中的分量完整描述；可以声明静态成员、方法和实现接口。' },
        ],
        pitfalls: ['看到字段是 final 就断言 record 深度不可变，忽略可变分量对象。', '把带实体身份和框架代理需求的持久化模型机械改成 record。'],
        sources: [OFFICIAL.records, OFFICIAL.object],
      },
      {
        title: 'sealed class 如何约束继承集合并帮助穷尽性检查？',
        summary: 'Java 17 正式提供密封类与接口，通过 permits 限制直接子类型；获准子类型必须继续声明为 final、sealed 或 non-sealed，使领域层级边界明确可见。',
        mechanism: 'sealed 声明可以显式列出 permitted direct subclasses，也可在满足同一编译单元等规则时推断。直接子类型必须选择终止继承、继续密封或重新开放，形成可审计的层级。因为编译器能够知道封闭的类型集合，配合模式匹配 switch 时可以做更强的穷尽性检查。密封性只约束继承，不限制对象创建数量，也不自动实现不可变。跨模块使用还受 named module 或包等可访问范围约束，不能把 permits 当运行时插件注册表。',
        example: '支付结果可以定义 `sealed interface PayResult permits Success, Declined, RetryableFailure`，业务 switch 必须处理每个分支；第三方支付插件则不适合密封，因为其实现集合需要独立扩展，应改用普通接口和 ServiceLoader 或显式注册。',
        followUps: [
          { question: 'non-sealed 子类会发生什么？', answer: '它重新开放从该分支继续继承，后续子类不再需要出现在原 sealed 类型 permits 列表中，因此穷尽推理只能基于直接层级语义。' },
          { question: 'sealed 与 final 的区别是什么？', answer: 'final 完全禁止继续继承；sealed 允许一组受控的直接子类型，并要求这些子类型明确下一步是封闭、继续受控还是开放。' },
        ],
        pitfalls: ['把 sealed 当作对象不可变或单例机制，而不是继承边界。', '在需要第三方自由扩展的 SPI 上使用 sealed，破坏插件生态。'],
        sources: [OFFICIAL.sealed, OFFICIAL.jlsClasses],
      },
      {
        title: 'switch 表达式的箭头分支和 yield 如何减少穿透错误？',
        summary: 'Java 14 正式提供 switch 表达式：箭头分支默认不穿透，多语句分支用 yield 提供结果，编译器还会检查穷尽性和每条可达路径是否完成求值。',
        mechanism: '传统冒号标签仍可用于语句或表达式，但保留穿透语义；箭头标签只执行右侧表达式、块或 throw，不需要 break。作为表达式时，每个正常完成的分支必须提供兼容结果，块内使用 yield 而不是 return 把值交给 switch。对 enum 和封闭类型，编译器可利用已知分支检查穷尽性；即使省略显式 default，编译产物也会考虑二进制演进出现未知常量的情况。null 处理则取决于所用模式与版本规则，不能默认所有 switch 都安全接受 null。',
        example: '`var fee = switch (level) { case VIP -> 0; case NORMAL -> 10; case UNKNOWN -> { audit(); yield 20; } };` 把赋值和分支绑定在一起。迁移旧 switch 时要先确认原代码是否故意利用穿透，不能机械替换冒号。',
        followUps: [
          { question: 'yield 与 return 的作用域有什么不同？', answer: 'yield 只结束当前 switch 表达式分支并提供其值；return 结束整个方法或 lambda，不能拿来替代普通的 switch 分支结果。' },
          { question: 'enum switch 已覆盖全部常量，为何仍要关注版本升级？', answer: '调用方编译后可能遇到运行期新增枚举常量；即使源码看似穷尽，跨版本二进制演进仍需测试异常路径和兼容策略。' },
        ],
        pitfalls: ['在箭头分支后继续写 break，混淆新旧两套控制流。', '机械迁移存在有意穿透的旧 switch，导致行为变化却没有回归测试。'],
        sources: [OFFICIAL.switchExpressions, OFFICIAL.jlsStatements],
      },
      {
        title: 'instanceof 与 switch 的模式匹配怎样结合类型检查和变量绑定？',
        summary: 'instanceof 类型模式在 Java 16 正式提供，switch 模式匹配在 Java 21 正式提供；它们把测试、转换和变量绑定结合，并检查作用域、支配关系与穷尽性。',
        mechanism: '`obj instanceof String s` 只有匹配成功路径才让 s 进入作用域，流敏感分析允许在 `&&` 右侧使用 s，却不允许在可能未匹配的路径使用。模式 switch 按标签顺序和支配关系匹配，更宽泛的类型不能挡在更具体类型之前；守卫条件可进一步细分。对 sealed 层级可做穷尽检查，并可显式处理 null。模式匹配减少手工强转，但不会改变运行时类型系统，也不能绕过泛型擦除去匹配 `List<String>`。',
        example: '处理 `Object payload` 时可写 `if (payload instanceof String text && !text.isBlank())`，避免重复强转。使用 switch 解析事件层级时，把 `case Payment p when p.amount() > 0` 放在普通 Payment 分支之前，并为 null 与未知开放实现保留明确策略。',
        followUps: [
          { question: '为什么不能写 `obj instanceof List<String> list`？', answer: '参数化类型的实际类型实参通常被擦除，运行时无法可靠区分 List<String> 与 List<Integer>，只能匹配可具体化类型如 List<?>。' },
          { question: '模式变量可以在 `||` 右侧使用吗？', answer: '通常不能，因为左侧匹配失败时仍可能求值右侧，此时变量没有成功绑定；编译器按控制流确保变量只在确定匹配的路径可用。' },
        ],
        pitfalls: ['把模式匹配理解成运行时保留完整泛型实参。', '把宽泛 Object 分支放在具体类型之前，造成后续模式被支配而不可达。'],
        sources: [OFFICIAL.patterns, OFFICIAL.jlsExpressions],
      },
      {
        title: '文本块解决了哪些多行字符串问题，又会保留哪些空白语义？',
        summary: 'Java 15 正式提供文本块，用三引号表达多行字符串并统一处理共同缩进，减少 JSON、SQL 和 HTML 的转义噪声；它仍是普通 String。',
        mechanism: '文本块在编译期经过换行规范化、附带缩进移除和转义处理，开头分隔符后通常需要换行。关闭分隔符的位置会影响共同缩进，`\\s` 可显式保留空格，行末反斜线可抑制换行。它不是模板字符串，不会自动把 `${name}` 替换为变量，也不会验证其中 JSON 或 SQL 的语法。编译结果仍是 String，因此与等价普通字符串的 equals 语义相同，并可能成为编译期常量。',
        example: '测试夹具可以用文本块保存 JSON，再交给真实解析器校验；SQL 仍应使用参数化查询，不能因为文本块可读就字符串拼接用户输入。若快照测试对换行敏感，应显示断言最终字符串或使用 `stripIndent`，不要靠编辑器外观猜测。',
        followUps: [
          { question: '文本块会自动使用当前操作系统换行符吗？', answer: '源代码中的行终止符会按语言规则规范化，不能把文本块当作平台原生行分隔符生成器；需要平台换行时应明确处理。' },
          { question: '为什么关闭分隔符向左或向右移动会改变结果？', answer: '它参与计算附带缩进边界，位置变化可能改变每行被移除的共同空白；应通过测试确认序列化协议中的精确字符。' },
        ],
        pitfalls: ['把文本块当成带变量插值和语法校验的模板语言。', '仅凭编辑器显示判断精确空白，忽略缩进裁剪与尾随换行。'],
        sources: [OFFICIAL.string, OFFICIAL.jlsExpressions],
      },
      {
        title: 'Java 模块系统中的 requires、exports 与 opens 各控制什么？',
        summary: 'Java 9 引入模块系统：`requires` 声明模块依赖，`exports` 控制公开包，`opens` 主要允许深反射访问；模块边界位于类的 public 可见性之外。',
        mechanism: 'module-info.java 为 named module 描述可读性与可访问性。一个 public 类只有位于被 exports 的包中，其他读取该模块的模块才能按普通方式使用。opens 可以对所有模块或特定模块开放包的深反射，不等于导出普通 API；open module 则整体开放反射。requires transitive 会让依赖可沿 API 暴露，requires static 可表达编译时需要而运行时可选。classpath 上的 unnamed module 与 module path 行为不同，迁移框架时常见问题是反射访问被模块边界拒绝。',
        example: '实体模块只需让 Hibernate 反射字段时，可用定向 `opens com.example.entity to org.hibernate.orm.core`，不必把整个包 exports 给所有调用方。迁移前用 jdeps 检查依赖，但仍需集成测试代理、序列化和测试框架的反射路径。',
        followUps: [
          { question: '包中类声明 public 后是否自动对其他模块可见？', answer: '不是。目标模块还必须 exports 该包，调用模块也要读取目标模块；类级 public 与模块级导出两层条件缺一不可。' },
          { question: 'exports 能替代 opens 让框架访问 private 字段吗？', answer: '不能。exports 支持公开成员的正常访问，深反射访问非公开成员通常需要 opens，并仍受具体反射 API 与安全约束影响。' },
        ],
        pitfalls: ['把 exports 和 opens 都理解成简单的“公开包”，忽略正常访问与深反射差异。', '为解决一个反射错误直接声明 open module，扩大整个模块的封装面。'],
        sources: [OFFICIAL.modules, OFFICIAL.reflection],
      },
      {
        title: '虚拟线程为什么适合阻塞式高并发 I/O，却不提高 CPU 密集计算吞吐？',
        summary: 'Java 21 正式提供虚拟线程；它是 JVM 调度的轻量 Thread，能让大量阻塞式任务保持直接风格并在阻塞时释放载体线程，但不会增加 CPU 核心。',
        mechanism: '平台线程通常映射昂贵的操作系统线程，虚拟线程由 JVM 在较少 carrier threads 上调度。遇到支持的阻塞操作时，虚拟线程可卸载，载体去运行其他任务，因此 thread-per-request 在 I/O 等待占比高时更易扩展。它仍遵守 Thread API 和内存模型，不应池化虚拟线程来复用稀缺资源；数据库连接等真正稀缺资源仍需信号量或连接池限流。长时间 CPU 计算会持续占用载体和核心，某些 native 或同步场景还可能造成 pinning，必须用 JFR 和负载测试确认。',
        example: '聚合服务并发调用三十个下游时，可为每个请求创建虚拟线程并保持同步代码，但数据库连接池仍限制为容量值，并设置超时和取消。若任务是图片编码或模型推理，虚拟线程不会凭空增加 CPU，应使用有界并行度和任务队列。',
        followUps: [
          { question: '虚拟线程是否应该放进固定大小线程池？', answer: '通常不应该，虚拟线程本身廉价且设计为按任务创建；需要限制的应是数据库连接、外部 QPS 或内存等稀缺资源，而非线程对象数量。' },
          { question: 'ThreadLocal 在虚拟线程中还能使用吗？', answer: '语义上可以且每个虚拟线程独立，但海量线程上的大对象 ThreadLocal 会放大内存占用；上下文传递与生命周期仍需谨慎设计。' },
        ],
        pitfalls: ['把虚拟线程宣传成让 CPU 密集任务线性加速的并行计算方案。', '取消所有下游限流，误以为线程轻量就代表数据库和远端服务容量无限。'],
        sources: [OFFICIAL.virtualThreads, OFFICIAL.thread],
      },
      {
        title: '升级 Java 版本时为什么要区分源码、二进制和行为兼容？',
        summary: '源码兼容关注能否重新编译，二进制兼容关注旧 Class 能否链接，行为兼容关注同一程序运行结果是否改变；版本升级必须分别验证，不能只看编译通过。',
        mechanism: '删除方法、改变字段静态性或不兼容的层级修改可能让旧字节码在链接时抛 NoSuchMethodError、IncompatibleClassChangeError 等；新增重载则可能使重新编译后的方法选择改变，即源码能编译但行为不同。标准库实现、GC、默认字符集、强封装和反射限制也可能改变运行表现。`--release` 能控制编译目标，却不验证第三方依赖、代理、JNI 和运行参数。可靠升级要固定构建工具链，扫描内部 API，重编译并跑单元、集成、性能和回滚测试。',
        example: '从 Java 8 升到 21 时，先在 CI 生成依赖与 jdeps 报告，清理 `sun.*` 使用，再用目标 JDK 全量重编译。灰度阶段比较 GC、启动时间、线程、TLS 与序列化行为；保留旧 JDK 构建物，避免只升级运行时后无法快速回滚。',
        followUps: [
          { question: '旧 jar 在新 JDK 上能启动是否证明兼容完成？', answer: '不能。冷门路径可能尚未加载相关类，反射、序列化、时区、加密和性能变化也可能只在特定请求或数据下出现。' },
          { question: '为什么新增一个重载也可能改变客户端行为？', answer: '客户端重新编译时会按新的候选集合重新做重载解析，可能选中更具体的新方法；旧字节码则仍引用原方法描述符，两者结果可能不同。' },
        ],
        pitfalls: ['把“能启动”和“编译通过”当作版本升级全部验证。', '只升级本地 JDK，不固定 CI、生产镜像、编译 `--release` 和回滚构建物。'],
        sources: [OFFICIAL.jlsBinary, OFFICIAL.jvmsClassFile],
      },
    ],
  },
]
