import { OFFICIAL } from './shared.js'

export const JAVA_FOUNDATION_CHAPTERS_04_06 = [
  {
    title: 'Collections 基础与选型',
    questions: [
      {
        title: 'List、Set、Queue 与 Map 分别承诺什么语义，选型时先看什么？',
        summary: '先按业务不变量选择接口：List 表达有序序列，Set 表达不重复元素，Queue 表达待处理次序，Map 表达键到值的关联；性能与具体实现应放在语义之后判断。',
        mechanism: 'Collection 是元素容器的根接口，List 进一步承诺按位置访问并允许重复，Set 约束元素不能按其相等性重复，Queue 用插入、检查和移除方法描述处理顺序；Map 不继承 Collection，它维护键值映射并分别提供 keySet、values 和 entrySet 视图。接口只给出契约，不自动保证线程安全、排序方式或复杂度。例如 Set 的“不重复”依赖实现采用的相等性规则，Queue 也不必都是先进先出。工程选型应依次确认是否需要重复、稳定顺序、按键定位、优先级、并发访问和空值，再用真实数据规模验证复杂度与内存成本。',
        example: '订单明细需要保留录入次序且同一商品可出现多行，可用 `List<OrderLine>`；已授权权限集合强调去重，可用 `Set<Permission>`；异步任务按优先级消费可用 `PriorityQueue<Job>`；用户编号查档案则用 `Map<Long, Profile>`。不要因为“查找快”就把每种数据都塞进 Map，否则会丢掉顺序或重复等业务语义。',
        followUps: [
          { question: '为什么不应该只凭大 O 复杂度选择集合？', answer: '复杂度通常描述平均或渐进成本，未覆盖元素语义、顺序保证、内存占用、缓存局部性、并发条件以及数据量很小时的常数成本。' },
          { question: 'Map 的 values 视图是不是一个 Set？', answer: '不是，多个键可以映射到相等的值，因此 values 返回 Collection；keySet 才按键的唯一性表现为 Set 视图。' },
        ],
        pitfalls: ['把接口契约和某个常见实现的内部结构混为一谈。', '为了理论查询速度牺牲业务需要的重复或顺序语义。'],
        sources: [OFFICIAL.collections, OFFICIAL.collection, OFFICIAL.map],
      },
      {
        title: 'List<Integer>.remove(1) 为什么删除索引而不是数值 1？',
        summary: '因为 List 同时重载了 `remove(int index)` 与 `remove(Object value)`；整数字面量 1 精确匹配基本类型参数，所以调用的是按索引删除，而不是按相等性删除元素。',
        mechanism: 'List 声明两个同名方法：`E remove(int index)` 删除指定位置并返回旧元素，`boolean remove(Object o)` 删除首次出现的相等元素。编译器在编译期依据实参静态类型执行重载解析；字面量 1 的类型是 int，与 remove(int) 无需装箱即可适用，而 remove(Object) 需要先把 int 装箱为 Integer 再做引用扩宽，因此前者更具体。泛型擦除不会消除这个区别，因为两个方法擦除后的参数仍分别是 int 与 Object。若实参变量静态类型为 Integer，remove(int) 不能通过拆箱与 remove(Object) 同时随意猜测，重载规则会选择可用且最具体的方法；把返回值当作删除是否成功也会因所选重载不同而产生误判。',
        example: '`List<Integer> nums = new ArrayList<>(List.of(1, 1, 2)); nums.remove(1);` 删除索引 1 的第二个元素，结果是 `[1, 2]`。如果列表为 `[9, 1, 2]`，同一句会删掉数值 1 只是巧合。明确按值删除应写 `nums.remove(Integer.valueOf(1))`，或使用 `nums.removeIf(n -> n == 1)` 表达删除全部匹配值；按索引删除则先检查边界并保留 int 参数。',
        followUps: [
          { question: '把 1 赋给 Integer 变量再调用 remove 会怎样？', answer: '实参的静态类型成为 Integer，`remove(Object)` 可直接接收该引用，调用表达的是按相等性删除首次出现的数值 1。' },
          { question: '为什么不能根据返回值类型反推要调用哪个 remove？', answer: 'Java 的重载解析主要由方法名与实参类型决定，不能仅凭期望接收 boolean 或 Integer 来选择这两个重载。' },
        ],
        pitfalls: ['看到集合元素类型是 Integer，就忽略 int 重载仍然存在。', '测试数据中索引和值恰好相同，导致按索引删除的缺陷未被发现。'],
        sources: [OFFICIAL.list, OFFICIAL.jlsConversions, OFFICIAL.jlsExpressions],
      },
      {
        title: '不可修改视图与真正的不可变集合有什么区别？',
        summary: '`Collections.unmodifiableXxx` 通常只是阻止通过当前引用修改底层集合的视图，而 `List.of`、`Set.of`、`Map.of` 创建的是自身不可修改的值集合，两者对别名变化的可见性不同。',
        mechanism: '不可修改包装器把读取委托给传入集合，并让自身的结构修改方法抛出 UnsupportedOperationException；如果调用方仍持有原集合引用，原集合变化会立即反映到包装视图。工厂方法 List.of、Set.of 和 Map.of 创建的集合不允许增加、删除或替换元素，也拒绝 null；Set.of 还拒绝重复元素，Map.of 拒绝重复键。不可修改只约束集合结构，不会深拷贝元素：元素本身若可变，其字段仍可变化。复制时可使用 copyOf 获得不随原可变容器变化的集合快照，但同样不是元素的深复制。',
        example: '配置中心可以执行 `var snapshot = Map.copyOf(mutableConfig)` 后再发布给读线程，之后修改 mutableConfig 不会改变 snapshot。若改成 `Collections.unmodifiableMap(mutableConfig)`，维护线程更新原 Map 时，读者看到的视图也随之变化。即便使用 Map.copyOf，若 value 是可变的 `ConfigItem`，修改该对象字段仍会被快照中的引用观察到。',
        followUps: [
          { question: '不可修改集合是否天然线程安全？', answer: '不等价。真正不可变且元素也安全发布时适合并发读取；包装视图若背后仍被并发修改，仍可能产生竞态或可见性问题。' },
          { question: 'List.copyOf 一定会创建新的底层数组吗？', answer: 'API 只承诺返回不可修改且包含相同元素的列表，不承诺对象身份或具体复制策略，调用方不应依赖内部是否复用。' },
        ],
        pitfalls: ['把 unmodifiable 包装器误当成与原集合隔离的快照。', '误以为集合不可修改就代表其中每个元素都不可变。'],
        sources: [OFFICIAL.collections, OFFICIAL.list, OFFICIAL.map],
      },
      {
        title: 'TreeSet 或有序 Map 的比较器为什么要与 equals 一致？',
        summary: '基于排序的集合通常把比较结果为零视为“同一个键”；若 comparator 与 equals 对相等性的判断不一致，集合虽然可能符合自身排序契约，却会违背使用者对 Set 或 Map 的直觉。',
        mechanism: 'Comparator.compare 返回负数、零或正数决定全序关系，并应满足反对称、传递等约束。TreeSet 与 TreeMap 依据自然顺序或 Comparator 导航树结构，比较结果为零时不会再保留一个独立集合键。因此两个 equals 不同但 compare 为零的对象，在 TreeSet 中可能只留下一个；反过来 equals 相同而 compare 非零，会破坏 Set 以 equals 理解唯一性的常规约定。比较器链应把真正用于区分键的字段补齐，并正确处理 null。不能用两个整数相减代替比较，因为溢出可能反转结果。',
        example: '若员工比较器只写 `Comparator.comparing(Employee::department)`，同部门的 Alice 与 Bob 比较为零，放入 TreeSet 后会丢掉一个。可按业务身份继续写 `.thenComparing(Employee::id)`。比较年龄时使用 `Comparator.comparingInt(Employee::age)` 或 `Integer.compare(a.age(), b.age())`，不要写 `a.age() - b.age()`。',
        followUps: [
          { question: 'Comparator 返回零是否表示两个引用完全相同？', answer: '不表示，它仅说明在该比较关系下处于同一排序位置；对象身份和 equals 结果都可能不同。' },
          { question: '排序稳定性能修复错误的比较器吗？', answer: '不能。稳定排序只保留比较为零元素的原相对次序，不会补足传递性，也不会改变有序集合对零结果的键判定。' },
        ],
        pitfalls: ['比较器只覆盖展示字段，却拿它充当集合键的唯一规则。', '用整数相减实现比较，忽略溢出和比较契约被破坏。'],
        sources: [OFFICIAL.comparator, OFFICIAL.set, OFFICIAL.map],
      },
      {
        title: 'LinkedHashMap 的插入顺序与访问顺序有什么差别？',
        summary: 'LinkedHashMap 可按首次插入顺序迭代，也可配置为按最近访问顺序迭代；后者配合 removeEldestEntry 能实现简单的有界 LRU，但并不自动具备并发安全。',
        mechanism: 'LinkedHashMap 在散列映射之外维护条目的双向顺序关系。默认 insertionOrder 中，替换已有键的值不会把条目移到末尾；构造时启用 accessOrder 后，get、getOrDefault 以及部分成功访问条目的更新方法会调整访问次序，最久未访问条目位于迭代前端。子类可覆写 removeEldestEntry，在插入新映射后根据 size 决定是否移除最老条目。访问顺序模式下，一次 get 会改变内部顺序，因此不能把“只有读取”误判为无结构变化；外部同步、容量权重、过期与加载合并仍需另外设计。',
        example: '本地保存最近 100 个模板可定义 `new LinkedHashMap<>(128, 0.75f, true)`，并让 `removeEldestEntry` 在 `size() > 100` 时返回 true。这个方案适合单线程或显式加锁的小缓存；若对象大小差异大、需要按时间过期或高并发统计，应该使用专门缓存组件，而不是继续给该 Map 叠加脆弱逻辑。',
        followUps: [
          { question: '在访问顺序模式调用 get，为什么迭代器可能受影响？', answer: '成功访问会调整条目在顺序链中的位置，属于影响迭代结构的操作，因此与并发迭代组合时不能按纯读取处理。' },
          { question: 'removeEldestEntry 能否表达精确的 TTL？', answer: '它只在加入新映射后获得移除最老条目的机会，不能主动按时间驱逐，也不保证空闲期间及时清理过期项。' },
        ],
        pitfalls: ['把简单条目数上限当成具备 TTL 和权重控制的完整缓存。', '访问顺序模式下无锁并发 get，忽略它会重排内部顺序。'],
        sources: [OFFICIAL.map, OFFICIAL.collections],
      },
      {
        title: '为什么实现栈和双端队列通常优先使用 Deque？',
        summary: 'Deque 同时定义队首与队尾操作，可直接表达栈和队列；ArrayDeque 通常是内存中的通用选择，但它不接受 null，也没有容量限制和并发保证。',
        mechanism: 'Deque 为两端操作分别提供抛异常版本 addFirst、removeFirst、getFirst，以及用特殊值表示失败的 offerFirst、pollFirst、peekFirst；栈语义则可用 push、pop、peek。ArrayDeque 基于可增长数组维护环形逻辑位置，两端操作通常为摊销常数时间，不需要为每个元素建立链式节点。null 被禁止，是因为 poll、peek 的 null 需要表示队列为空。选择方法族时要让“容量满或为空”成为显式控制流：有界队列通常偏向 offer/poll，编程错误或必须成功的场景才适合 add/remove。',
        example: '解析括号可写 `Deque<Character> stack = new ArrayDeque<>();`，遇到左括号 `push`，遇到右括号 `pop` 并核对类型。广度优先搜索则用 `offerLast(node)` 与 `pollFirst()`。不要再用继承 Vector 的 Stack 作为默认答案，也不要向 ArrayDeque 放 null 充当结束标记；结束状态应使用单独信号或封装类型。',
        followUps: [
          { question: 'offer 与 add 的核心区别是什么？', answer: '在受容量限制的队列中，offer 用返回 false 表示无法加入，而 add 按 Collection 契约通常抛出 IllegalStateException。' },
          { question: 'ArrayDeque 可以在多个线程间无锁共享吗？', answer: '不可以，它没有并发安全保证；生产者消费者场景应选择 BlockingQueue 等并发容器或提供明确同步。' },
        ],
        pitfalls: ['用 null 作为空队列或结束标记，混淆特殊值方法的语义。', '只因为方法名像栈就默认选 Stack，忽略更合适的 Deque 接口。'],
        sources: [OFFICIAL.deque, OFFICIAL.collection],
      },
      {
        title: 'PriorityQueue 为什么不能当成“随时完全有序的 List”？',
        summary: 'PriorityQueue 只保证队首是当前最小或最高优先级元素，内部迭代顺序没有排序承诺；若需要完整有序输出，必须逐个移除或复制后排序。',
        mechanism: 'PriorityQueue 按自然顺序或 Comparator 维护堆不变量：父位置不劣于子位置，因此 peek 和 poll 能取得队首，而其余元素只需满足局部关系。offer 与 poll 通常为对数时间，peek 为常数时间；iterator 不承诺按优先级遍历。相同优先级元素的先后不确定，若业务需要稳定次序，比较键中必须加入序号等决胜字段。队列不允许 null，也不是线程安全的。更重要的是，入队后修改参与比较的字段不会触发自动重排，会破坏调用者对优先级的判断。',
        example: '调度任务可比较 `priority`，再用递增 `sequence` 保证同优先级按进入次序执行：`comparingInt(Task::priority).thenComparingLong(Task::sequence)`。展示队列时不能直接遍历原 PriorityQueue 声称已经排序，可复制到列表后 sort；消费时则连续 poll。已经入队的任务若要改优先级，应先 remove，再修改并重新 offer。',
        followUps: [
          { question: 'PriorityQueue 的 iterator 为什么看起来有时像有序？', answer: '堆数组的局部结构可能让前几个元素呈现某种顺序，但 API 未承诺全序，任何依赖这种观察结果的代码都不可靠。' },
          { question: '怎样保证同优先级任务先进先出？', answer: '把单调递增序号加入比较器作为第二排序键，并确保序号在任务入队后保持不变。' },
        ],
        pitfalls: ['直接遍历 PriorityQueue，并把输出当成完整排序结果。', '元素入队后修改比较字段，却期待堆结构自动重新定位。'],
        sources: [OFFICIAL.priorityQueue, OFFICIAL.comparator],
      },
      {
        title: 'subList、keySet 与 entrySet 为什么既方便又容易埋坑？',
        summary: '这些对象通常是原集合的受支持视图，而不是独立副本；通过视图进行允许的修改会作用于原容器，原容器发生不协调的结构变化也可能让视图操作失效。',
        mechanism: 'List.subList 返回指定区间的视图，视图中的 set、add、remove 会映射到原列表。若原列表通过视图之外的路径发生结构修改，之后使用该 subList 的语义可能变得未定义并常表现为并发修改异常。Map 的 keySet、values 和 entrySet 同样由 Map 支撑，通过迭代器 remove、集合 remove 或 entry.setValue 等受支持操作可以修改 Map，但是否支持增加取决于视图契约，通常不能凭一个键或值构造完整映射。视图适合原地批量操作；若需要生命周期隔离、跨层返回或长期缓存，应显式复制。',
        example: '删除列表中间一段可以执行 `list.subList(from, to).clear()`，它会直接缩短原 list。若接口准备返回最近十条记录，不能把 `records.subList(0, 10)` 长期暴露出去，因为调用方修改它会影响 records，且 records 后续追加也会让旧视图不可靠；应返回 `List.copyOf(records.subList(0, 10))`。',
        followUps: [
          { question: '从 map.keySet 删除一个键会怎样？', answer: '如果该操作受实现支持，对应的键值映射会从原 Map 删除，因为 keySet 是由该 Map 支撑的视图。' },
          { question: '为什么长期保存很小的 subList 还可能占用较多内存？', answer: 'API 不保证其内部表示完全独立；部分实现的视图会继续引用原列表结构，因此复制能明确生命周期和内存边界。' },
        ],
        pitfalls: ['把集合视图当成已经与原数据隔离的普通副本。', '在保留 subList 时又从原列表路径做结构修改，随后继续使用旧视图。'],
        sources: [OFFICIAL.list, OFFICIAL.map],
      },
      {
        title: 'Arrays.asList、List.of 与 Stream.toList 得到的列表有何不同？',
        summary: '三者都可能让 add 或 remove 失败，但原因与其他能力不同：Arrays.asList 是定长数组视图，List.of 是拒绝 null 的不可修改集合，Stream.toList 返回不可修改列表且可包含 null。',
        mechanism: 'Arrays.asList 返回由原数组支撑的固定大小 List，因此 set 会同步改动数组，但 add、remove 因改变大小而抛 UnsupportedOperationException；基本类型数组作为单个对象传入时，会得到只有一个数组元素的列表。List.of 创建不可修改列表，拒绝 null，并对 Set.of、Map.of 额外检查重复。Stream.toList 的契约是按遭遇顺序返回不可修改 List，没有声明拒绝 null；它与 `collect(Collectors.toList())` 不等价，后者并未在 API 契约中承诺具体类型、可修改性或线程安全。调用方必须依据公开契约，而不是某个 JDK 当前实现。',
        example: '`String[] a = {"A", "B"}; var fixed = Arrays.asList(a); fixed.set(0, "X")` 会让 `a[0]` 变为 X，但 `fixed.add("C")` 失败。需要可变副本时写 `new ArrayList<>(Arrays.asList(a))`；需要不可修改快照且确认没有 null 时用 `List.copyOf(source)`。对于 `int[]`，应使用 IntStream.boxed 或显式循环，不能期待 Arrays.asList 自动装箱每个元素。',
        followUps: [
          { question: 'Collectors.toList 一定返回 ArrayList 吗？', answer: '不一定，规范没有保证具体实现或可修改性；若结果能力重要，应改用明确的集合供应器或 toCollection。' },
          { question: 'Stream.toList 与 List.of 对 null 的约束相同吗？', answer: '不同，List.of 明确拒绝 null，而 Stream.toList 的结果可以包含流中出现的 null 元素。' },
        ],
        pitfalls: ['看到 add 失败就把三种列表笼统称为同一种不可变集合。', '对基本类型数组调用 Arrays.asList，误以为会逐元素装箱。'],
        sources: [OFFICIAL.list, OFFICIAL.stream, OFFICIAL.collectors],
      },
      {
        title: 'EnumSet 与 EnumMap 为什么适合枚举域，而不是普通集合的语法糖？',
        summary: '当元素或键来自单一枚举类型时，EnumSet 与 EnumMap 能直接表达封闭值域，并按枚举声明顺序迭代，通常比通用散列结构更紧凑、更可预测。',
        mechanism: '枚举常量在一个 enum 类型中拥有稳定的声明次序和有限全集。EnumSet 只接受同一枚举类型的非 null 常量，可用位向量一类紧凑表示支持 allOf、noneOf、range、complementOf 等集合运算；EnumMap 也限定键为单一枚举类型，键不允许 null，并按枚举常量的自然声明顺序迭代。它们的优势来自受限键域，而不是改变 Set 或 Map 的业务契约。value 是否允许 null 仍应看 EnumMap 契约；并发修改、复合操作原子性也不会因为使用枚举专用实现而自动获得。',
        example: '权限开关可写 `EnumSet.of(READ, WRITE)`，要取“除 DELETE 外所有权限”可先 `EnumSet.complementOf(EnumSet.of(DELETE))`。状态对应处理器可写 `EnumMap<OrderState, Handler>`，评审时一眼能看出键域是 OrderState；若必须检查每个状态均已配置，再与 `EnumSet.allOf(OrderState.class)` 对照，而不是依赖 Map 大小口诀。',
        followUps: [
          { question: 'EnumSet 的迭代顺序由什么决定？', answer: '由枚举常量在类型中的声明顺序决定，不受元素加入顺序影响，因此可以稳定表达枚举域顺序。' },
          { question: '枚举专用集合是否自动线程安全？', answer: '不会。它们仍需遵守普通集合的并发使用规则，跨线程写入要外部同步或采用不可变快照。' },
        ],
        pitfalls: ['键明明是封闭枚举域，却用字符串 Map 丢失类型检查。', '误把紧凑实现理解成并发安全或复合操作自动原子化。'],
        sources: [OFFICIAL.set, OFFICIAL.map, OFFICIAL.collections],
      },
    ],
  },
  {
    title: 'Lambda、Stream、Optional 与 java.time',
    questions: [
      {
        title: 'Lambda 为什么只能捕获 final 或 effectively final 的局部变量？',
        summary: 'Lambda 可以读取没有再次赋值的局部变量，但不能修改它；这个限制让捕获值具有清晰稳定的语义，并避免把栈上局部变量误当成可共享可变存储。',
        mechanism: 'Lambda 表达式在目标类型上下文中产生函数式接口实例。它可以引用实例字段、静态字段以及 final 或 effectively final 的局部变量；后者指变量初始化后从未被重新赋值，即使没有显式 final。局部变量的生命周期通常短于返回后的 Lambda，实现可捕获其值而不是暴露原栈槽，因此禁止后续重新赋值可避免两套状态含义。实例字段通过捕获 this 访问，不受 effectively final 规则限制，但这也意味着异步 Lambda 可能读取并修改共享对象状态，线程安全仍需另行保证。循环变量是否可捕获取决于它是否是每轮新声明且未再赋值。',
        example: '`int limit = 10; Predicate<String> p = s -> s.length() > limit;` 合法；若随后执行 `limit++`，编译器会拒绝捕获。要统计流中元素，不能用单元素数组绕过限制并在并行流里递增；顺序代码可用 collect 得到结果，并发计数则根据语义选择 LongAdder、原子变量或无副作用归约。',
        followUps: [
          { question: '为什么可以在 Lambda 中修改对象字段，却不能给局部变量重新赋值？', answer: '捕获的局部变量值本身必须稳定；对象引用稳定不代表对象不可变，字段属于共享堆对象，修改合法但需要调用方承担并发风险。' },
          { question: 'Lambda 中的 this 指向 Lambda 对象吗？', answer: '不指向独立 Lambda 实例，它保留外围词法作用域的 this 语义，这一点与匿名内部类的 this 行为不同。' },
        ],
        pitfalls: ['用数组或可变容器绕过捕获限制，再把同一 Lambda 放进并行执行。', '看到 effectively final 就误以为所引用对象的内部状态也不可变。'],
        sources: [OFFICIAL.function, OFFICIAL.jlsExpressions],
      },
      {
        title: '函数式接口如何确定，为什么还需要基本类型专用接口？',
        summary: '函数式接口只需有一个抽象方法契约，默认方法不计入；IntFunction、ToLongFunction 等专用接口则用于减少装箱拆箱并把输入输出意图表达得更清楚。',
        mechanism: '一个接口若其抽象成员可归并为一个函数描述符，就能作为 Lambda 或方法引用的目标类型，@FunctionalInterface 让编译器帮助维护该约束，但不是成为函数式接口的必要条件。继承自 Object 的公共方法不会简单计入多个函数描述符，default 与 static 方法也不属于抽象函数。java.util.function 提供 Function、Predicate、Consumer、Supplier 以及 Bi 系列；IntPredicate、LongConsumer、ToIntFunction 等基本类型专用形式避免在高频流水线中把原始值反复装箱成包装对象。UnaryOperator 和 BinaryOperator 则表达输入输出为同一类型的特殊 Function。',
        example: '校验订单可声明 `Predicate<Order>`，把订单映射为展示对象用 `Function<Order, View>`，只读取配置用 `Supplier<Config>`。对百万个 int 求值时优先 `IntUnaryOperator` 或 `IntStream`，避免 `Function<Integer, Integer>` 为每个值产生潜在装箱成本。自定义回调加上 @FunctionalInterface，可在未来误增第二个抽象方法时立即编译失败。',
        followUps: [
          { question: '函数式接口能不能包含多个 default 方法？', answer: '可以，函数式接口的限制针对抽象函数描述符，default、static 以及可归并的方法不妨碍它作为 Lambda 目标。' },
          { question: '什么时候不值得为装箱专门优化？', answer: '低频控制流或对象操作中，应优先接口可读性；只有数据量、采样或性能测试表明装箱成为成本时再做针对性选择。' },
        ],
        pitfalls: ['把“接口只能有一个方法”当作函数式接口的准确规则。', '所有数值流水线都使用包装类型 Function，忽略可观的装箱成本。'],
        sources: [OFFICIAL.function, OFFICIAL.jlsInterfaces],
      },
      {
        title: '方法引用只是 Lambda 缩写吗，重载时如何确定目标方法？',
        summary: '方法引用与 Lambda 都依赖目标函数式接口进行类型检查，但方法引用的接收者位置、参数适配和重载解析可能更隐含；不清晰时显式 Lambda 往往更易读。',
        mechanism: '静态方法引用 `Type::staticMethod` 把函数参数传给静态方法；绑定实例引用 `instance::method` 已固定接收者；未绑定实例引用 `Type::instanceMethod` 会把函数描述符的第一个参数当接收者；构造器引用则产生对象或数组。编译器结合赋值、实参或返回位置给出的目标函数式接口，推导参数类型后选择适用重载。因此同一个 `String::valueOf` 在不同目标类型下可解析到不同重载，也可能因信息不足而二义。方法引用不会忽略受检异常：目标函数式接口的方法若未声明兼容异常，引用的方法也不能直接抛出它。',
        example: '`Function<String, String> trim = String::trim` 属于未绑定实例引用，调用时第一个 String 既是接收者；`Supplier<String> empty = String::new` 是无参构造器引用。若 `service::load` 有多个重载导致编译信息难懂，可改写为 `(UserId id) -> service.load(id)`，显式给出参数类型并在 Lambda 内完成异常转换。',
        followUps: [
          { question: 'Type::instanceMethod 的第一个参数为何会消失？', answer: '它并未消失，而是被用作调用该实例方法的接收者，剩余函数参数才对应实例方法自己的形参。' },
          { question: '方法引用一定比 Lambda 更好吗？', answer: '不一定。只有接收者和参数映射直观时才更简洁；重载、异常适配或多步逻辑下，显式 Lambda 更能表达意图。' },
        ],
        pitfalls: ['忽略目标类型对重载解析的决定作用，只看方法名猜签名。', '为了形式简短强行使用方法引用，掩盖接收者和参数的真实映射。'],
        sources: [OFFICIAL.jlsExpressions, OFFICIAL.function],
      },
      {
        title: 'Stream 为什么是惰性的、一次性的，副作用又为何危险？',
        summary: '中间操作只描述流水线，终止操作才触发遍历；Stream 一旦被消费就不能复用，而依赖外部可变状态会破坏优化、并行与结果可预测性。',
        mechanism: 'filter、map、sorted 等中间操作返回新流并延迟执行，count、collect、forEach 等终止操作消费流水线。实现可融合操作、短路或省略不影响结果的阶段，所以不能把 peek 当成一定执行的业务回调。流与数据源不同，它通常只遍历一次，终止或显式 close 后再次操作会抛 IllegalStateException。函数参数应尽量 non-interfering 且 stateless：遍历过程中修改数据源或依赖共享可变状态，顺序流也可能产生并发修改或时序耦合，并行流更会出现竞态。需要资源的流还必须关闭。',
        example: '不要写 `orders.stream().peek(audit::save).count()` 来保证每笔审计落库，因为流水线优化与终止操作语义不应承担业务副作用。可先 `var accepted = orders.stream().filter(rule).toList()`，再用明确循环执行事务性保存。调试 peek 只用于观察，不作为正确性条件；同一个 Stream 若要执行两种统计，应重新从集合创建流或一次 collect 完成。',
        followUps: [
          { question: '调用 stream() 时数据已经遍历了吗？', answer: '通常没有，stream() 建立遍历源，中间操作继续描述流水线，直到终止操作请求结果才实际拉取元素。' },
          { question: '为什么同一个 Stream 不能执行两个终止操作？', answer: '终止操作已经消费并关闭该流水线状态；Stream 不是可重复读取的集合，需要从数据源重新创建或合并计算。' },
        ],
        pitfalls: ['把 peek 当作可靠的保存、计费或发送消息钩子。', '缓存 Stream 实例并跨方法、跨线程或多次终止消费。'],
        sources: [OFFICIAL.stream, OFFICIAL.spliterator],
      },
      {
        title: 'map 与 flatMap 的区别如何从“层级”理解？',
        summary: 'map 对每个元素做一对一变换并保留结果层级，flatMap 则让每个元素产生一个流再把这些流展平，适合一对多关系和组合可选上下文。',
        mechanism: 'Stream.map 接收 Function<T,R>，一个输入产生一个 R，因此把 `Stream<Order>` 映射为订单的行列表会得到 `Stream<List<Line>>`。flatMap 接收从元素到 Stream 的函数，随后把所有子流的元素串接成当前流，得到 `Stream<Line>`；映射函数返回 null 会被当作空流，但显式 Stream.empty 更清楚。flatMap 的展平只处理一层，且生成的子流在内容并入后会被关闭。Optional.map 在映射函数返回 null 时得到 empty，Optional.flatMap 则要求函数直接返回 Optional，用于避免 `Optional<Optional<T>>`。',
        example: '统计所有订单行可写 `orders.stream().flatMap(o -> o.lines().stream()).filter(Line::billable).toList()`；若用 map，后续面对的是一组列表。查找用户再查邮箱时，`findUser(id).flatMap(User::verifiedEmail)` 直接得到 `Optional<Email>`，而 map 会多包一层。若每个输入恰好产生一个输出，就保留 map，让基数关系更明确。',
        followUps: [
          { question: 'flatMap 会自动递归展平任意层吗？', answer: '不会，它只按当前操作展平一层；更深嵌套需要再次 flatMap，或先调整不必要的数据结构。' },
          { question: '过滤空子集合应该在 flatMap 前还是后？', answer: '空集合的 stream 本身不产生元素，通常无需额外过滤；若子集合可能为 null，应先修正模型或显式转为空流。' },
        ],
        pitfalls: ['把所有映射都写成 flatMap，掩盖原本的一对一关系。', '用 null 表示没有子流，增加读者对特殊行为的依赖。'],
        sources: [OFFICIAL.stream, OFFICIAL.optional],
      },
      {
        title: 'reduce 与 collect 为什么不能互相随便替换？',
        summary: 'reduce 适合把不可变值按结合运算归约，collect 适合把元素累积到可变结果容器；并行正确性取决于 identity、accumulator 与 combiner 满足契约。',
        mechanism: 'reduce 的 identity 必须对运算保持单位元性质，accumulator 与 combiner 需要兼容且运算应具有结合性，才能在不同分组方式下得到相同结果；浮点加法等并非严格结合，因此并行分组可能有细微差异。collect 的 Supplier 为每个分区提供独立可变容器，accumulator 将元素加入容器，combiner 合并分区结果，适合列表、Map 或统计汇总。不要在 reduce 中反复复制可变 List，也不要让多个并行分区共享同一个 mutable identity。Collectors 的特征只在真实满足无序、并发等条件时才能声明。',
        example: '金额总和可用 `amounts.stream().reduce(BigDecimal.ZERO, BigDecimal::add)`；收集用户编号用 `collect(Collectors.toSet())`。错误示例是 `reduce(new ArrayList<>(), (a,e) -> { a.add(e); return a; }, ...)`，并行时 identity 与变异关系不满足预期。需要自定义汇总时，为每个分区 new 独立 Accumulator，再实现清晰的 merge。',
        followUps: [
          { question: '为什么字符串拼接可 reduce，列表收集更适合 collect？', answer: '字符串是不可变值，拼接能按值归约；列表是可变容器，collect 专门定义了创建、累积与合并各分区容器的协议。' },
          { question: '并行 reduce 结果错误最先检查什么？', answer: '先检查 identity 是否真是单位元、运算是否结合、combiner 是否与 accumulator 兼容，以及函数是否读写了共享状态。' },
        ],
        pitfalls: ['在 reduce 中复用并修改同一个可变 identity。', '只在顺序流测试通过，就假设 accumulator 可安全用于并行分区。'],
        sources: [OFFICIAL.stream, OFFICIAL.collectors],
      },
      {
        title: '并行 Stream 何时可能更慢，顺序与线程安全如何判断？',
        summary: 'parallel 并不是免费加速：拆分、调度、合并和共享资源争用都有成本；是否保序、是否并发累积则由数据源、操作和 Collector 契约共同决定。',
        mechanism: '并行流利用 Spliterator 拆分数据；JDK 21 默认实现通常通过 `ForkJoinPool.commonPool()` 处理分区任务，但 Java SE 的 Stream 接口并未把具体执行器写成跨实现保证。规则计算足够重、数据量大、来源易均衡拆分且合并便宜时才可能获益；链表、I/O、锁竞争、很小的数据集或昂贵的顺序合并会抵消收益。流的 encounter order 来自有序数据源和操作，forEach 不保证并行输出顺序，forEachOrdered 保序但可能降低并行度。线程安全容器也不能自动让整条复合逻辑正确，非干扰与无状态仍是基本要求；共享执行资源还可能与应用其他任务相互影响，必须通过目标运行时基准验证。',
        example: '对百万个独立图像做纯 CPU 特征计算，可以用代表性数据比较 sequential 与 parallel；而“并行读取数据库再写同一个 ArrayList”既受连接池限制又有竞态。若只是把 500 个订单金额求和，调度成本可能高于计算。需要稳定输出时用 collect 保持有序结果，而不是给共享列表加锁后在 forEach 中追加。',
        followUps: [
          { question: 'forEachOrdered 是否仍然并行执行所有上游操作？', answer: '它要求按遭遇顺序产生终端效果，会限制部分并行收益；具体调度由实现决定，不能把它理解为完全顺序或免费保序。' },
          { question: 'ConcurrentHashMap 能否让任意并行流副作用都安全？', answer: '不能，它只能保证自身规定的操作；跨多个键、外部对象或检查后执行的业务不变量仍需原子设计。' },
        ],
        pitfalls: ['看到 CPU 多核就无基准地把所有 stream 改成 parallel。', '并行 forEach 写共享容器，并把容器单次操作安全等同于整体逻辑正确。'],
        sources: [OFFICIAL.stream, OFFICIAL.spliterator, OFFICIAL.collectors],
      },
      {
        title: 'Optional 适合表达什么，不适合出现在哪里？',
        summary: 'Optional 最适合方法返回值明确表达“可能没有一个结果”，并通过 map、flatMap、orElseGet 组合处理；它不应成为所有字段、参数和集合元素的通用包装。',
        mechanism: 'Optional 是可能包含一个非 null 值的容器，empty 表示缺失。of 要求非 null，ofNullable 接受 null；map 在有值时映射且将 null 结果变为空，flatMap 用于映射函数已经返回 Optional。orElse 的参数会在调用前求值，即使当前有值也可能执行昂贵查询；orElseGet 仅在缺失时调用 Supplier。Optional 本身是 value-based 类，不应依赖对象身份或拿来加锁。API 设计上，返回 Optional 能迫使调用者面对缺失，但参数、实体字段、集合元素通常可以通过重载、领域状态或空集合表达得更直接。',
        example: '缓存查询可写 `findLocal(id).or(() -> findRemote(id)).orElseThrow(...)`；默认值需要访问数据库时用 `orElseGet(() -> repository.loadDefault())`，避免命中本地结果仍执行查询。返回多项时优先空 List 而不是 `Optional<List<T>>`。持久化实体字段若必须区分“未加载”和“明确为空”，应建立领域类型，不能只靠 Optional 猜状态。',
        followUps: [
          { question: 'orElse 与 orElseGet 的差异只在语法吗？', answer: '不是，orElse 的候选值在方法调用前已经求值；orElseGet 的 Supplier 仅在 Optional 为空时执行。' },
          { question: '为什么不推荐直接 get？', answer: 'get 把缺失转成无上下文的 NoSuchElementException；orElseThrow、组合操作或显式分支更能表达业务处理策略。' },
        ],
        pitfalls: ['在有值概率很高时用 orElse 执行昂贵或有副作用的默认逻辑。', '用 Optional 包装集合、参数和实体每个字段，反而模糊领域状态。'],
        sources: [OFFICIAL.optional],
      },
      {
        title: 'Instant、LocalDateTime 与 ZonedDateTime 应该如何按业务语义选择？',
        summary: 'Instant 表示时间线上的唯一时刻，LocalDateTime 只有墙上日期和时间而没有时区，ZonedDateTime 同时携带时区规则；存储和展示必须先弄清业务需要哪一种。',
        mechanism: 'Instant 以 UTC 时间线上的秒和纳秒定位时刻，适合事件时间戳、跨系统排序和机器交换。LocalDate、LocalTime、LocalDateTime 是不含偏移与时区的本地值，单独一个 LocalDateTime 在夏令时切换区可能对应两个时刻或根本不存在。OffsetDateTime 携带固定偏移，但偏移本身不包含地区未来规则；ZonedDateTime 绑定 ZoneId 与时区规则，适合“巴黎每天九点开会”这类地区语义。Duration 基于秒和纳秒度量时间线长度，Period 按年、月、日表达日历差异，两者跨夏令时的结果可能不同。',
        example: '日志与数据库审计字段可保存 Instant，并在展示时执行 `instant.atZone(userZone)`；生日只需 LocalDate；航班当地起飞时间要同时保存地区 ZoneId，而不只是 `+08:00`。纽约夏令时切换日，“加 24 小时”和“加 1 天”可能落在不同本地时钟时间，排班逻辑应明确使用 Duration 还是 Period。',
        followUps: [
          { question: '固定的 UTC offset 为什么不能完全替代 ZoneId？', answer: 'offset 只描述当下与 UTC 的差值，不包含地区历史和未来的夏令时规则，长期日程需要 ZoneId 重新解析规则。' },
          { question: 'LocalDateTime 能否直接代表数据库创建时间？', answer: '只有系统明确约定统一时区且绝不混用时才勉强可行；跨区域审计通常应存 Instant，并在边界转换显示。' },
        ],
        pitfalls: ['把没有时区的 LocalDateTime 当成全球唯一事件时刻传输。', '用固定偏移表示长期地区日程，忽略夏令时与规则调整。'],
        sources: [OFFICIAL.time],
      },
      {
        title: '日期格式化、解析和夏令时边界怎样避免“看起来正确”？',
        summary: 'DateTimeFormatter 是不可变且线程安全的，但模式字母、Locale、解析严格度和 ZoneId 都必须显式；边界时间还要决定重叠与空洞时采用什么业务策略。',
        mechanism: 'DateTimeFormatter 可复用并组合 pattern、Locale、DecimalStyle、ResolverStyle 与 ZoneId。模式中的 `uuuu` 表示纪年年份，`yyyy` 是纪元内年份；`MM` 是月份而 `mm` 是分钟，误用会产生隐蔽结果。STRICT 解析会拒绝无效日期，SMART 可能进行有限调整。把 LocalDateTime 绑定地区时区时，夏令时前跳会形成不存在的本地时间，回拨会形成两个有效偏移；ZonedDateTime 的默认解析有既定规则，但业务若涉及计费、调度或法规，必须检测有效偏移数量并明确选择、拒绝或提示用户。',
        example: '接口日期可固定 `DateTimeFormatter.ofPattern("uuuu-MM-dd").withResolverStyle(STRICT)`，并用明确 Locale 解析英文月份。用户输入 `2026-03-08 02:30 America/New_York` 时，该本地时间可能处于春季跳时空洞；预约系统不应静默当作普通时刻，而应校验 zone rules 后提示选择有效时间。格式化事件前先把 Instant 转入用户 ZoneId。',
        followUps: [
          { question: 'SimpleDateFormat 与 DateTimeFormatter 的并发差异是什么？', answer: 'DateTimeFormatter 是不可变且线程安全的，可作为常量复用；旧的 SimpleDateFormat 是可变对象，不应无保护跨线程共享。' },
          { question: '为什么日期模式更推荐 uuuu 而非 yyyy？', answer: 'uuuu 直接表示 proleptic year，与严格解析和无纪元日期更一致；yyyy 是 year-of-era，严格解析时还涉及纪元信息。' },
        ],
        pitfalls: ['把 MM 与 mm、uuuu 与 yyyy 混用后只用普通日期样例测试。', '解析本地时间时未指定地区时区，也未处理夏令时空洞和重叠。'],
        sources: [OFFICIAL.time],
      },
    ],
  },
  {
    title: 'IO、NIO、编码、文件与序列化',
    questions: [
      {
        title: '字节流与字符流怎样分层，Buffered 就一定更快吗？',
        summary: 'InputStream、OutputStream 处理原始字节，Reader、Writer 通过字符集处理字符；缓冲能减少小粒度底层调用，但缓冲层数量、刷新时机和真实访问模式仍需设计。',
        mechanism: '二进制图片、压缩包和协议帧应保持字节语义；文本必须在边界由 CharsetDecoder 或 Reader 把字节解释为字符，再由 Writer 编码回字节。InputStreamReader 与 OutputStreamWriter 是两套层级的桥接器。BufferedInputStream、BufferedReader 等通过内存块合并小读写，通常能减少系统调用，但若底层 API 已有缓冲或应用一次读大块，重复包装只增加复制和状态复杂度。Writer 的 flush 只把 Java 侧缓冲推进下层，不等于磁盘持久化或网络对端已经处理；close 通常会先刷新，但错误处理仍要保留最初异常。',
        example: '读取 UTF-8 配置可写 `Files.newBufferedReader(path, StandardCharsets.UTF_8)`；复制图片则用 InputStream/OutputStream 或 `Files.copy`，不能经 Reader 中转。日志逐字符写入性能差，可批量缓冲，但每行 flush 会抵消收益。若要求落盘耐久，还需 FileChannel.force 等明确机制，不能把 `writer.flush()` 当作断电安全承诺。',
        followUps: [
          { question: 'Reader 读到的是 Unicode 码点吗？', answer: 'Reader 的基本单位是 UTF-16 char；补充字符可能由一对代理项表示，按码点处理还需 Character 相关 API。' },
          { question: '为什么不能用字符流复制任意二进制文件？', answer: '解码和再编码会把任意字节解释成字符，非法序列可能被替换，合法序列也未必可逆，最终破坏原始字节。' },
        ],
        pitfalls: ['用平台默认字符集读取协议或配置，部署后结果随环境变化。', '把 flush 等同于设备持久化或远端业务已确认接收。'],
        sources: [OFFICIAL.io, OFFICIAL.files],
      },
      {
        title: '字符集、编码和乱码的根因怎样系统定位？',
        summary: '字符串是字符序列，文件和网络上传输的是字节；乱码通常来自编码端与解码端字符集不一致、错误的二次转码，或对非法字节采用了不合适的替换策略。',
        mechanism: 'CharsetEncoder 把字符编码为字节，CharsetDecoder 把字节解码为字符。同一字节在不同字符集中可映射为不同字符，某些字节序列在指定字符集中还可能 malformed；目标字符集无法表示某字符时则属于 unmappable。许多便捷构造器使用默认字符集，默认值会随运行环境配置而变化，因此持久格式和协议必须显式指定 Charset。错误处理可选择 REPORT、REPLACE 或 IGNORE：关键数据导入通常应 REPORT 并记录偏移，静默替换会让数据看似成功却已损坏。已经乱码的 String 再反复 getBytes/new String 通常无法恢复丢失信息。',
        example: '接收 CSV 时先保留原始字节，依据协议或 BOM 选择 UTF-8，再以配置为 REPORT 的 CharsetDecoder 解码；失败时记录文件名与字节位置并拒绝导入。不要写 `new String(text.getBytes("ISO-8859-1"), "UTF-8")` 当万能修复，它只在非常特定的错误链可逆时碰巧有效。HTTP、数据库连接和文件读写三端都要核对真实字节与声明。',
        followUps: [
          { question: 'UTF-8 文件是否一定需要 BOM？', answer: '不一定，UTF-8 并不依赖 BOM；是否接受或生成 BOM 要依据具体协议，不能把它当成通用编码检测器。' },
          { question: '出现替换字符后还能完全还原原文吗？', answer: '通常不能，多个非法输入可能都被替换为同一字符，信息已经丢失；应回到原始字节和正确字符集重新解码。' },
        ],
        pitfalls: ['依赖 `Charset.defaultCharset()` 处理跨机器持久数据。', '发生乱码后多轮猜测式转码，覆盖了还能用于诊断的原始字节。'],
        sources: [OFFICIAL.nio, OFFICIAL.io],
      },
      {
        title: 'InputStream.read 为什么返回 int，怎样正确处理 EOF 与无符号字节？',
        summary: '单字节 `read()` 需要同时表达 0 到 255 的全部字节值和额外的 EOF 状态，因此返回 int：非负值是无符号字节，-1 才表示流结束。',
        mechanism: 'Java 的 byte 取值范围是 -128 到 127，无法再腾出一个值同时无歧义表示 256 种字节模式与 EOF。`InputStream.read()` 因而返回 int：读取成功时结果限定在 0 到 255，流结束且没有更多字节时返回 -1。调用方必须先判断 -1，再转换或参与位运算；直接强转 byte 会把 128 到 255 表现为负数，并且把 -1 强转后得到的 `0xFF` 与真实字节 255 无法区分。批量 `read(byte[])` 返回本次字节数，EOF 返回 -1；数组长度为零时可返回 0，普通阻塞 InputStream 代码不能把“读到的内容恰好为 0”与返回值 0 混淆。读取固定长度数据还必须循环，因为一次批量 read 不承诺填满数组。',
        example: '正确单字节循环是 `for (int v; (v = in.read()) != -1;) { checksum.update(v); }`，此时 v 已是 0 到 255，无需再次 `& 0xff`。若已有一个 byte b，要恢复其无符号数值才写 `b & 0xff`。读取 16 字节头部时应累计 offset，直到收满、发生异常或 read 返回 -1；若中途 EOF，应报告截断，不能把数组剩余的默认零值当成文件内容。',
        followUps: [
          { question: '为什么 `(byte) in.read() == -1` 不能可靠判断 EOF？', answer: '真实字节 255 和 EOF 的 int -1 强转为 byte 后都表现为 -1，转换前不判断会丢失区分它们所需的信息。' },
          { question: '批量 read 返回的 n 应该怎样使用？', answer: '只处理缓冲区从零到 n 的本次有效区域并累计进度；不能假设数组每次被填满，也不能读取上次遗留的尾部。' },
        ],
        pitfalls: ['先把 read 返回值强转为 byte，再判断是否等于 -1。', '一次 read(byte[]) 后处理整个数组，忽略实际返回的有效字节数。'],
        sources: [OFFICIAL.io, OFFICIAL.jlsTypes, OFFICIAL.jlsConversions],
      },
      {
        title: 'Path 与 Files 操作怎样避免相对路径、符号链接和非原子替换风险？',
        summary: 'Path 是路径表达而不是文件本身；安全文件操作要明确基准目录、规范化与真实路径的差别，并对符号链接、竞态和原子移动能力做显式处理。',
        mechanism: 'Path.resolve 组合路径，normalize 只做语法层面的 `.`、`..` 消解，不访问文件系统；toRealPath 会解析真实存在路径及符号链接。上传文件若仅 normalize 后检查字符串前缀，攻击者仍可能借助符号链接或检查后替换制造逃逸。Files.move 的 ATOMIC_MOVE 只有文件系统支持时才提供原子移动，否则会抛 AtomicMoveNotSupportedException；指定它时其他复制选项会被忽略，目标已存在时究竟替换还是失败由具体实现决定。稳妥更新通常在同一文件系统写入并校验临时文件，再用版本文件、清单或明确的恢复协议完成切换，而不是假设 ATOMIC_MOVE 与 REPLACE_EXISTING 组合具有统一语义。',
        example: '配置发布可在目标目录用 `Files.createTempFile(dir, ".config-", ".tmp")` 写完并校验，再把它以唯一版本名执行 `Files.move(tmp, versioned, ATOMIC_MOVE)`；最后按应用约定切换清单并保留旧版本。若必须覆盖固定目标，应先确认文件系统提供者语义并测试失败恢复。用户文件名则使用服务端生成 ID，避免直接 resolve 不可信路径。',
        followUps: [
          { question: 'normalize 与 toRealPath 的本质差异是什么？', answer: 'normalize 仅重写路径字符串，不要求目标存在；toRealPath 访问文件系统并解析实际路径及符号链接。' },
          { question: 'ATOMIC_MOVE 失败后直接普通 move 可以吗？', answer: '要看业务是否容忍中间状态；关键配置或索引需要备份、校验和恢复流程，不能无条件静默降级。' },
        ],
        pitfalls: ['只用字符串 startsWith 校验路径，忽略符号链接与检查后使用竞态。', '假设所有文件系统和容器挂载都支持同样的原子移动语义。'],
        sources: [OFFICIAL.files],
      },
      {
        title: 'Files.lines 与 Files.walk 为什么必须关注关闭和惰性遍历？',
        summary: '这类方法返回按需读取目录或文件的 Stream，底层可能持有打开的文件或目录句柄；终止操作完成不应取代显式 try-with-resources 生命周期。',
        mechanism: 'Files.lines 返回文本行的惰性 Stream，Files.list 和 Files.walk 也可能在遍历期间持有一个或多个打开目录。它们实现 AutoCloseable 的 Stream 关闭钩子，因此应放在 try-with-resources 中；把 Stream 返回到已离开资源作用域的调用方，或长期缓存它，都会让资源边界模糊。walk 会按深度优先遍历并可选择 FOLLOW_LINKS；跟随链接时必须考虑循环和越界。惰性还意味着异常可能不在创建流时发生，而是在终止操作拉取后续元素时以包装的未检查 I/O 异常出现。大目录上直接 toList 会把全部 Path 驻留内存。',
        example: '`try (var lines = Files.lines(path, UTF_8)) { return lines.filter(this::valid).limit(1000).toList(); }` 在方法内完成消费并关闭文件。扫描上传目录时使用 `try (var paths = Files.walk(root, maxDepth))`，默认不跟随符号链接，并边遍历边处理；不要返回 paths 给控制器以后再消费，也不要为找前十个文件先把整棵目录树收集进 List。',
        followUps: [
          { question: '调用 count 后 Stream 是否会自动替代 close？', answer: '不能把终止操作当作通用资源关闭保证；官方建议对持有 I/O 资源的 Stream 使用 try-with-resources 显式关闭。' },
          { question: '遍历时的 IOException 为什么可能变成未检查异常？', answer: '惰性 Stream 的函数接口不便直接声明 IOException，后续访问失败可能包装为 UncheckedIOException 再从终止操作传播。' },
        ],
        pitfalls: ['从方法返回仍绑定文件句柄的 Stream，让调用者难以正确关闭。', '对巨大目录先 walk().toList()，造成句柄时间过长和内存峰值。'],
        sources: [OFFICIAL.files, OFFICIAL.stream],
      },
      {
        title: 'ByteBuffer 的 position、limit、capacity 如何配合 flip、clear 与 compact？',
        summary: 'ByteBuffer 依靠 position 和 limit 划分当前可读写区间；flip 是从写模式切到读模式，clear 是准备覆盖整个缓冲区，compact 则保留未读数据后继续写。',
        mechanism: 'capacity 是缓冲区固定容量，position 指向下一个读或写位置，limit 表示当前不可越过的边界。新缓冲区通常 position 为零、limit 等于 capacity；写入后 position 前移，flip 把 limit 设为原 position 再把 position 归零，使刚写入部分可读。读完后 clear 仅重置索引，并不会擦除旧字节；若只消费部分数据，compact 会把未读字节移到开头，把 position 放到其后，便于继续从 Channel 追加。rewind 只把 position 归零以便重读当前 limit 内数据。mark/reset 受位置变化影响，不能用肉眼猜状态。',
        example: '处理半包协议时，channel.read(buffer) 后 flip，循环解析完整帧；发现末尾不足一帧就 compact，把残余字节搬到开头并等待下一次 read。若此时误用 clear，残余半帧会被新数据覆盖；若读取后忘记 compact 或 clear，limit 仍停在旧数据末端，后续 read 可能立即返回零。调试时记录 position、limit、capacity 比打印整块数组更有效。',
        followUps: [
          { question: 'clear 会把缓冲区内容填零吗？', answer: '不会，它只把 position 置零、limit 置为 capacity，并丢弃旧内容的逻辑可见性，底层字节可能仍在。' },
          { question: 'compact 与 rewind 分别用于什么场景？', answer: 'compact 保留未读数据并准备继续写；rewind 保持 limit 不变，只把 position 归零以重新读取已有数据。' },
        ],
        pitfalls: ['把 clear 当作安全擦除敏感数据的操作。', '网络半包尚未解析完就 clear，导致跨读取边界的数据丢失。'],
        sources: [OFFICIAL.nio, OFFICIAL.channels],
      },
      {
        title: 'Channel 的 read 和 write 为什么必须处理“部分完成”？',
        summary: 'Channel 方法返回本次实际传输数量，不保证一次读满缓冲区或一次写完全部内容；正确代码必须根据返回值、buffer 状态和 EOF 循环推进。',
        mechanism: 'ReadableByteChannel.read 最多读取 buffer.remaining 个字节，可能读到较少字节，流结束时返回 -1；非阻塞通道暂时无数据时还可返回 0。WritableByteChannel.write 同样只写当前可写部分的一部分，特别是套接字发送缓冲区受限时。FileChannel 的 position 读写和带显式位置的读写具有不同共享位置语义，transferTo/transferFrom 也不应假设一次覆盖请求总量。循环必须保证每轮有进展或等待就绪，避免返回 0 时忙等；协议层还需区分“流结束”“当前无数据”和“还缺一帧”。',
        example: '写文件或阻塞套接字时使用 `while (buffer.hasRemaining()) channel.write(buffer)`，并处理 write 异常；非阻塞 SocketChannel 若 write 返回 0，应注册 OP_WRITE，待 Selector 通知后继续，不能在 CPU 上自旋。读固定长度消息时累计返回值，read 为 -1 且仍未收齐应报告截断，而不是把缓冲区未写区域当作有效零字节。',
        followUps: [
          { question: '阻塞 Channel 的 write 是否一定写完整个 buffer？', answer: '不保证，阻塞只影响等待行为，write 的契约仍允许返回小于 remaining 的正数，调用者应循环到写完。' },
          { question: 'read 返回 0 与 -1 有什么区别？', answer: '0 表示本次没有传输数据但通道未必结束，-1 明确表示到达流末尾，协议处理不能混为一谈。' },
        ],
        pitfalls: ['一次 write 后直接复用缓冲区，丢掉尚未发送的尾部数据。', '非阻塞通道返回零时紧密循环，制造高 CPU 忙等。'],
        sources: [OFFICIAL.channels, OFFICIAL.nio],
      },
      {
        title: '阻塞 IO、非阻塞 Channel 与 Selector 的边界是什么？',
        summary: '非阻塞模式让线程在通道暂不可读写时立即返回，Selector 用就绪事件管理多个通道；它减少等待线程，不会自动简化协议状态机或让业务计算并行。',
        mechanism: 'SelectableChannel 配置为非阻塞后可向 Selector 注册感兴趣的操作。select 返回的是“某操作现在可能不阻塞”的就绪提示，而不是保证下一次调用一定传输完整消息；处理期间条件可能变化，仍需接受 read/write 返回零。每个连接必须保存解码进度、半包、待发送缓冲等状态，处理完 selectedKeys 后正确移除已消费键，并按待写数据动态维护 OP_WRITE，长期无条件关注可写事件会造成空轮询。Selector 线程适合做轻量 I/O 状态推进，耗时计算应交给受控执行器再安全地把结果唤醒回事件循环。',
        example: '聊天室可由一个 Selector 管理数千连接：OP_READ 到来后把字节追加到连接 ByteBuffer，解析出完整帧再提交业务；响应未写完就保留 buffer 并注册 OP_WRITE，写空后取消该兴趣。不要在 selector 线程里调用慢数据库，也不要每轮都保持 OP_WRITE，因为套接字通常持续可写，会让 select 频繁立即返回。',
        followUps: [
          { question: '就绪事件是否表示已经收到一个完整业务请求？', answer: '不是，它只说明底层 I/O 操作可能推进；完整请求仍需由应用协议处理拆包、粘包和解码状态。' },
          { question: '为什么 OP_WRITE 通常按需注册？', answer: '套接字在多数时间都可写，持续关注会不断产生就绪事件；只有存在未发送数据时注册才能避免空转。' },
        ],
        pitfalls: ['把 Selector 就绪误解为一次 read 就能得到完整消息。', '永久注册 OP_WRITE 或在事件线程执行慢业务，造成空转与全局延迟。'],
        sources: [OFFICIAL.channels, OFFICIAL.nio],
      },
      {
        title: 'Java 原生序列化中的 serialVersionUID、transient 与钩子方法各管什么？',
        summary: 'serialVersionUID 用于反序列化版本兼容检查，transient 排除默认字段数据，而 writeObject、readObject 等钩子可定制格式；三者都不能把不可信反序列化变安全。',
        mechanism: '实现 Serializable 只是标记对象可参与协议。若未显式声明 serialVersionUID，运行时会根据类结构计算默认值，普通重构可能改变它并导致 InvalidClassException；显式 UID 只允许版本检查通过，不会自动解决字段语义变化。static 字段属于类而非对象状态，默认不序列化；transient 实例字段也跳过默认序列化，反序列化后取得类型默认值，需由 readObject 恢复不变量。自定义 writeObject/readObject、readResolve/writeReplace 能控制表示和身份，但必须遵守调用顺序、校验长度与对象不变量。构造器执行规则也与普通 new 不同，不能依赖构造器完成全部验证。',
        example: '会话对象把临时缓存字段标成 transient，并在 `readObject` 中先 `defaultReadObject()`，再检查用户名非空、集合大小上限并重建缓存。升级类时显式保持或变更 serialVersionUID 要基于兼容策略，而不是为了“强行读取旧数据”始终写 1。密码不应因 transient 就安全，因为其他字段图和自定义钩子仍可能泄露数据。',
        followUps: [
          { question: 'serialVersionUID 相同是否保证新旧对象完全兼容？', answer: '不保证，它只是版本检查的一部分；字段类型、类层次、自定义钩子和业务不变量变化仍可能导致错误或静默语义偏差。' },
          { question: 'transient 字段反序列化后是什么值？', answer: '默认序列化不会恢复它，字段先得到 Java 类型默认值，若对象需要其他状态必须在安全钩子中重建。' },
        ],
        pitfalls: ['把固定 serialVersionUID 当作任意类演进都兼容的开关。', '依赖普通构造器校验反序列化对象，忽略协议的特殊构造过程。'],
        sources: [OFFICIAL.serialization, OFFICIAL.io],
      },
      {
        title: '为什么不应反序列化不可信 Java 对象流，替代方案如何选？',
        summary: '对象流会按输入重建复杂对象图并触发类中的反序列化行为，攻击面不只在目标 DTO；外部数据应优先使用受限结构格式、显式模式校验和最小类型集合。',
        mechanism: 'ObjectInputStream 读取的类型信息与对象图可能触发 readObject、readResolve、代理处理及可达类的其他行为，历史上的 gadget 链会把“仅解析数据”变成代码执行或资源耗尽入口。ObjectInputFilter 能按类、数组长度、深度、引用数与字节量进行过滤，是遗留系统的重要纵深防御，但过滤规则遗漏和类演进仍可能扩大攻击面，不能替代可信边界。新协议更适合 JSON、CBOR、Protocol Buffers 等显式 schema：只绑定预期 DTO，限制大小、深度和字段，拒绝任意类型名，并对语义不变量再次校验。签名或 TLS 能验证来源和传输，不会让来源本身的恶意对象图变安全。',
        example: '内部旧队列若暂时必须读取对象流，应限定入口身份，同时配置 ObjectInputFilter 只允许 `com.example.dto` 中的少数最终类、基础集合及严格深度和数组上限，拒绝代理与未知类，并在隔离环境做兼容测试。面向浏览器的新接口则改为带版本字段的 JSON DTO，关闭多态类型自动解析，对集合数量、字符串长度和金额范围逐项校验。',
        followUps: [
          { question: '只允许一个顶层 DTO 类就足够安全吗？', answer: '不够，DTO 的字段可达图还可能包含集合、代理或危险类型，必须限制整个对象图的类型、深度、数量与字节规模。' },
          { question: '数据有数字签名后能否放心原生反序列化？', answer: '签名只证明数据来自持钥者且未被篡改，不保证生产方未被攻陷、内容无逻辑攻击或解析过程没有资源风险。' },
        ],
        pitfalls: ['把网络内网或登录用户等同于输入绝对可信。', '配置过宽的类名前缀过滤，并误以为已经消除 gadget 与资源耗尽风险。'],
        sources: [OFFICIAL.serialization, OFFICIAL.io],
      },
    ],
  },
]
