export const OFFICIAL = {
  jlsTypes: { label: 'JLS 4：类型、值与变量', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-4.html', kind: 'official' },
  jlsConversions: { label: 'JLS 5：转换与上下文', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html', kind: 'official' },
  jlsClasses: { label: 'JLS 8：类', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-8.html', kind: 'official' },
  jlsInterfaces: { label: 'JLS 9：接口', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-9.html', kind: 'official' },
  jlsArrays: { label: 'JLS 10：数组', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-10.html', kind: 'official' },
  jlsExceptions: { label: 'JLS 11：异常', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-11.html', kind: 'official' },
  jlsExecution: { label: 'JLS 12：执行、加载与初始化', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-12.html', kind: 'official' },
  jlsBinary: { label: 'JLS 13：二进制兼容性', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-13.html', kind: 'official' },
  jlsStatements: { label: 'JLS 14：语句与控制流', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html', kind: 'official' },
  jlsExpressions: { label: 'JLS 15：表达式', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-15.html', kind: 'official' },
  jlsThreads: { label: 'JLS 17：线程与内存模型', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-17.html', kind: 'official' },
  jlsInference: { label: 'JLS 18：类型推断', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-18.html', kind: 'official' },
  jvmsRuntime: { label: 'JVMS 2：运行时数据区', url: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html', kind: 'official' },
  jvmsClassFile: { label: 'JVMS 4：Class 文件格式', url: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-4.html', kind: 'official' },
  object: { label: 'Java 21 Object API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Object.html', kind: 'official' },
  string: { label: 'Java 21 String API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/String.html', kind: 'official' },
  bigDecimal: { label: 'Java 21 BigDecimal API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/math/BigDecimal.html', kind: 'official' },
  autoCloseable: { label: 'Java 21 AutoCloseable API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/AutoCloseable.html', kind: 'official' },
  reflection: { label: 'Java 21 Reflection API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/reflect/package-summary.html', kind: 'official' },
  annotations: { label: 'Java 21 Annotation API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/annotation/package-summary.html', kind: 'official' },
  collections: { label: 'Java 21 Collections Framework', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/doc-files/coll-overview.html', kind: 'official' },
  collection: { label: 'Java 21 Collection API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Collection.html', kind: 'official' },
  list: { label: 'Java 21 List API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/List.html', kind: 'official' },
  set: { label: 'Java 21 Set API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Set.html', kind: 'official' },
  map: { label: 'Java 21 Map API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Map.html', kind: 'official' },
  deque: { label: 'Java 21 Deque API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Deque.html', kind: 'official' },
  priorityQueue: { label: 'Java 21 PriorityQueue API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/PriorityQueue.html', kind: 'official' },
  comparator: { label: 'Java 21 Comparator API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Comparator.html', kind: 'official' },
  spliterator: { label: 'Java 21 Spliterator API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Spliterator.html', kind: 'official' },
  function: { label: 'Java 21 函数式接口包', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/function/package-summary.html', kind: 'official' },
  stream: { label: 'Java 21 Stream API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/stream/Stream.html', kind: 'official' },
  collectors: { label: 'Java 21 Collectors API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/stream/Collectors.html', kind: 'official' },
  optional: { label: 'Java 21 Optional API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Optional.html', kind: 'official' },
  time: { label: 'Java 21 日期时间 API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/time/package-summary.html', kind: 'official' },
  io: { label: 'Java 21 java.io 包', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/io/package-summary.html', kind: 'official' },
  nio: { label: 'Java 21 java.nio 包', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/package-summary.html', kind: 'official' },
  files: { label: 'Java 21 Files API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/Files.html', kind: 'official' },
  channels: { label: 'Java 21 NIO Channels', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/channels/package-summary.html', kind: 'official' },
  serialization: { label: 'Java 对象序列化规范', url: 'https://docs.oracle.com/en/java/javase/21/docs/specs/serialization/', kind: 'official' },
  thread: { label: 'Java 21 Thread API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html', kind: 'official' },
  concurrent: { label: 'Java 21 并发工具包', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/package-summary.html', kind: 'official' },
  executor: { label: 'Java 21 ExecutorService API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ExecutorService.html', kind: 'official' },
  future: { label: 'Java 21 Future API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/Future.html', kind: 'official' },
  completableFuture: { label: 'Java 21 CompletableFuture API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/CompletableFuture.html', kind: 'official' },
  threadLocal: { label: 'Java 21 ThreadLocal API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ThreadLocal.html', kind: 'official' },
  locks: { label: 'Java 21 Locks API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/locks/package-summary.html', kind: 'official' },
  atomic: { label: 'Java 21 原子变量包', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/atomic/package-summary.html', kind: 'official' },
  gcTuning: { label: 'JDK 21 GC 调优指南', url: 'https://docs.oracle.com/en/java/javase/21/gctuning/', kind: 'official' },
  jcmd: { label: 'JDK 21 jcmd 工具说明', url: 'https://docs.oracle.com/en/java/javase/21/docs/specs/man/jcmd.html', kind: 'official' },
  nativeMemory: { label: 'JDK 21 Native Memory Tracking', url: 'https://docs.oracle.com/en/java/javase/21/vm/native-memory-tracking.html', kind: 'official' },
  hotspotPerformance: { label: 'JDK 21 HotSpot 性能增强', url: 'https://docs.oracle.com/en/java/javase/21/vm/java-hotspot-virtual-machine-performance-enhancements.html', kind: 'official' },
  references: { label: 'Java 21 引用对象 API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ref/package-summary.html', kind: 'official' },
  records: { label: 'JLS 8.10：Record 类', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-8.html#jls-8.10', kind: 'official' },
  sealed: { label: 'JLS 8.1.6：密封类', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-8.html#jls-8.1.6', kind: 'official' },
  switchExpressions: { label: 'JLS 15.28：switch 表达式', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-15.html#jls-15.28', kind: 'official' },
  patterns: { label: 'JLS 14.30：模式', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-14.30', kind: 'official' },
  modules: { label: 'Java 21 模块系统 API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/module/package-summary.html', kind: 'official' },
  virtualThreads: { label: 'JEP 444：Virtual Threads', url: 'https://openjdk.org/jeps/444', kind: 'official' },
}
