const COMMUNITY = {
  tencent: { label: '腾讯 Java 后端一面（牛客，2025-03-14）', url: 'https://www.nowcoder.com/discuss/730082976414846976', kind: 'community-interview' },
  kuaishou: { label: '快手 Java 后端一面（牛客，2025-03-19）', url: 'https://www.nowcoder.com/discuss/731843046232395776', kind: 'community-interview' },
  iflytek: { label: '科大讯飞 Java 后端一面（牛客，2025）', url: 'https://www.nowcoder.com/discuss/747230985057468416', kind: 'community-interview' },
  jdIntern: { label: '京东 Java 后端实习一面（牛客，2025-03-27）', url: 'https://www.nowcoder.com/discuss/734872934639996928', kind: 'community-interview' },
  baidu: { label: '百度 Java 后端提前批二面（牛客，2025-09-23）', url: 'https://www.nowcoder.com/discuss/799949823049756672', kind: 'community-interview' },
  jdDada: { label: '京东达达 Java 后端一面（牛客，2025-04-03）', url: 'https://www.nowcoder.com/discuss/737329814587117568', kind: 'community-interview' },
  digitalHorse: { label: '数字马力 Java 后端秋招面经（牛客，2025-12-04）', url: 'https://www.nowcoder.com/discuss/826171566831517696', kind: 'community-interview' },
  ctrip: { label: '携程 Java 后端一面（牛客，2025-03-20）', url: 'https://www.nowcoder.com/discuss/729706507876487168', kind: 'community-interview' },
  xhsDesign: { label: '小红书 Java 后端二面（牛客，2025-11-02）', url: 'https://www.nowcoder.com/discuss/814455404334776320', kind: 'community-interview' },
  xhsCore: { label: '小红书后端开发一面（牛客，2025-09-01）', url: 'https://www.nowcoder.com/discuss/792145962431946752', kind: 'community-interview' },
  byteLife: { label: '字节生活服务 Java 后端面经（牛客，2025-09-12）', url: 'https://www.nowcoder.com/discuss/796138629310455808', kind: 'community-interview' },
  meituan: { label: '美团 Java 后端一面（牛客，2025-04-08）', url: 'https://www.nowcoder.com/discuss/737336813836111872', kind: 'community-interview' },
  byteDoubao: { label: '字节豆包后端三轮面经（牛客，2025-03-19）', url: 'https://www.nowcoder.com/discuss/731895855627759616', kind: 'community-interview' },
  taotian: { label: '淘天业务技术后端面经（牛客，2024-04-21）', url: 'https://www.nowcoder.com/discuss/611696355077103616', kind: 'community-interview' },
  maimaiAlibaba: { label: '阿里 Java 后端面经（脉脉，2025-08-26）', url: 'https://maimai.cn/article/detail?efid=Ba1fhcvc38EuxMgVAWmZDg&fid=1885619951', kind: 'community-interview' },
  beanLifecycle: { label: 'Spring Bean 生命周期面试题（牛客，2025）', url: 'https://www.nowcoder.com/discuss/782649298138820608', kind: 'community-interview' },
  tencentShortLink: { label: '腾讯视频 Java 后端短链面经（牛客，2025-04-01）', url: 'https://www.nowcoder.com/discuss/742152164449017856', kind: 'community-interview' },
}

const CURATED = {
  javaCollection: { label: 'JavaGuide：Java 集合专题', url: 'https://javaguide.cn/java/collection/', kind: 'curated-guide' },
  javaConcurrent: { label: 'JavaGuide：Java 并发编程专题', url: 'https://javaguide.cn/java/concurrent/', kind: 'curated-guide' },
  javaJvm: { label: 'JavaGuide：JVM 专题', url: 'https://javaguide.cn/java/jvm/', kind: 'curated-guide' },
  spring: { label: 'JavaGuide：Spring 与 Spring Boot 专题', url: 'https://javaguide.cn/system-design/framework/spring/', kind: 'curated-guide' },
  springAuto: { label: 'JavaGuide：Spring Boot 自动装配原理', url: 'https://javaguide.cn/system-design/framework/spring/spring-boot-auto-assembly-principles.html', kind: 'curated-guide' },
  mysql: { label: 'JavaGuide：MySQL 专题', url: 'https://javaguide.cn/database/mysql/', kind: 'curated-guide' },
  redis: { label: 'JavaGuide：Redis 专题', url: 'https://javaguide.cn/database/redis/', kind: 'curated-guide' },
  messageQueue: { label: 'JavaGuide：消息队列专题', url: 'https://javaguide.cn/high-performance/message-queue/', kind: 'curated-guide' },
  distributed: { label: 'JavaGuide：分布式系统专题', url: 'https://javaguide.cn/distributed-system/', kind: 'curated-guide' },
  highPerformance: { label: 'JavaGuide：高性能系统专题', url: 'https://javaguide.cn/high-performance/', kind: 'curated-guide' },
  xiaolinMysql: { label: '小林 Coding：图解 MySQL', url: 'https://xiaolincoding.com/mysql/', kind: 'curated-guide' },
  xiaolinIndex: { label: '小林 Coding：为什么 MySQL 采用 B+ 树', url: 'https://xiaolincoding.com/mysql/index/why_index_chose_bpuls_tree.html', kind: 'curated-guide' },
  xiaolinMvcc: { label: '小林 Coding：事务隔离与 MVCC', url: 'https://xiaolincoding.com/mysql/transaction/mvcc.html', kind: 'curated-guide' },
  xiaolinLogs: { label: '小林 Coding：undo、redo 与 binlog', url: 'https://xiaolincoding.com/mysql/log/how_update.html', kind: 'curated-guide' },
  xiaolinRedis: { label: '小林 Coding：图解 Redis', url: 'https://xiaolincoding.com/redis/', kind: 'curated-guide' },
  xiaolinAof: { label: '小林 Coding：AOF 持久化', url: 'https://xiaolincoding.com/redis/storage/aof.html', kind: 'curated-guide' },
  xiaolinRedisInterview: { label: '小林 Coding：Redis 常见面试题', url: 'https://xiaolincoding.com/redis/base/redis_interview.html', kind: 'curated-guide' },
}

const OFFICIAL = {
  arrayList: { label: 'Java 21 ArrayList API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ArrayList.html', kind: 'official' },
  collections: { label: 'Java 21 Collections Framework', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/doc-files/coll-overview.html', kind: 'official' },
  hashMap: { label: 'Java 21 HashMap API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/HashMap.html', kind: 'official' },
  hashMapJdk8Source: { label: 'OpenJDK 8 HashMap 源码', url: 'https://github.com/openjdk/jdk8u/blob/master/jdk/src/share/classes/java/util/HashMap.java', kind: 'official' },
  concurrentHashMap: { label: 'Java 21 ConcurrentHashMap API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html', kind: 'official' },
  stringBuffer: { label: 'Java 21 StringBuffer API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/StringBuffer.html', kind: 'official' },
  jlsLoading: { label: 'JLS 12：执行与类加载', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-12.html', kind: 'official' },
  classLoader: { label: 'Java 21 ClassLoader.loadClass API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ClassLoader.html#loadClass(java.lang.String,boolean)', kind: 'official' },
  serviceLoader: { label: 'Java 21 ServiceLoader API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html', kind: 'official' },
  jlsThreads: { label: 'JLS 17：线程与内存模型', url: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-17.html', kind: 'official' },
  atomic: { label: 'Java 21 原子变量包说明', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/atomic/package-summary.html', kind: 'official' },
  aqs: { label: 'Java 21 AbstractQueuedSynchronizer API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/locks/AbstractQueuedSynchronizer.html', kind: 'official' },
  locks: { label: 'Java 21 Lock API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/locks/Lock.html', kind: 'official' },
  threadPool: { label: 'Java 21 ThreadPoolExecutor API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html', kind: 'official' },
  threadMx: { label: 'Java 21 ThreadMXBean API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.management/java/lang/management/ThreadMXBean.html', kind: 'official' },
  jvmsRuntime: { label: 'JVMS 2：运行时数据区', url: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html', kind: 'official' },
  gcTuning: { label: 'JDK 21 Garbage Collection Tuning Guide', url: 'https://docs.oracle.com/en/java/javase/21/gctuning/', kind: 'official' },
  jcmd: { label: 'JDK 21 jcmd 工具说明', url: 'https://docs.oracle.com/en/java/javase/21/docs/specs/man/jcmd.html', kind: 'official' },
  springLifecycle: { label: 'Spring Bean 生命周期回调', url: 'https://docs.spring.io/spring-framework/reference/core/beans/factory-nature.html', kind: 'official' },
  springAop: { label: 'Spring AOP 代理机制', url: 'https://docs.spring.io/spring-framework/reference/core/aop/proxying.html', kind: 'official' },
  springDeps: { label: 'Spring 依赖注入文档', url: 'https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html', kind: 'official' },
  springTx: { label: 'Spring 声明式事务注解', url: 'https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html', kind: 'official' },
  springBootAuto: { label: 'Spring Boot 自动配置官方文档', url: 'https://docs.spring.io/spring-boot/reference/using/auto-configuration.html', kind: 'official' },
  springMvc: { label: 'Spring MVC DispatcherServlet 官方文档', url: 'https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-servlet.html', kind: 'official' },
  springObservability: { label: 'Spring Boot 可观测性官方文档', url: 'https://docs.spring.io/spring-boot/reference/actuator/observability.html', kind: 'official' },
  dubbo: { label: 'Apache Dubbo 官方概览', url: 'https://dubbo.apache.org/en/overview/what/overview/', kind: 'official' },
  nacos: { label: 'Nacos 服务发现概览', url: 'https://nacos.io/en/docs/latest/manual/user/naming/overview/', kind: 'official' },
  nacosSubscription: { label: 'Nacos 订阅、推送与故障恢复', url: 'https://nacos.io/en/docs/latest/manual/user/naming/subscription-and-ops/', kind: 'official' },
  mysqlIndexes: { label: 'MySQL 8.4 InnoDB 索引类型', url: 'https://dev.mysql.com/doc/refman/8.4/en/innodb-index-types.html', kind: 'official' },
  mysqlOptimization: { label: 'MySQL 8.4 索引优化', url: 'https://dev.mysql.com/doc/refman/8.4/en/optimization-indexes.html', kind: 'official' },
  mysqlMvcc: { label: 'MySQL 8.4 InnoDB MVCC', url: 'https://dev.mysql.com/doc/refman/8.4/en/innodb-multi-versioning.html', kind: 'official' },
  mysqlLocks: { label: 'MySQL 8.4 InnoDB 锁', url: 'https://dev.mysql.com/doc/refman/8.4/en/innodb-locking.html', kind: 'official' },
  mysqlRedo: { label: 'MySQL 8.4 InnoDB Redo Log', url: 'https://dev.mysql.com/doc/refman/8.4/en/innodb-redo-log.html', kind: 'official' },
  mysqlUndo: { label: 'MySQL 8.4 InnoDB Undo Logs', url: 'https://dev.mysql.com/doc/refman/8.4/en/innodb-undo-logs.html', kind: 'official' },
  mysqlBinlog: { label: 'MySQL 8.4 Binary Log', url: 'https://dev.mysql.com/doc/refman/8.4/en/binary-log.html', kind: 'official' },
  mysqlExplain: { label: 'MySQL 8.4 EXPLAIN', url: 'https://dev.mysql.com/doc/refman/8.4/en/explain.html', kind: 'official' },
  mysqlPartitioning: { label: 'MySQL 8.4 分区限制', url: 'https://dev.mysql.com/doc/refman/8.4/en/partitioning-limitations.html', kind: 'official' },
  redisTypes: { label: 'Redis 官方数据类型', url: 'https://redis.io/docs/latest/develop/data-types/', kind: 'official' },
  redisPersistence: { label: 'Redis 官方持久化文档', url: 'https://redis.io/docs/latest/operate/oss_and_stack/management/persistence/', kind: 'official' },
  redisEviction: { label: 'Redis 官方淘汰策略', url: 'https://redis.io/docs/latest/develop/reference/eviction/', kind: 'official' },
  redisLock: { label: 'Redis 官方分布式锁模式', url: 'https://redis.io/docs/latest/develop/clients/patterns/distributed-locks/', kind: 'official' },
  redisTransactions: { label: 'Redis 官方事务文档', url: 'https://redis.io/docs/latest/develop/interact/transactions/', kind: 'official' },
  redisScale: { label: 'Redis Cluster 扩展文档', url: 'https://redis.io/docs/latest/operate/oss_and_stack/management/scaling/', kind: 'official' },
  redisLatency: { label: 'Redis 延迟诊断与事件循环说明', url: 'https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/latency/', kind: 'official' },
  kafkaDesign: { label: 'Apache Kafka 设计文档', url: 'https://kafka.apache.org/documentation/#design', kind: 'official' },
  kafkaSemantics: { label: 'Apache Kafka 消息语义', url: 'https://kafka.apache.org/documentation/#semantics', kind: 'official' },
  kafkaConsumer: { label: 'Apache Kafka Consumer 配置', url: 'https://kafka.apache.org/documentation/#consumerconfigs', kind: 'official' },
  rocketOrder: { label: 'RocketMQ 顺序消息', url: 'https://rocketmq.apache.org/docs/featureBehavior/03fifomessage/', kind: 'official' },
  rocketTx: { label: 'RocketMQ 事务消息', url: 'https://rocketmq.apache.org/docs/featureBehavior/04transactionmessage/', kind: 'official' },
  rfcTcp: { label: 'RFC 9293：TCP', url: 'https://www.rfc-editor.org/rfc/rfc9293', kind: 'official' },
  rfcHttp: { label: 'RFC 9110：HTTP Semantics', url: 'https://www.rfc-editor.org/rfc/rfc9110', kind: 'official' },
  rfcWebSocket: { label: 'RFC 6455：WebSocket', url: 'https://www.rfc-editor.org/rfc/rfc6455', kind: 'official' },
  rfcDns: { label: 'RFC 1034：DNS 概念与设施', url: 'https://www.rfc-editor.org/rfc/rfc1034', kind: 'official' },
  pthreads: { label: 'Linux pthreads(7)', url: 'https://man7.org/linux/man-pages/man7/pthreads.7.html', kind: 'official' },
  mmap: { label: 'Linux mmap(2)', url: 'https://man7.org/linux/man-pages/man2/mmap.2.html', kind: 'official' },
  linuxOvercommit: { label: 'Linux 内核 Overcommit Accounting', url: 'https://docs.kernel.org/mm/overcommit-accounting.html', kind: 'official' },
  linuxOom: { label: 'Linux 内核 OOM 处理', url: 'https://docs.kernel.org/mm/oom.html', kind: 'official' },
  cgroupV2: { label: 'Linux 内核 cgroup v2 内存控制', url: 'https://docs.kernel.org/admin-guide/cgroup-v2.html', kind: 'official' },
  adaptiveConcurrency: { label: 'Envoy Adaptive Concurrency Filter', url: 'https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/adaptive_concurrency_filter', kind: 'official' },
  uuid: { label: 'Java 21 UUID API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/UUID.html', kind: 'official' },
  owaspAuth: { label: 'OWASP Authentication Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html', kind: 'official' },
  uri: { label: 'RFC 3986：URI 通用语法', url: 'https://www.rfc-editor.org/rfc/rfc3986', kind: 'official' },
}

export const javaBackendInterviewBank = {
  id: 'java-backend-interviews',
  title: 'Java 后端真实面经',
  shortTitle: 'Java 后端',
  kicker: 'REAL-WORLD JAVA INTERVIEWS',
  category: '真实面经',
  description: '以公开真实面经为线索，并参照 JavaGuide 与小林 Coding 的高频主线重新整理，覆盖 Java 并发、JVM、Spring Boot、MySQL、Redis、消息队列与生产排障。',
  sourcePolicy: 'community-guide-official',
  baseTags: ['Java', '后端', '真实面经'],
  tone: 'amber',
  source: 'public/question-banks/java-backend-interviews.md',
  sections: [
    {
      title: 'Java 语言、集合与类加载',
      questions: [
        {
          title: 'HashMap 在 JDK 8 中怎样完成 put、扩容与树化？',
          summary: '结论：HashMap 先定位桶，再按空桶、同键、链表或红黑树分支写入；扩容通过容量翻倍重新分配桶，树化只在桶和表容量同时达到条件时发生。',
          mechanism: '哈希值会把 key 的高位扰动到低位，再以 `(n - 1) & hash` 定位桶。冲突后先比较哈希与 equals；链过长时，只有数组容量至少为 64 才树化，否则优先扩容。扩容到两倍后，旧桶节点只会留在原索引或移动到 `原索引 + oldCap`，因为新增的最高有效位决定去向。HashMap 不提供并发写安全，resize 与覆盖写都不能用“偶尔没出错”证明安全。',
          example: '订单属性缓存预估有十万条且读多写少时，应先合理设置 initialCapacity，减少扩容停顿；若被多线程共享，应改用 ConcurrentHashMap，而不是给 HashMap 的单次 put 结果做乐观假设。验证可构造碰撞 key，观察树化前后桶形态并压测扩容峰值。',
          followUps: [
            { question: '为什么容量通常取 2 的幂？', answer: '这样可以用位与替代取模，并使扩容后节点仅按新增的一位拆成两个桶，避免完整重算索引。' },
            { question: '树化后查询就一定是 O(log n) 吗？', answer: '只有冲突桶进入红黑树分支时才接近该复杂度；整体还受哈希质量、equals 成本和表容量影响。' },
          ],
          pitfalls: ['把树化阈值说成唯一条件，漏掉最小表容量限制。', '把 HashMap 的常规操作复杂度当成并发安全保证。'],
          sources: [COMMUNITY.jdDada, OFFICIAL.hashMapJdk8Source],
        },
        {
          title: 'ConcurrentHashMap 在高并发更新时如何避免整表锁？',
          summary: '结论：JDK 8 的 ConcurrentHashMap 以桶为并发粒度，空桶通过 CAS 安装首节点，冲突桶通过同步桶头完成修改，扩容时允许多个线程协助迁移。',
          mechanism: '读取大多不加互斥锁，依赖 volatile 可见性读取表和节点；写入空桶先 CAS，失败后重试，非空桶再对桶头同步并在锁内完成链表或树操作。扩容阶段使用转发节点标记已迁移桶，其他写线程可参与 transfer。计数不是每次都竞争同一个全局变量，而采用分散计数后汇总，降低热点竞争。它保证单次映射操作的线程安全，却不自动保证“先读再写”这一组合业务原子性。',
          example: '积分扣减若先 get 再 put，即使容器换成 ConcurrentHashMap 仍会丢更新；应使用 compute、merge 或把业务状态放入具有版本约束的存储。验证时用固定线程数并发累加，比较 get-put 与 compute 的最终总数，并记录扩容期间延迟。',
          followUps: [
            { question: '为什么 ConcurrentHashMap 不允许 null？', answer: '并发读取返回 null 时必须明确表示“没有映射”，否则无法区分真实 null 值与并发删除后的不存在。' },
            { question: 'size() 能否作为并发控制条件？', answer: '不能。并发修改期间统计值适合监控和估算，不应拿来决定必须精确执行一次的业务分支。' },
          ],
          pitfalls: ['只背“CAS 加 synchronized”，却说不清空桶和冲突桶各走哪条路径。', '误以为线程安全容器能让多步业务逻辑天然原子。'],
          sources: [COMMUNITY.iflytek, OFFICIAL.concurrentHashMap],
        },
        {
          title: '遍历集合时怎样安全地新增或删除元素？',
          summary: '结论：增强 for 或普通 Iterator 遍历期间不能直接调用集合自身的结构性修改；删除应使用迭代器方法，复杂增删可先收集变更或选用并发容器。',
          mechanism: 'ArrayList 的迭代器记录创建时的 modCount 期望值，每次 next 或 remove 都会检查集合实际修改计数。集合绕过迭代器发生结构变化后，后续检查会尽力抛出 ConcurrentModificationException；这是快速失败诊断，不是线程安全机制，也不保证每次都抛。Iterator.remove 会同步更新期望计数，因此可在单线程遍历中安全删除当前元素。新增位置、跨线程修改和批量过滤应使用专门 API 或快照策略。',
          example: '清理过期会话时，单线程可以使用 `iterator.remove()`；若条件只是过滤，`removeIf` 更清楚。若读远多于写且需并发遍历，可评估 CopyOnWriteArrayList，但要压测写时数组复制和内存峰值，而不是看到“不会报错”就采用。',
          followUps: [
            { question: 'fail-fast 是否能检测所有并发修改？', answer: '不能。它是尽力检测的错误提示机制，规范不承诺在所有竞态下必然抛出异常。' },
            { question: 'CopyOnWriteArrayList 为什么适合读多写少？', answer: '迭代读取固定数组快照而无需锁，但每次结构写会复制数组，写多时吞吐和内存成本很高。' },
          ],
          pitfalls: ['把 ConcurrentModificationException 当作可靠的并发控制手段。', '在大集合高频写场景盲目换成 CopyOnWriteArrayList。'],
          sources: [COMMUNITY.ctrip, OFFICIAL.collections],
        },
        {
          title: '业务代码该怎样在 ArrayList、LinkedList 与队列之间选型？',
          summary: '结论：默认随机访问和顺序追加优先 ArrayList；频繁从两端操作应考虑 ArrayDeque；LinkedList 只有持有节点位置时插删才有优势，不能只按“大量插入”选择。',
          mechanism: 'ArrayList 使用连续引用数组，随机访问 O(1)，尾部追加摊销 O(1)，中间插删需要移动后续引用。LinkedList 查找第 i 个元素先走链，定位本身 O(n)，因此“中间插入 O(1)”只有已经拿到节点时才成立；每个节点还增加前后指针和对象开销。ArrayDeque 以循环数组提供两端 O(1) 操作，通常比 LinkedList 更适合作为栈或队列。选型还应考虑缓存局部性、内存占用和实际访问模式。',
          example: '批量组装响应 DTO 并按下标读取时使用预估容量的 ArrayList；任务调度需要从头取、从尾补时使用 ArrayDeque。用 JMH 或真实请求回放比较吞吐、分配率与 GC，而不是只列复杂度表。',
          followUps: [
            { question: 'ArrayList 扩容是否会使每次 add 都是 O(n)？', answer: '不会，只有容量不足的少数操作需要复制，连续追加的平均成本仍是摊销 O(1)。' },
            { question: 'LinkedList 能否实现高性能队列？', answer: '功能上可以，但节点分配和局部性较差；无特殊需求时 ArrayDeque 通常更合适。' },
          ],
          pitfalls: ['把“链表插入 O(1)”忽略定位节点的 O(n) 成本。', '忽略对象分配、CPU 缓存和 GC，仅凭大 O 记号选型。'],
          sources: [COMMUNITY.ctrip, OFFICIAL.arrayList],
        },
        {
          title: 'equals 与 hashCode 写错会怎样破坏 HashMap 和 HashSet？',
          summary: '结论：相等对象必须拥有相同 hashCode；否则逻辑上相同的键可能落入不同桶，导致查不到、删不掉或 Set 重复。放入哈希容器后的键也不应再修改参与相等判断的字段。',
          mechanism: '哈希容器先用 hashCode 缩小到桶，再用 equals 判断是否同一个键。只重写 equals 不重写 hashCode 会破坏“相等对象同哈希”的契约；只比较 hashCode 又会把碰撞误判为相等。若 key 入表后关键字段变化，查询会按新哈希定位，而对象仍留在旧桶，形成业务层的幽灵数据。',
          example: '订单去重键可由不可变的业务编号构成，并同时重写 equals/hashCode；不要把会变化的订单状态纳入键。测试要覆盖两个独立实例表示同一业务键、哈希碰撞以及入表后字段变化。',
          followUps: [
            { question: 'hashCode 相同就代表 equals 为 true 吗？', answer: '不代表。不同对象允许哈希碰撞，仍要继续执行 equals 判断。' },
            { question: 'record 适合做 Map key 吗？', answer: '字段语义稳定且组成值对象时通常合适，但字段引用的对象仍应避免在入表后发生影响相等性的变化。' },
          ],
          pitfalls: ['只背“重写 equals 就要重写 hashCode”，说不出桶定位与二次比较。', '使用可变对象作为 key，修改字段后再尝试查询或删除。'],
          sources: [COMMUNITY.iflytek, OFFICIAL.hashMap],
        },
        {
          title: '双亲委派如何工作，什么时候才有理由打破它？',
          summary: '结论：类加载器先把加载请求交给父级，父级无法完成时才由当前加载器查找；它保护核心类唯一性和基础安全，打破必须有明确隔离或扩展需求。',
          mechanism: '加载、链接、初始化是不同阶段；ClassLoader 的典型 loadClass 先检查已加载类，再委派父加载器，最后调用 findClass。类的身份由“全限定名加定义它的类加载器”共同决定，因此同名 class 被两个加载器定义也不是同一类型。插件容器、应用服务器隔离和 SPI 可能需要子优先或线程上下文类加载器，让父层框架看到子层实现，但必须控制依赖边界与卸载引用。',
          example: '支付插件按租户加载时可为每个插件建立受限类加载器，只开放稳定 SPI；升级后释放线程、ThreadLocal、驱动注册等强引用，再观察旧加载器是否可回收。若只是普通业务依赖，不应自定义加载顺序。',
          followUps: [
            { question: '两个同名类为什么可能无法强转？', answer: '因为定义它们的类加载器不同，JVM 认为它们拥有不同的运行时类型身份。' },
            { question: 'SPI 为什么常使用线程上下文类加载器？', answer: '父加载器定义的框架接口需要发现由子加载器提供的实现，反向借用上下文加载器完成查找。' },
          ],
          pitfalls: ['把类加载、链接和初始化混成一个动作。', '没有隔离需求却采用子优先加载，制造依赖冲突和安全风险。'],
          sources: [COMMUNITY.iflytek, OFFICIAL.jlsLoading, OFFICIAL.classLoader, OFFICIAL.serviceLoader],
        },
      ],
    },
    {
      title: 'MySQL 索引、事务与日志',
      questions: [
        {
          title: 'InnoDB 为什么用 B+Tree，而不是 B 树或红黑树？',
          summary: '结论：B+Tree 的高扇出降低磁盘层数，叶子按键有序并保存行或主键，既适合点查也适合范围扫描；选择核心是页 I/O，而不是“树越平衡越好”。',
          mechanism: 'InnoDB 以固定大小页组织索引。非叶子节点主要保存键与子页指针，同一页能容纳更多分支，使大数据量下根到叶通常只需少数页访问；叶子节点有序，范围查询定位起点后可连续扫描。红黑树每节点分支少，数据量大时层数高且对象式节点不匹配页存储。普通 B 树在内部节点也存记录，降低扇出。真实性能还受缓存池、键宽、页分裂和回表影响。',
          example: '一亿行订单按 `(user_id, created_at)` 查询最近记录，联合 B+Tree 可先定位用户范围，再顺序扫描时间段。设计前用 EXPLAIN 验证 key、rows 与访问类型，并通过冷缓存/热缓存两组压测区分 I/O 与 CPU。',
          followUps: [
            { question: 'Hash 索引为什么不适合通用范围查询？', answer: '哈希只便于等值定位，不保持键的全序，无法直接支持范围、排序和最左前缀扫描。' },
            { question: 'B+Tree 层数少就一定快吗？', answer: '不一定，选择度差、回表多、随机页读和锁等待仍可能成为主要瓶颈。' },
          ],
          pitfalls: ['只回答“B+Tree 矮”，没有解释页、扇出和范围扫描。', '把索引结构优势当成任意 SQL 都会自动高效。'],
          sources: [COMMUNITY.taotian, OFFICIAL.mysqlIndexes],
        },
        {
          title: '聚簇、二级与覆盖索引如何决定是否回表？',
          summary: '结论：InnoDB 聚簇索引叶子保存整行，二级索引叶子保存索引列和主键；查询列能由二级索引直接提供时形成覆盖索引，否则需按主键回表。',
          mechanism: '每张 InnoDB 表的数据按聚簇索引组织，通常使用主键；二级索引找到候选后携带主键值，再访问聚簇树取得其余列。覆盖索引避免第二次树查找与随机页访问，但会增加索引宽度和写放大。主键越宽，所有二级索引叶子携带的主键也越宽。优化不能只看“用了索引”，还要看扫描行数、回表次数、过滤比例以及是否发生排序。',
          example: '查询 `SELECT created_at,status FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 20`，可评估 `(user_id, created_at, status)` 覆盖；若 status 更新极频繁，宽索引写成本可能不划算。用 EXPLAIN 与 Handler 统计验证扫描和回表。',
          followUps: [
            { question: '覆盖索引为什么不等于索引越宽越好？', answer: '更多列会占用磁盘和缓存、降低页扇出并放大插入更新成本，需要以高频查询收益换算。' },
            { question: '二级索引叶子为什么保存主键？', answer: '它既用于同值记录的唯一定位，也能作为访问聚簇索引整行数据的回表地址。' },
          ],
          pitfalls: ['把二级索引叶子说成直接保存整行所有列。', '为消除一次回表把大量低价值列全部塞进索引。'],
          sources: [COMMUNITY.taotian, OFFICIAL.mysqlIndexes],
        },
        {
          title: '联合索引怎样设计，哪些写法最容易导致索引失效？',
          summary: '结论：先根据高频过滤、排序和覆盖需求确定联合索引顺序，再用执行计划验证；函数计算、隐式类型转换、左模糊匹配和缺失前导列都可能让索引无法高效定位。',
          mechanism: '联合 B+Tree 按列顺序逐层有序，等值条件通常放在前面，范围或排序列靠后；范围后的列可能只参与过滤或覆盖，不能继续缩小连续查找区间。是否真正使用索引由成本优化器决定，`possible_keys` 只是候选，要结合 `key`、`type`、`rows`、`filtered`、`Extra` 和 EXPLAIN ANALYZE 的实际行数判断。',
          example: '订单查询 `tenant_id=? AND status=? ORDER BY created_at DESC LIMIT 20` 可评估 `(tenant_id,status,created_at)`，并只选择列表所需列形成覆盖。若线上变慢，先检查参数类型、统计信息和实际扫描行，而不是直接 FORCE INDEX。',
          followUps: [
            { question: '范围条件后的列完全没用吗？', answer: '不一定，它可能不再参与连续索引定位，但仍可用于索引条件下推、覆盖或避免回表过滤。' },
            { question: '为什么同一 SQL 有时突然不走索引？', answer: '数据分布、统计信息、参数值和缓存状态变化都可能让优化器判断全表扫描更便宜。' },
          ],
          pitfalls: ['为每个字段各建一个单列索引，忽略真实组合访问路径。', '只看 possible_keys，不核对最终 key 和实际扫描行。'],
          sources: [COMMUNITY.byteDoubao, OFFICIAL.mysqlOptimization],
        },
        {
          title: 'MySQL 深分页和慢 SQL 应怎样用执行计划逐步优化？',
          summary: '结论：不要看到慢 SQL 就先加索引；先确认慢在扫描、回表、排序还是锁等待。大 offset 连续翻页优先改为基于唯一排序键的游标分页。',
          mechanism: '`LIMIT offset,size` 仍需找到并丢弃 offset 条，二级索引还可能对大量候选回表。可先用覆盖索引定位主键再回表，或以 `(sort_key,id)` 作为下一页边界。排查时对照慢日志与 EXPLAIN ANALYZE，关注估算/实际行数、扫描方式、临时表、filesort 和执行时间，并核对是否受锁等待、连接池或磁盘抖动影响。',
          example: '订单列表按 `created_at DESC,id DESC` 返回游标，下一页条件为“小于上一页末尾二元组”，索引与排序顺序一致。用百万级数据比较首屏和深页的扫描行、回表次数与 p95，而不是只比较一条开发库 SQL。',
          followUps: [
            { question: '游标分页为什么难以直接跳到任意页？', answer: '它依赖上一页末尾边界，没有中间游标就不知道目标页起点，这是用交互能力换稳定性能。' },
            { question: '只按时间排序会有什么问题？', answer: '多个记录时间相同会导致边界不唯一，需要追加主键等唯一列形成确定顺序。' },
          ],
          pitfalls: ['把子查询优化当成所有深分页场景的固定答案。', '游标排序键不唯一，导致并发数据下重复或遗漏。'],
          sources: [COMMUNITY.jdDada, OFFICIAL.mysqlExplain],
        },
        {
          title: 'MVCC 如何让可重复读看到稳定快照？',
          summary: '结论：InnoDB 通过隐藏事务信息、undo 版本链和一致性读视图判断哪个版本可见；它减少读写阻塞，但当前读仍需锁，不能把 MVCC 等同于无锁事务。',
          mechanism: '记录修改会保留指向旧版本的 undo 信息，一致性读根据 Read View 中活跃事务边界判断当前版本是否可见，不可见则沿版本链回溯。可重复读事务通常复用一致性快照，使同一记录多次快照读保持稳定；读已提交会为每个语句取得更新视图。`SELECT ... FOR UPDATE`、UPDATE 和 DELETE 属于当前读，读取最新可锁版本并参与行锁/间隙锁协议。长事务会阻碍旧版本清理并扩大 undo。',
          example: '对账任务在可重复读事务中先后两次普通 SELECT 得到同一快照，但中间若使用 FOR UPDATE，语义转为当前读。测试用两个连接按时间线提交更新，记录每个语句结果并检查 history list length，避免长事务拖累清理。',
          followUps: [
            { question: 'MVCC 能避免所有幻读吗？', answer: '快照读可保持视图稳定；当前读要依靠锁范围控制，不能只靠版本链。' },
            { question: '长只读事务为什么也可能有成本？', answer: '它持有较老视图，使 purge 不能清理仍可能被该视图访问的 undo 版本。' },
          ],
          pitfalls: ['把 Read View 说成复制整张表的物理快照。', '忽略快照读与当前读的语义差异。'],
          sources: [COMMUNITY.digitalHorse, OFFICIAL.mysqlMvcc],
        },
        {
          title: '一条 UPDATE 怎样经过行锁、undo、redo、binlog 与提交？',
          summary: '结论：更新先按索引访问路径锁定记录，写 undo 保存旧版本，在 Buffer Pool 修改页并记录 redo，提交时协调 redo 与 binlog；锁、三类日志分别负责并发、回滚/MVCC、崩溃恢复和复制恢复。',
          mechanism: 'InnoDB 当前读按实际扫描范围加记录锁、间隙锁或 Next-Key Lock；索引不合适会扩大扫描与锁范围。undo 保存旧版本，redo 以 WAL 方式保证已提交修改可在崩溃后重做，binlog 位于 Server 层用于复制与时间点恢复。提交阶段用内部协调保证 redo 和 binlog 不出现一个可见、一个缺失的分裂结果，脏页可稍后刷盘。',
          example: '库存更新必须命中商品唯一索引并在事务内检查受影响行数。压测时观察锁等待和死锁，故障演练在提交阶段杀进程，恢复后核对主库数据、binlog 位点和从库结果。',
          followUps: [
            { question: '间隙锁是否锁住一条真实记录？', answer: '它保护的是索引键之间的区间，主要阻止该间隙插入，并不等同于锁定某条已有行。' },
            { question: '有 binlog 为什么还需要 redo？', answer: 'binlog 面向逻辑复制，redo 面向 InnoDB 页级崩溃恢复，记录层次和恢复目标不同。' },
          ],
          pitfalls: ['脱离索引访问路径背诵固定锁范围。', '把 undo、redo、binlog 都泛称为“事务日志”而不分职责。'],
          sources: [COMMUNITY.digitalHorse, OFFICIAL.mysqlLocks, OFFICIAL.mysqlRedo, OFFICIAL.mysqlUndo, OFFICIAL.mysqlBinlog],
        },
      ],
    },
    {
      title: 'Redis、缓存与分布式锁',
      questions: [
        {
          title: 'Redis 的高吞吐来自哪些条件，瓶颈又在哪里？',
          summary: '结论：内存访问、紧凑数据结构、事件驱动 I/O 和短命令执行共同带来高吞吐；单线程命令路径避免锁竞争，但慢命令、网络、持久化和大 Key 仍会阻塞。',
          mechanism: 'Redis 通过事件循环监听大量连接，就绪后读取请求并执行命令；核心数据在内存，常规操作减少磁盘随机 I/O。单命令串行执行简化原子性，却意味着 `KEYS`、大集合删除、复杂 Lua 或巨大响应可占住执行线程。后台线程与子进程会承担部分 I/O、释放或持久化工作，但不能把 Redis 简化成“完全单线程”。性能分析应拆成客户端排队、网络、命令耗时、fork/写时复制和内存压力。',
          example: '缓存 p99 突然升高时，先检查 slowlog、latency doctor、大 Key、网络与持久化事件；若发现线上 `KEYS *`，改为受控 SCAN 并限制批量。用真实 value 尺寸压测，不能只用小 key 得出容量结论。',
          followUps: [
            { question: '单线程为什么还能处理很多连接？', answer: 'I/O 多路复用让一个事件循环只处理已就绪连接，避免为每个空闲连接阻塞一个线程。' },
            { question: 'Lua 脚本原子是否代表可以无限执行？', answer: '不代表，长脚本会阻塞其他命令，应限制复杂度和处理数据量。' },
          ],
          pitfalls: ['只回答“因为内存”，遗漏事件循环、数据结构和阻塞风险。', '把所有后台工作也错误描述为单线程。'],
          sources: [COMMUNITY.baidu, OFFICIAL.redisLatency, OFFICIAL.redisPersistence],
        },
        {
          title: 'Redis 数据结构怎样按访问模式选，ZSet 为何使用跳表？',
          summary: '结论：选择应从读写命令和容量出发；ZSet 需要同时支持成员去重、按分值定位与范围遍历，字典加跳表正好覆盖等值和有序操作。',
          mechanism: 'String 适合计数、位图和简单值，Hash 适合对象字段，List 适合有序两端操作，Set 适合无序去重，ZSet 适合排行榜与区间。跳表通过多级随机索引把期望查找、插入、删除降到 O(log n)，底层链表又便于顺序范围扫描；字典从 member 快速找到 score。结构选择还要考虑编码转换、大元素数量、单 key 热点及跨槽操作限制。',
          example: '实时积分榜以用户 ID 为 member、积分为 score，用 ZADD 更新、ZREVRANGE 取榜；若只需判断是否参与活动，Set 更简单。压测应覆盖百万 member 下的更新与 Top-N，并监控单 key CPU 和内存。',
          followUps: [
            { question: '跳表为什么不用严格平衡树？', answer: '随机层级实现简单，期望复杂度稳定，且底层有序链天然适合连续范围遍历。' },
            { question: '排行榜拆成多个 key 会有什么代价？', answer: '可分散热点，但全局 Top-N 需要额外归并，并要处理分片更新一致性。' },
          ],
          pitfalls: ['按数据名字选结构，不先定义具体命令与访问频率。', '把所有用户塞进单个超大 ZSet，却不评估热点与迁移。'],
          sources: [COMMUNITY.taotian, OFFICIAL.redisTypes],
        },
        {
          title: 'RDB、AOF 与混合持久化应该怎样选择？',
          summary: '结论：RDB 适合紧凑快照和快速恢复，AOF 以写命令和刷盘策略缩小丢失窗口，混合持久化兼顾恢复速度与增量完整性；选择依据是 Redis 的数据角色、RPO 和 RTO。',
          mechanism: 'RDB 保存时间点快照，两次快照间变更可能丢失；AOF 在命令执行后追加日志，以 always/everysec/no 权衡可靠性与延迟，并通过后台重写压缩历史。Redis 7 的多部分 AOF 将基础文件和增量文件由 manifest 管理。持久化不等于高可用或备份，副本可能同步误删，缓存事实仍应能从权威存储重建。',
          example: '纯商品缓存可以接受故障后回源重建；若 Redis 保存短期任务状态，则要明确允许丢失窗口，配置 AOF、备份和恢复演练。验证要实际杀进程并测恢复时间、确认写丢失量和 fork/重写期间延迟。',
          followUps: [
            { question: 'AOF everysec 能保证零丢失吗？', answer: '不能，故障窗口内仍可能丢失尚未刷盘的数据，只是将常见窗口控制在约秒级。' },
            { question: 'AOF 重写是简单复制旧日志吗？', answer: '不是，它根据当前数据状态生成等价且更紧凑的基础内容，并在切换时衔接重写期间的增量写。' },
          ],
          pitfalls: ['把副本、持久化和备份当作同一层保障。', '只背配置名，不用故障演练验证真实 RPO/RTO。'],
          sources: [COMMUNITY.meituan, OFFICIAL.redisPersistence],
        },
        {
          title: '缓存穿透、击穿和雪崩如何按失败形态分别治理？',
          summary: '结论：穿透是不存在数据反复回源，击穿是单个热点失效瞬间并发回源，雪崩是大量 key 或缓存服务同时失效；三者的检测指标和治理手段不同。',
          mechanism: '穿透可对合法不存在结果做短负缓存、参数校验或 Bloom Filter，但要处理误判和数据新建后的失效；击穿可用请求合并、逻辑过期、互斥重建和热点预热，并确保锁等待有上限；雪崩需让 TTL 加抖动、分批预热、缓存集群高可用，同时保护数据库连接池并提供降级。所有方案都要防缓存重建失败，否则互斥锁只会把并发洪峰变成长时间排队。',
          example: '热门商品 key 到期时只允许一个加载协程回源，其余请求短等后读取新值或返回旧值；不存在商品缓存 30 秒并在创建事件后主动删除。演练同时过期一万 key，观察回源 QPS、等待和降级比例。',
          followUps: [
            { question: 'Bloom Filter 为什么不能单独做最终判断？', answer: '它可能误判存在且不保存真实值，只适合作前置过滤，最终结果仍由事实存储确认。' },
            { question: '互斥重建失败后应如何处理？', answer: '锁要有超时，加载失败应释放并限速重试，同时允许旧值、负缓存或降级响应兜底。' },
          ],
          pitfalls: ['把三种问题都回答成“加锁”，没有区分流量形态。', '所有 key 使用同一固定 TTL，主动制造集中失效。'],
          sources: [COMMUNITY.meituan, OFFICIAL.redisTypes],
        },
        {
          title: '数据库与 Redis 缓存怎样尽量保持一致？',
          summary: '结论：常见读多写少业务采用 Cache Aside：写数据库成功后删除缓存，并依靠过期时间兜底；它通常追求最终一致，强一致场景应缩短缓存链路或改用事实存储读取。',
          mechanism: '先更新数据库再删除缓存，可避免先删缓存后并发旧值回填的常见窗口；但删除失败仍会留下旧缓存，因此需要重试、消息表或订阅 binlog 做补偿。读路径未命中时回源并回填，需配合热点互斥和双重检查。延迟双删不是万能公式，延迟难覆盖所有并发时序，还会增加操作复杂度。',
          example: '商品价格更新在数据库事务提交后发送可靠失效事件，消费者按商品 ID 幂等删除缓存，TTL 作为最后兜底；高价值支付余额不把 Redis 当最终事实。压测并发读写并注入删缓存失败，量化不一致窗口。',
          followUps: [
            { question: '为什么不优先“更新数据库后更新缓存”？', answer: '并发写可能让较早的事务最后覆盖缓存，且双写失败需要更复杂的原子协调；删除通常更容易收敛。' },
            { question: '删除缓存失败怎么处理？', answer: '记录可重试事件或本地消息，持续幂等删除，并用监控和 TTL 控制最坏不一致时间。' },
          ],
          pitfalls: ['宣称 Cache Aside 可以提供跨库强一致。', '只写“延迟双删”，不说明并发时序、失败补偿与监控。'],
          sources: [COMMUNITY.kuaishou, OFFICIAL.redisTransactions],
        },
        {
          title: 'Redis 主从切换期间怎样理解复制顺序与可用性？',
          summary: '结论：单连接命令按复制流顺序应用，但复制通常是异步的；主节点确认写后立刻故障，未到副本的数据可能丢失，故不能据此宣称线性一致。',
          mechanism: '副本建立连接后进行全量或部分同步，随后持续接收主节点命令流。复制偏移量用于判断断线后能否部分续传；链路内顺序不代表跨客户端全局线性化，也不保证已返回写必然落到晋升副本。故障转移在可用性与数据新鲜度间取舍，客户端还要处理旧主恢复、读副本延迟和拓扑变更。Cluster 分片进一步要求理解槽迁移与多 key 限制。',
          example: '写入订单状态后若立即从副本读取，可能读到旧值；关键读可走主库或携带版本等待副本追平。故障演练在持续写入时隔离主节点，统计成功响应中有多少未出现在新主，并核对复制 offset。',
          followUps: [
            { question: '副本按顺序执行为何仍会读旧数据？', answer: '因为异步传输存在延迟，顺序只约束已收到命令的应用次序，不保证已经追到主节点最新位置。' },
            { question: 'WAIT 命令是否等于强一致提交？', answer: '它可等待指定副本确认以降低丢失概率，但仍不等同于完整共识协议和绝对持久性。' },
          ],
          pitfalls: ['把“复制有序”推导成所有读写都线性一致。', '只验证正常同步，不演练主从切换中的已确认写丢失窗口。'],
          sources: [COMMUNITY.xhsDesign, OFFICIAL.redisScale],
        },
      ],
    },
    {
      title: 'JVM、GC 与生产诊断',
      questions: [
        {
          title: '一次 Java 方法调用会使用哪些 JVM 运行时数据区？',
          summary: '结论：线程执行方法主要使用自己的程序计数器和虚拟机栈，实例通常分配在共享堆，类结构与运行时常量由方法区语义承载；各区域的生命周期和故障不同。',
          mechanism: '每个线程拥有程序计数器和栈，每次方法调用创建栈帧，保存局部变量、操作数栈、动态链接与返回信息；本地方法还涉及本地方法栈的实现。堆由线程共享，是垃圾回收重点。方法区是规范概念，HotSpot 现代实现以 Metaspace 承载类元数据，但“方法区等于永久代”并不成立。对象逃逸分析可能允许标量替换，所以“所有对象一定在堆上”也不应作为绝对结论。',
          example: '递归接口不断创建栈帧更可能触发 StackOverflowError；动态生成大量代理类且类加载器无法卸载，更可能推高 Metaspace；业务对象引用链未释放则表现为堆持续增长。排障先按异常类型与区域指标分类，再抓对应证据。',
          followUps: [
            { question: '局部变量一定存放在栈上吗？', answer: '局部变量槽位在栈帧中，但引用指向的对象位置由运行时决定，优化后还可能被标量替换。' },
            { question: '方法区和 Metaspace 是同一个概念吗？', answer: '方法区是 JVM 规范定义的逻辑区域，Metaspace 是 HotSpot 对其中类元数据的一种实现。' },
          ],
          pitfalls: ['把 JMM 的主内存/工作内存与 JVM 运行时数据区混为一谈。', '断言所有 new 出来的对象永远以完整对象形式位于堆中。'],
          sources: [COMMUNITY.digitalHorse, OFFICIAL.jvmsRuntime],
        },
        {
          title: '可达性分析怎样处理循环引用并决定对象生死？',
          summary: '结论：主流 JVM 从 GC Roots 沿引用图标记可达对象，两个对象即使互相引用，只要整体不再从根可达，仍可被回收，因此不会被简单引用计数困住。',
          mechanism: 'GC Roots 可包括活动线程栈中的引用、类静态字段、JNI 引用等实现规定的根集合。回收器在安全点或并发标记协议下遍历对象图；强引用保持可达，软、弱、虚引用具有不同清理语义。对象从“不可达”到实际内存回收仍可能跨越引用处理、终结相关兼容行为和清扫阶段，所以不能用一次 System.gc() 断言回收完成。业务正确性也不应依赖 finalize。',
          example: '监听器注册到长生命周期单例后，即使页面对象之间没有业务引用，单例仍从根持有它们，形成真实泄漏；两个临时对象互相引用却都不再连接根则不是泄漏。可用堆转储查看到 GC Root 的最短引用链来验证。',
          followUps: [
            { question: '弱引用适合直接做关键业务缓存吗？', answer: '通常不适合，回收时机受内存压力影响且不可预测，关键数据需要明确容量、过期和重建策略。' },
            { question: 'System.gc() 能保证立即回收指定对象吗？', answer: '不能，它最多表达一次建议，具体是否执行、何时执行和回收哪些对象由 JVM 策略决定。' },
          ],
          pitfalls: ['把互相引用直接判定为无法回收的内存泄漏。', '用 finalize 或 System.gc() 作为资源释放与测试断言。'],
          sources: [COMMUNITY.ctrip, OFFICIAL.gcTuning],
        },
        {
          title: 'CMS、G1 与低停顿收集器的选择依据是什么？',
          summary: '结论：选择收集器应围绕堆规模、暂停目标、吞吐和 JDK 支持版本；G1 以 Region 和可预测暂停为主，低停顿收集器用更多并发工作换取更短停顿。',
          mechanism: 'CMS 以老年代并发标记清除降低停顿，但会产生碎片，并存在并发失败等维护成本；现代 JDK 已移除它。G1 将堆划分为 Region，统一处理年轻代和老年代，通过 remembered set 跟踪跨区引用，按收益选择回收集合。ZGC、Shenandoah 将更多标记、重定位工作并发化，适合大堆低停顿目标，但仍要评估 CPU、内存余量和应用分配速率。任何收集器都无法弥补无界对象增长。',
          example: '延迟敏感 API 从 Parallel GC 迁移 G1 时，先记录基线吞吐、p99、分配率和 Full GC 原因，再设定可验证暂停目标并做相同流量回放。若堆持续占满，应先修复存活集或容量问题，而不是反复更换收集器。',
          followUps: [
            { question: 'G1 为什么能做暂停预测？', answer: '它维护各 Region 回收成本与收益估计，在暂停预算内选择一组回收集合，但预测并非绝对保证。' },
            { question: '低停顿是否意味着吞吐一定更高？', answer: '不意味着，并发标记和转移会消耗 CPU 与内存带宽，通常需要用部分吞吐换更短暂停。' },
          ],
          pitfalls: ['在现代 JDK 题目中仍把 CMS 当作默认可用方案。', '只背收集器名称，不给堆规模、暂停 SLO 和验证指标。'],
          sources: [COMMUNITY.xhsCore, OFFICIAL.gcTuning],
        },
        {
          title: '线上内存泄漏如何证明是存活集增长而非正常缓存？',
          summary: '结论：先看 Full GC 后基线是否持续上升，再用类直方图、堆转储和 GC Root 引用链定位增长对象；缓存命中高也不能替代容量与回收证据。',
          mechanism: '泄漏是对象已无业务价值却仍被引用，常见来源包括静态集合、监听器、ThreadLocal、未关闭类加载器和无界缓存。排查先关联堆使用、GC 频率、分配率和请求负载，确认不是流量增长造成的合理工作集；再多时点采集 class histogram 比较实例与字节增量，必要时转储堆分析 dominator 与到根路径。转储可能造成停顿和敏感数据暴露，需选择副本、限流或离线环境。',
          example: '若用户会话缓存从不淘汰，Full GC 后 retained heap 仍随用户数单调上涨。先用 `jcmd GC.class_histogram` 比较增长类，再在受控实例生成 heap dump，找到静态 Map 到会话对象的路径；修复后以固定流量跑足过期周期，确认基线回落。',
          followUps: [
            { question: '堆使用上涨就一定是泄漏吗？', answer: '不一定，扩容后的正常存活集、批任务和缓存预热都会上涨，关键看负载归零和回收后是否回落。' },
            { question: '为什么不能直接在所有生产实例 dump？', answer: '堆转储可能触发停顿、磁盘压力并包含敏感数据，应控制实例、权限、时间与留存。' },
          ],
          pitfalls: ['只看瞬时堆曲线，不比较 Full GC 后基线和业务负载。', '未经评估在高峰生成巨大 heap dump，造成二次事故。'],
          sources: [COMMUNITY.baidu, OFFICIAL.jcmd],
        },
        {
          title: 'Java 服务 CPU 突然 100% 应怎样定位到代码行？',
          summary: '结论：先确认是单实例、单核还是整体资源饱和，再把操作系统热点线程与 JVM 线程栈对应；多次采样找到持续 RUNNABLE 的热点栈，最后用火焰图或 JFR 验证，而不是凭一张线程快照下结论。',
          mechanism: '先排除流量上涨、宿主机抢占和 GC，再用 top/pidstat 找高 CPU 线程，将十进制线程 ID 转成十六进制，对照 jcmd Thread.print 或线程 dump 的 nid。连续采样能区分死循环、频繁序列化、锁自旋与瞬时任务；若 CPU 主要耗在 GC，则继续检查分配速率、堆占用和 GC 日志。生产采样要控制开销并保留时间线。',
          example: '某接口发布后单核打满，连续三次线程 dump 都指向 JSON 转换循环，再用 JFR 确认该方法占据主要 CPU；回滚并补充输入上限。若热点线程是 GC worker，则转向分析对象分配和存活集，而不是优化业务循环。',
          followUps: [
            { question: '为什么要连续抓多次线程栈？', answer: '单次快照可能正好撞上瞬时任务；持续出现的相同热点栈才更能说明 CPU 长时间消耗位置。' },
            { question: '线程很多 BLOCKED 会导致 CPU 100% 吗？', answer: '阻塞线程本身通常不消耗大量 CPU，应继续寻找 RUNNABLE、自旋、频繁唤醒或 GC 线程。' },
          ],
          pitfalls: ['只看 Java 进程总 CPU，不定位到线程并建立时间线。', '拿一次 jstack 就宣布根因，未用复现、指标或采样工具验证。'],
          sources: [COMMUNITY.jdDada, OFFICIAL.jcmd, OFFICIAL.threadMx],
        },
        {
          title: 'Java 常见 OOM 与频繁 Full GC 应怎样区分和排查？',
          summary: '结论：先按错误类型区分 Java heap space、Metaspace、Direct buffer memory、unable to create native thread 与容器 OOMKill，再结合 GC 日志、堆转储和进程内存判断是泄漏、瞬时膨胀还是堆外/系统限制。',
          mechanism: '频繁 Full GC 只是现象：老年代持续高占用可能来自存活集增长，也可能是堆太小或晋升压力。堆 OOM 要看支配树和引用链；Metaspace 关注类加载器是否泄漏；直接内存关注 NIO 缓冲；线程创建失败要核对线程数、栈大小和系统限制。容器被杀可能来不及抛 Java OOM，应结合 cgroup 和内核事件。',
          example: '开启滚动 GC 日志和 `HeapDumpOnOutOfMemoryError`，同时采集 RSS、堆、非堆与线程数。若堆稳定但 RSS 上升，优先查 direct buffer、native 库和线程栈；若 Full GC 后基线持续上升，再分析 dump 的大对象与 GC Roots。',
          followUps: [
            { question: 'Full GC 后堆占用下降很多说明什么？', answer: '更像短期分配压力或容量问题；若回收后基线仍持续抬升，才更值得怀疑泄漏或无界缓存。' },
            { question: '为什么容器 OOMKill 可能没有 heap dump？', answer: '进程可能被内核直接终止，没有机会由 JVM 抛出堆 OOM 并执行转储。' },
          ],
          pitfalls: ['看到 Full GC 就盲目增大堆，掩盖无界增长。', '只看堆内存，忽略 Metaspace、直接内存、线程栈与容器限制。'],
          sources: [COMMUNITY.baidu, OFFICIAL.gcTuning, OFFICIAL.jcmd, OFFICIAL.jvmsRuntime],
        },
      ],
    },
    {
      title: 'Spring 与 Spring Boot 核心',
      questions: [
        {
          title: 'Spring Bean 从定义到可调用代理经历哪些阶段？',
          summary: '结论：容器先读取 BeanDefinition，再实例化、注入依赖、执行 Aware 与后处理器、初始化回调；需要 AOP 时，最终暴露给调用方的可能是代理而非原对象。',
          mechanism: 'BeanDefinition 保存类、作用域、构造参数和生命周期元数据。容器创建实例后填充属性，调用相关 Aware 接口，再依次经过 BeanPostProcessor 的初始化前后回调；`@PostConstruct`、InitializingBean 或自定义 init 方法在规定阶段执行。代理通常由后处理器在初始化后包装。单例缓存的是容器管理的最终引用，销毁时再调用回调。构造器里访问尚未注入的依赖或启动外部线程，会破坏生命周期假设。',
          example: '审计切面 Bean 在构造器里调用自身业务方法时，调用发生在代理完成前，不会经过切面。应把外部连接建立放到明确初始化阶段，并用集成测试从容器取 Bean 调用，验证实际类型、切面与销毁回调。',
          followUps: [
            { question: 'BeanPostProcessor 与 BeanFactoryPostProcessor 区别是什么？', answer: '前者处理 Bean 实例，后者在实例化前修改 BeanDefinition 等容器元数据。' },
            { question: 'prototype Bean 会自动执行销毁回调吗？', answer: '容器通常不管理其完整销毁生命周期，调用方需负责释放 prototype 实例持有的资源。' },
          ],
          pitfalls: ['把实例化和依赖注入说成同一个瞬间。', '在构造器中依赖尚未完成的代理、事务或外部资源。'],
          sources: [COMMUNITY.beanLifecycle, OFFICIAL.springLifecycle],
        },
        {
          title: 'Spring AOP 何时使用 JDK 代理，何时使用类代理？',
          summary: '结论：面向接口可使用 JDK 动态代理，类代理通过生成子类拦截可覆盖方法；两者都只能拦截经过代理引用的调用，不能把对象内部自调用自动变成切面调用。',
          mechanism: '代理对象持有目标对象与拦截器链，调用进入代理后按顺序执行事务、日志等 Advice，再反射或方法句柄调用目标。JDK 代理暴露接口类型；类代理需要目标类可继承、方法可覆盖，因此 final 类或 final/private 方法无法按普通子类方式增强。Spring 可根据配置和目标类型选择代理。代理只在容器边界生效，`this.method()` 没有重新经过代理。',
          example: '订单服务接口由控制器注入代理，外部调用能记录审计日志；同类方法 A 直接调用方法 B 时，B 上的独立切面可能不生效。可将 B 抽到另一个 Bean，或重新设计事务边界，并在测试中检查代理类型与切面计数。',
          followUps: [
            { question: 'private 方法为什么难以被常规 Spring AOP 拦截？', answer: '它不能被子类覆盖，也不会通过接口代理暴露，普通代理调用链无法在其入口接管。' },
            { question: '代理与 AspectJ 编织有何边界差异？', answer: '代理主要拦截对象边界的方法调用，编织可修改字节码连接点，但部署和调试复杂度更高。' },
          ],
          pitfalls: ['认为加了注解就能拦截任何 private、final 或自调用。', '调用方持有手工 new 的原对象，却期待容器代理生效。'],
          sources: [COMMUNITY.iflytek, OFFICIAL.springAop],
        },
        {
          title: 'Spring 单例循环依赖为什么有时能解、有时不能？',
          summary: '结论：部分属性/Setter 注入的单例循环依赖可借助提前暴露引用解决；构造器循环在任一实例尚未创建前就互相等待，无法用同一机制补全。',
          mechanism: '创建单例 A 后、属性填充前，容器可登记一个获取其早期引用的工厂；创建依赖 B 时若 B 又需要 A，可取早期引用继续完成 B，再回填 A。若 A 最终需要 AOP，早期引用必须与最终暴露代理保持一致，否则会出现原对象和代理不一致。prototype 不由单例缓存统一管理，也无法套用该流程。即使容器能解开，双向依赖通常反映职责耦合，应优先重构。',
          example: '订单服务与库存服务互相注入时，不要依赖“三级缓存能跑”；提取库存预占协调器，由其单向调用两个领域服务。测试同时覆盖启用事务代理后的 Bean 身份，避免一侧拿到原对象绕过切面。',
          followUps: [
            { question: '为什么构造器循环不能提前暴露？', answer: '构造 A 必须先得到 B，而构造 B 又必须先得到 A，此时两个完整实例都尚未产生可供回填。' },
            { question: '能自动启动就代表设计合理吗？', answer: '不代表，循环依赖增加初始化顺序和代理一致性风险，应视为需要审查的架构信号。' },
          ],
          pitfalls: ['把所有循环依赖都归结为“三级缓存一定解决”。', '只为消除启动错误改成字段注入，却保留领域职责环。'],
          sources: [COMMUNITY.iflytek, OFFICIAL.springDeps],
        },
        {
          title: 'Spring 事务传播与常见失效路径怎样一起解释？',
          summary: '结论：声明式事务通过代理拦截方法并绑定线程资源；传播行为决定已有事务下加入、挂起或创建保存点，失效常源于调用未经过代理或异常未越过边界。',
          mechanism: '外部调用代理方法时，事务拦截器根据属性取得事务管理器，开启或复用事务，目标成功则提交，匹配回滚规则的异常则回滚。REQUIRED 加入当前事务，REQUIRES_NEW 挂起外层并创建新事务，NESTED 通常依赖保存点且受管理器能力限制。自调用、对象不在容器、方法不可代理、异常被吞掉、异步切换线程或受检异常未配置 rollbackFor，都可能使预期与实际不同。',
          example: '批量导入中主事务调用同类 `saveItem()`，即使后者标了 REQUIRES_NEW 也可能没有新事务。将单项写入放到独立 Bean，经代理调用，并故障注入第三条写入异常，核对数据库提交边界和事务日志。',
          followUps: [
            { question: 'REQUIRES_NEW 一定更安全吗？', answer: '不一定，它会增加独立连接占用，并可能留下外层失败、内层已提交的业务补偿问题。' },
            { question: '异步线程会继承当前事务吗？', answer: '通常不会，事务资源多绑定在线程上下文，新线程需要自己的事务边界或消息一致性方案。' },
          ],
          pitfalls: ['只背传播枚举，不说明已有事务存在时具体发生什么。', '在方法内捕获异常后正常返回，却期待代理自动回滚。'],
          sources: [COMMUNITY.kuaishou, OFFICIAL.springTx],
        },
        {
          title: 'Spring Boot 自动装配为什么能做到“引入 Starter 即可用”？',
          summary: '结论：Starter 主要聚合依赖，自动配置模块声明候选配置类；Spring Boot 根据类路径、已有 Bean、配置属性等条件按需注册组件，应用显式配置通常可以覆盖默认值。',
          mechanism: '`@SpringBootApplication` 组合了配置、扫描和自动配置入口。现代 Spring Boot 从 `AutoConfiguration.imports` 发现候选自动配置，再用 `@ConditionalOnClass`、`@ConditionalOnMissingBean`、`@ConditionalOnProperty` 等条件筛选。配置属性负责把外部配置绑定成类型化对象；条件评估报告可解释某项配置为何生效或未生效。Starter 不等于自动配置代码本身。',
          example: '自定义短信 Starter 将 API 依赖和自动配置分层，只有类路径存在客户端且用户未定义 SmsClient 时才创建默认 Bean。集成测试分别覆盖缺配置、用户覆盖和条件满足三条路径，并用条件报告排查线上装配差异。',
          followUps: [
            { question: 'Starter 与 AutoConfiguration 有什么区别？', answer: 'Starter 主要做依赖聚合；AutoConfiguration 提供按条件注册 Bean 的配置实现，两者可在不同模块。' },
            { question: '如何判断某个自动配置为什么没生效？', answer: '查看条件评估报告，逐项核对类路径、属性、已有 Bean 和排除配置。' },
          ],
          pitfalls: ['仍把所有版本都说成只读取 spring.factories 的 EnableAutoConfiguration。', '把 Starter、自动配置和组件扫描混为一谈。'],
          sources: [COMMUNITY.kuaishou, OFFICIAL.springBootAuto],
        },
        {
          title: '一个 Spring MVC 请求从 DispatcherServlet 到响应经历什么？',
          summary: '结论：DispatcherServlet 是前端控制器，先寻找处理器和拦截器，再由适配器调用 Controller，随后通过返回值处理、消息转换或视图解析生成响应；异常则进入统一异常解析链。',
          mechanism: '请求先经过 Servlet Filter，再进入 DispatcherServlet。HandlerMapping 根据路由找到 HandlerExecutionChain，HandlerAdapter 负责参数解析、数据绑定和调用方法；返回值由 HandlerMethodReturnValueHandler 处理，`@ResponseBody` 通常交给 HttpMessageConverter。异常由 HandlerExceptionResolver 链解析。Interceptor 位于 MVC 调用链，Filter 位于 Servlet 容器层，适用边界不同。',
          example: '统一 traceId 和安全头可放 Filter，登录态与接口耗时可放 Interceptor，业务异常由 `@ControllerAdvice` 映射统一错误码。测试覆盖参数校验失败、业务异常和序列化失败，确保都经过一致的响应契约。',
          followUps: [
            { question: 'Filter 与 Interceptor 的主要区别是什么？', answer: 'Filter 属于 Servlet 规范，覆盖更底层的请求响应；Interceptor 属于 Spring MVC，能感知选中的 Handler。' },
            { question: '参数校验异常在哪里统一处理？', answer: '通常通过 ControllerAdvice/HandlerExceptionResolver 映射为稳定错误响应，同时保留可观测日志。' },
          ],
          pitfalls: ['只背 DispatcherServlet，不说明 HandlerMapping、Adapter 与消息转换职责。', '在 Controller 到处分散 try/catch，破坏统一错误契约。'],
          sources: [COMMUNITY.maimaiAlibaba, OFFICIAL.springMvc],
        },
      ],
    },
    {
      title: 'JMM、线程池与锁',
      questions: [
        {
          title: 'JMM 怎样解释可见性、有序性与 happens-before？',
          summary: '结论：JMM 不是 JVM 内存区域图，而是线程间读写共享变量的规则；happens-before 给出“前一动作结果必须对后一动作可见”的最低保证。',
          mechanism: '每个线程可能从寄存器或缓存使用共享变量副本，编译器与处理器也可在不破坏单线程语义时重排。程序次序、监视器解锁到后续加锁、volatile 写到后续读、线程 start/join 等规则建立 happens-before；该关系还具有传递性。没有这条关系的竞态读写结果不受业务直觉保护。原子性、可见性和有序性是不同维度，volatile 只覆盖其中部分。',
          example: '配置热更新时，先完整构造不可变配置对象，再写入 volatile 引用；工作线程读取同一引用后可看到构造完成的字段。验证可用 JCStress 或大量并发测试寻找旧值，但“没复现”不能证明无数据竞争，还需代码层建立明确同步边。',
          followUps: [
            { question: 'volatile 写读建立了什么保证？', answer: '对同一变量的写 happens-before 后续读，写前普通写入也可经传递关系对读线程可见。' },
            { question: 'happens-before 是否等于真实时间上先执行？', answer: '不等于，它描述内存可见性与允许的执行结果，不要求所有动作按墙钟时间完全串行。' },
          ],
          pitfalls: ['把 JMM 误画成堆、栈、方法区的内存分区。', '只说“禁止重排”，不说明针对哪类读写建立可见性。'],
          sources: [COMMUNITY.xhsCore, OFFICIAL.jlsThreads],
        },
        {
          title: 'volatile 为什么不能让 i++ 变成原子操作？',
          summary: '结论：volatile 保证读写可见性并约束部分重排，但 `i++` 包含读取、计算、写回三个动作，多个线程仍可能读取同一个旧值并覆盖更新。',
          mechanism: '对 volatile 变量的单次读写具有规定的同步语义，却不会把复合表达式自动包装为不可分割事务。两个线程都读到 10，各自计算 11 并写回，最终只增加一次。计数需求可用 AtomicLong 的 CAS 循环、LongAdder 的分散累加，或在更大不变量上使用锁；选择取决于是否要求线性化读取、竞争强度及是否需要把多个字段一并更新。',
          example: '接口请求总量只用于监控且高并发时可使用 LongAdder；库存余量要求每次扣减可线性化并联动订单状态时，不能只换原子计数器，应在数据库条件更新或事务边界内完成。通过并发屏障同时执行一百万次自增，核对期望值与实际值。',
          followUps: [
            { question: 'AtomicLong 与 LongAdder 如何选择？', answer: 'AtomicLong 提供单值 CAS 与精确瞬时读取；LongAdder 高竞争吞吐更好，但 sum 不是全局线性化快照。' },
            { question: 'volatile 能安全发布对象吗？', answer: '先完成对象构造再写入 volatile 引用，可以借助写读关系安全发布其构造前状态。' },
          ],
          pitfalls: ['把可见性直接等同于复合操作原子性。', '在要求强一致余额的路径上用 LongAdder 追求吞吐。'],
          sources: [COMMUNITY.byteLife, OFFICIAL.jlsThreads],
        },
        {
          title: 'CAS、AQS 与公平锁之间是什么关系？',
          summary: '结论：CAS 是条件更新原语，AQS 用原子状态和等待队列搭建同步器；公平性由获取策略决定，不是 CAS 本身天然提供的属性。',
          mechanism: 'CAS 比较内存当前值与期望值，相等才写入新值，失败方可重试、入队或返回。AQS 维护 volatile state，并把竞争失败的线程组织为队列节点；独占或共享模式由子类定义 tryAcquire/tryRelease 语义。公平锁获取前会尊重队列中是否已有前驱，非公平锁允许新线程抢占，常有更高吞吐但可能增加尾延迟。高竞争下无界自旋会浪费 CPU，因此同步器需在自旋与挂起间权衡。',
          example: '连接池许可可基于 Semaphore 的共享模式；需要严格排队的人工审批任务可评估公平锁，但普通短临界区先用非公平锁并测量 p99。验证记录获取顺序、阻塞时间和 CPU，自旋成功率不能只看平均吞吐。',
          followUps: [
            { question: 'CAS 的 ABA 问题是什么？', answer: '值从 A 变 B 又变 A 时普通 CAS 看不出中间变化，可用版本戳、不可复用节点或更高层协议处理。' },
            { question: 'AQS 队列是否就是业务任务队列？', answer: '不是，它保存等待同步状态的线程节点，不负责承载线程池中的业务 Runnable。' },
          ],
          pitfalls: ['把 CAS 描述成完全没有开销的无锁万能方案。', '把公平锁理解为绝对墙钟顺序，忽略调度和取消等因素。'],
          sources: [COMMUNITY.byteLife, OFFICIAL.aqs],
        },
        {
          title: 'synchronized 与 ReentrantLock 的取舍怎样结合锁升级说明？',
          summary: '结论：两者都能建立互斥和可见性；synchronized 语法简单且自动释放，ReentrantLock 提供可中断、超时、公平及多条件队列，选择应由控制需求决定。',
          mechanism: '进入和退出 synchronized 监视器形成 happens-before，并由 JVM 管理异常释放。JVM 可针对竞争形态使用轻量路径、自旋或膨胀到重量级监视器，这属于实现优化，业务代码不应依赖固定升级细节。ReentrantLock 基于 AQS，必须在 finally 中 unlock，可通过 tryLock 限时退让，Condition 将不同等待条件分组。两者都不能修复锁范围过大或锁顺序不一致。',
          example: '账户间转账若必须拿两把锁，应先按账户 ID 排序，避免循环等待；如果外部调用可能长时间阻塞，可用 tryLock 超时后回滚并重试。验证应做故障注入，让临界区抛异常，确认锁一定释放且无部分更新。',
          followUps: [
            { question: 'synchronized 锁能主动降级吗？', answer: '业务 API 没有主动降级能力；JVM 的具体锁状态优化属于实现细节，不应作为正确性前提。' },
            { question: '什么时候需要多个 Condition？', answer: '同一锁保护多种等待谓词时可分别唤醒，例如有界队列的 notEmpty 与 notFull。' },
          ],
          pitfalls: ['背诵锁升级阶段，却说不清业务为何需要互斥。', '使用 ReentrantLock 后漏写 finally 解锁，异常路径永久占锁。'],
          sources: [COMMUNITY.meituan, OFFICIAL.locks],
        },
        {
          title: 'ThreadPoolExecutor 的参数如何映射到真实负载？',
          summary: '结论：线程池参数必须从任务等待时间、执行时间、下游容量和内存预算反推；无界队列或盲目增大 maximumPoolSize 都可能把过载藏成延迟与 OOM。',
          mechanism: '提交任务时，运行线程少于 corePoolSize 先建核心线程；否则尝试入队；队列满且未达 maximumPoolSize 才扩线程，最后触发拒绝策略。keepAliveTime 管理非核心线程空闲回收，也可选择作用于核心线程。CPU 密集任务线程数接近可用核数，I/O 等待任务可更高，但必须受连接池、数据库和远端限额约束。队列容量决定允许积压的时间窗口，应结合 Little 定律和超时目标评估。',
          example: '报表任务平均执行 200ms、峰值 100 RPS，而数据库只允许 20 个并发查询时，线程数上限不能超过数据库容量。设置有界队列、明确拒绝或降级，压测时同时观察 activeCount、queueSize、拒绝量、下游 RT 与堆占用。',
          followUps: [
            { question: '为什么 Executors.newFixedThreadPool 有风险？', answer: '其默认无界队列可持续积压任务，流量超过处理能力时延迟和内存占用不断增长。' },
            { question: 'CallerRunsPolicy 的价值和风险是什么？', answer: '它让提交线程执行任务形成反压，但若提交线程是事件循环或关键入口，也可能拖死接入层。' },
          ],
          pitfalls: ['只按 CPU 核数给 I/O 任务定线程数，忽略下游连接上限。', '把任务不丢等同于使用无界队列，最终以 OOM 方式丢服务。'],
          sources: [COMMUNITY.byteDoubao, OFFICIAL.threadPool],
        },
        {
          title: '线上死锁怎样从现象定位到具体锁顺序？',
          summary: '结论：先保留现场并确认线程确实在循环等待，再用 JVM 线程信息定位持锁者和等待者，最后回到统一锁顺序、缩小临界区或超时退让修复。',
          mechanism: '死锁需要互斥、持有并等待、不可剥夺和循环等待同时成立。线上表现可能是吞吐突然归零、线程池 active 满但 CPU 不高，也可能与连接池耗尽混淆。ThreadMXBean 或 jcmd Thread.print 可给出线程栈、监视器和 ownable synchronizer 信息；将“线程 A 持有 L1 等 L2、线程 B 持有 L2 等 L1”画成等待图即可确认。修复后还要检查数据库锁和外部资源，它们未必出现在 JVM 死锁检测中。',
          example: '订单迁移同时锁旧账户和新账户时，统一按账户 ID 从小到大获取；无法统一时使用限时 tryLock，失败释放已持有锁并带抖动重试。故障测试让两线程从相反方向同时进入，确认不会永久阻塞。',
          followUps: [
            { question: 'ThreadMXBean 没报告死锁就能排除吗？', answer: '不能，数据库行锁、分布式锁和条件等待可能不在 JVM 可识别的监视器循环中。' },
            { question: '扩大线程池能解决死锁吗？', answer: '不能，只会增加更多等待线程和资源占用；必须破坏循环等待或调整临界区协议。' },
          ],
          pitfalls: ['把所有线程阻塞都叫死锁，没有画出资源等待环。', '直接重启消除现场，却不保存线程转储和请求关联信息。'],
          sources: [COMMUNITY.ctrip, OFFICIAL.threadMx],
        },
      ],
    },
    {
      title: '消息队列与分布式一致性',
      questions: [
        {
          title: 'Kafka 如何用 ACK、副本与 ISR 控制消息丢失窗口？',
          summary: '结论：生产端 ACK 决定等待到哪一步，副本与 ISR 决定可容忍故障范围；要降低已确认消息丢失，需组合 `acks=all`、足够副本和最小同步副本，而非只改一个参数。',
          mechanism: '分区 Leader 接收写入并追加日志，Follower 拉取并追赶；ISR 表示当前保持足够同步的副本集合。`acks=0/1/all` 分别表示不等响应、只等 Leader、等待满足同步条件。若允许 ISR 只剩 Leader 仍接受写，Leader 随即故障时可能没有合格副本保留数据；设置 min.insync.replicas 可在同步副本不足时拒绝写，牺牲部分可用性换持久性。磁盘刷盘、机架故障域和不洁净选主也必须进入模型。',
          example: '支付事件分区配置 3 副本、跨机架分布，生产者使用 acks=all，并把最小同步副本设为 2。演练隔离一个再隔离两个 Broker，确认单故障仍写入、同步副本不足时明确失败，且已确认消息在新 Leader 上可读。',
          followUps: [
            { question: 'acks=all 是否等于所有配置副本都写入？', answer: '不是，它等待当前 ISR 中满足配置条件的副本，ISR 规模与 min.insync.replicas 共同决定强度。' },
            { question: '副本越多是否只有好处？', answer: '副本会增加存储、网络复制和恢复成本，仍需按故障域与吞吐预算选择。' },
          ],
          pitfalls: ['只背 acks=all，不说明 ISR 缩小时是否继续接受写。', '多个副本放在同一故障域，却按副本数宣称高可用。'],
          sources: [COMMUNITY.taotian, OFFICIAL.kafkaDesign],
        },
        {
          title: 'Kafka 重试后怎样避免消息与业务结果重复？',
          summary: '结论：传输重试可由幂等生产者减少日志重复，消费端仍要把业务写入与消费进度设计为可重放；所谓 Exactly-Once 不能自动覆盖任意外部数据库。',
          mechanism: '客户端超时不知道 Broker 是否已写入，重试可能重复发送；幂等生产者用生产者 ID、分区与序列号去重同会话内重试。消费者拉取、处理、提交 offset 是三个动作，处理成功但提交前崩溃会再次收到同一消息。若结果写回 Kafka，可用事务协调输入 offset 与输出记录；若写 MySQL，则需唯一业务键、幂等表或本地事务同时记录处理状态。先提交 offset 再处理又会造成消息丢失。',
          example: '优惠券发放以 `event_id` 建唯一索引，在同一数据库事务内插入处理记录并发券；重复消费命中唯一约束后读取既有结果并正常推进 offset。故障测试在业务提交后、offset 提交前杀消费者，验证只发一张券。',
          followUps: [
            { question: '手动提交 offset 就能杜绝重复吗？', answer: '不能，只能选择提交时机；业务成功到 offset 成功之间仍存在崩溃窗口。' },
            { question: 'Kafka 事务能原子写 MySQL 吗？', answer: '不能直接覆盖任意外部数据库，仍需 outbox、幂等键或专门一致性协议。' },
          ],
          pitfalls: ['把至少一次投递错误描述成消费者只会收到一次。', '先提交 offset 再执行外部副作用，失败后消息无法自动重放。'],
          sources: [COMMUNITY.taotian, OFFICIAL.kafkaSemantics],
        },
        {
          title: 'RocketMQ 顺序消息与事务消息分别解决什么问题？',
          summary: '结论：顺序消息约束同一消息组内的存储和消费次序，事务消息协调本地事务与消息最终可见；二者解决的问题不同，也都不能替代消费幂等。',
          mechanism: '要保持订单事件顺序，应以订单 ID 作为消息组/队列路由键，让同一订单进入同一有序通道，并让消费者按协议串行处理；全局顺序会牺牲并行度。事务消息先发送半消息，再执行本地事务并提交或回滚消息；Broker 在状态不明时回查生产者。生产者本地事务状态查询必须可靠，消费者仍可能因重试看到重复事件。死信是多次消费失败后的隔离结果，需要告警和人工/自动修复流程。',
          example: '订单创建、支付、关闭事件按 orderId 分组，消费者维护状态机拒绝非法逆序；创建订单与发布事件使用事务消息，回查根据本地事务记录返回明确状态。注入网络超时和重复投递，验证状态机与幂等键。',
          followUps: [
            { question: '为什么不追求所有订单全局有序？', answer: '全局单队列会限制吞吐，业务通常只要求同一聚合根内有序，不同订单可以并行。' },
            { question: '事务回查返回未知怎么办？', answer: '应保留可查询的本地事务记录，持续回查或进入人工处置，不能随意提交半消息。' },
          ],
          pitfalls: ['把顺序消息误说成整个 Topic 所有消息绝对有序。', '使用事务消息后取消消费者幂等与状态校验。'],
          sources: [COMMUNITY.maimaiAlibaba, OFFICIAL.rocketOrder, OFFICIAL.rocketTx],
        },
        {
          title: '消息积压时应怎样止损、定位和恢复消费？',
          summary: '结论：先阻止积压继续扩大并保护下游，再区分生产突增、消费变慢、分区不均、故障重平衡或毒消息；恢复时提升有效并行度并验证幂等，不能只盲目加消费者。',
          mechanism: '用 lag、生产/消费速率和最老消息年龄判断规模，按 topic/partition/consumer 实例定位瓶颈。消费者数量超过分区数不会继续提升 Kafka 并行度；慢 SQL、远程超时、频繁 GC 和单条毒消息都会拖慢处理。可临时限流生产者、旁路非核心事件、扩分区或扩容消费者，但扩分区可能改变按 key 顺序，重放也会放大重复处理。',
          example: '订单事件 lag 激增时先暂停非核心补数，定位某分区被一个大商户热点占满；拆分路由键并扩容前，先确认消费者以 eventId 幂等。恢复期间监控 lag 下降斜率、数据库连接池和失败重试队列，避免二次击穿。',
          followUps: [
            { question: '消费者加倍为什么吞吐可能不变？', answer: '分区数可能已限制并行度，或真正瓶颈在数据库、远程依赖和单条消息处理时间。' },
            { question: '直接跳过失败消息可以吗？', answer: '要按业务定义隔离到死信/重试队列并告警，保留可追溯上下文，不能静默丢弃。' },
          ],
          pitfalls: ['只看总 lag，不定位到分区和消费阶段。', '无限重试毒消息，阻塞同分区后续正常消息。'],
          sources: [COMMUNITY.jdIntern, OFFICIAL.kafkaConsumer],
        },
        {
          title: 'Kafka、RocketMQ 与 RabbitMQ 应怎样按业务选型？',
          summary: '结论：不要只比峰值吞吐；日志流和可重放分析常偏 Kafka，订单交易与事务/延时能力常偏 RocketMQ，复杂路由和轻量业务集成常偏 RabbitMQ，最终还要服从团队运维经验。',
          mechanism: '比较维度包括消息模型、顺序范围、投递语义、事务与延时能力、路由、消息保留/重放、扩容方式、生态和可观测性。Kafka 以分区日志提供高吞吐和回放；RocketMQ 强调业务消息、事务与延时；RabbitMQ 的 Exchange 路由灵活。所有 MQ 都会引入丢失、重复、乱序、积压和运维复杂度。',
          example: '埋点流进入 Kafka 供多下游回放，订单状态事件使用团队已有 RocketMQ 事务消息，邮件通知可用 RabbitMQ 路由。选型文档必须写清 SLA、峰值、保留期、顺序键、灾备和团队值班能力，再用压测验证。',
          followUps: [
            { question: '为什么不应为了异步而上 MQ？', answer: '若流量小、链路简单且同步即可满足 SLA，MQ 的一致性和运维成本可能高于收益。' },
            { question: '选型时“支持顺序消息”够吗？', answer: '不够，要说明顺序范围、分区/队列键、失败重试后是否仍有序以及吞吐代价。' },
          ],
          pitfalls: ['只拿厂商公布 TPS 做结论，不考虑消息语义与运维能力。', '把 MQ 当成无成本解耦，遗漏重复、积压和故障恢复。'],
          sources: [COMMUNITY.xhsDesign, OFFICIAL.kafkaDesign, OFFICIAL.rocketTx],
        },
        {
          title: '本地事务与消息发送怎样实现可靠最终一致？',
          summary: '结论：数据库提交与普通 MQ 发送不是同一个原子操作；可使用事务消息或本地消息表/Outbox，把业务事实与待发送事件放入同一事务，再由可靠投递、幂等消费和对账收敛。',
          mechanism: '本地消息表方案在同一数据库事务写业务表和事件表，后台按状态重试发送，Broker 确认后标记完成；事务消息通过半消息与事务回查协调本地事务。两者都可能重复投递，消费者必须以事件 ID 或业务唯一键去重，失败进入重试/死信并保留人工补偿。它们提供最终一致，不等于跨服务强事务。',
          example: '订单创建与 `OrderCreated` outbox 同事务提交，投递器至少一次发送，库存服务以 eventId 建唯一记录后扣减。演练数据库提交后进程崩溃、Broker 超时和消费者重复执行，最终用订单—事件—库存三方对账验证收敛。',
          followUps: [
            { question: '为什么消费者仍必须幂等？', answer: '发送确认丢失、消费超时和故障恢复都可能触发重投，至少一次语义天然允许重复。' },
            { question: '事务消息能替代业务对账吗？', answer: '不能，跨系统仍可能有长期失败和数据损坏，需要状态监控、补偿与周期对账。' },
          ],
          pitfalls: ['先提交数据库再裸发消息，发送失败后没有可恢复记录。', '只保证生产端不丢，不设计消费幂等、死信与对账。'],
          sources: [COMMUNITY.xhsDesign, OFFICIAL.rocketTx, OFFICIAL.mysqlLocks],
        },
      ],
    },
    {
      title: '分布式场景与生产排障',
      questions: [
        {
          title: '接口幂等怎样覆盖重复点击、超时重试与 MQ 重投？',
          summary: '结论：幂等不是“前端按钮置灰”，而是同一业务请求重复到达时服务端只产生一次有效结果；优先用业务唯一键和数据库约束兜底，再配合幂等记录、状态机与结果复用。',
          mechanism: '客户端生成 requestId 只能辅助识别，真正边界应由订单号、支付流水号等业务键定义。服务端先查幂等记录或依靠唯一索引竞争，成功后保存结果供重复请求返回；处理中状态要避免并发请求都执行。MQ 消费使用 eventId 或业务版本去重。幂等记录需设合理生命周期，不能过早过期让迟到重试再次生效。',
          example: '创建订单以 `(tenant_id, client_order_no)` 建唯一约束，请求重复时查询并返回原订单；支付回调按平台流水号和状态机执行，已成功状态不再扣款。故障测试覆盖响应丢失后重试、并发重复和 MQ 重投。',
          followUps: [
            { question: '查询接口天然幂等吗？', answer: '语义上通常应无副作用，但若查询顺便写浏览次数或触发任务，仍要单独处理这些副作用。' },
            { question: 'Redis SETNX 能替代数据库唯一约束吗？', answer: '不能完全替代，Redis 故障、过期与跨存储失败都可能突破边界，关键事实仍需持久层约束。' },
          ],
          pitfalls: ['只在网关缓存 requestId，没有业务唯一键和数据库兜底。', '把异常重试写成无上限循环，扩大重复与雪崩。'],
          sources: [COMMUNITY.tencent, OFFICIAL.rfcHttp, OFFICIAL.mysqlIndexes],
        },
        {
          title: '超时、重试、熔断和限流怎样协同避免服务雪崩？',
          summary: '结论：超时限制单次等待，重试应有次数、退避和幂等边界，熔断隔离持续故障依赖，限流控制入口负载；四者必须围绕统一延迟预算设计，否则各层重试会指数放大流量。',
          mechanism: '上游超时应大于下游单次预算但小于用户总预算，并为连接、读取分别设置边界。只对瞬时且幂等失败重试，使用指数退避和抖动；熔断在失败率达到阈值后快速失败，半开阶段少量探测；限流和舱壁隔离保护线程池、连接池。调用链各层都重试会形成乘法放大，应指定唯一重试层。',
          example: '订单查询总预算 800ms，下游库存单次 200ms，最多一次带抖动重试；库存持续超时时打开熔断并返回降级信息，独立线程池防止拖死支付。故障演练注入超时，检查实际调用次数、线程池队列和恢复过程。',
          followUps: [
            { question: '为什么重试必须配合幂等？', answer: '超时只代表调用方没收到结果，服务端可能已执行；重试会重复产生副作用。' },
            { question: '熔断和限流有什么区别？', answer: '熔断依据依赖失败状态暂时停止调用，限流按容量控制允许进入系统的请求量。' },
          ],
          pitfalls: ['每一层都默认重试三次，形成调用风暴。', '只设置客户端超时，不限制线程池队列和并发。'],
          sources: [COMMUNITY.baidu, OFFICIAL.adaptiveConcurrency, OFFICIAL.rfcHttp],
        },
        {
          title: '分布式 ID 怎样在唯一性、趋势递增与可用性之间取舍？',
          summary: '结论：数据库自增简单但集中，UUID 去中心化但较长且随机写不友好，号段模式减少数据库访问，Snowflake 类方案高吞吐但依赖机器号和时钟治理；应按主键、业务单号和安全性分别选。',
          mechanism: '全局唯一只是底线，还要考虑是否有序、生成延迟、容量、故障域、信息泄露和数据库索引局部性。Snowflake 通过时间、节点与序列组合 ID，必须防节点号重复和时钟回拨；号段模式批量租用区间，服务重启可能浪费但通常不影响唯一。外部订单号不应直接暴露可枚举的数据库主键。',
          example: '内部订单表主键使用趋势递增 ID 改善 B+Tree 写入，面向用户的订单号再加入随机或校验维度。压测节点扩缩容、时钟回拨和号段服务故障，验证不重复、生成延迟和降级策略。',
          followUps: [
            { question: 'UUID 为什么不一定适合作为聚簇主键？', answer: '随机且较宽的键会增加二级索引体积、页分裂和缓存局部性压力，需结合具体 UUID 版本与存储形式判断。' },
            { question: '时钟回拨怎么处理？', answer: '可短时等待、切换逻辑时钟或拒绝生成并告警，关键是节点号与时间状态持久化且不允许静默重复。' },
          ],
          pitfalls: ['只回答 Snowflake 位数分配，不讨论时钟和节点号冲突。', '把内部递增主键直接暴露给外部，造成枚举风险。'],
          sources: [COMMUNITY.baidu, OFFICIAL.uuid, OFFICIAL.mysqlIndexes],
        },
        {
          title: 'Redis 分布式锁怎样避免误删、续期失效与迟到写？',
          summary: '结论：加锁要用唯一持有者 token 和租约，释放必须原子比较后删除；续期只能降低任务超时概率，网络分区或长暂停后旧持有者仍可能迟到写，关键资源要增加 fencing token 或存储层版本检查。',
          mechanism: '使用 `SET key token NX PX ttl` 获取锁，Lua 脚本比较 token 后删除，避免旧持有者误删新锁。Watchdog 只在确认仍持有时续期，进程崩溃后依赖 TTL 释放。主从异步复制和故障切换仍可能损失刚写入的锁；锁本身也不保证被保护数据库的事务原子性，因此必须明确可接受的一致性级别。',
          example: '结算任务获得锁时同时取得单调 fencing 版本，数据库只接受不小于当前版本的写。故障注入暂停旧实例超过 TTL，新实例接管后再恢复旧实例，确认旧写被版本条件拒绝且解锁不会删掉新锁。',
          followUps: [
            { question: '为什么释放锁不能直接 DEL？', answer: '自己的租约可能已经过期且新持有者已成功加锁，直接 DEL 会删掉别人的有效锁。' },
            { question: '有自动续期就不需要业务幂等吗？', answer: '仍需要，续期线程也可能暂停或失联，旧任务恢复后仍可能重复执行。' },
          ],
          pitfalls: ['只会背 SETNX，不设置租约、不校验持有者。', '把 Redis 锁说成跨数据库和外部系统的强一致事务。'],
          sources: [COMMUNITY.kuaishou, OFFICIAL.redisLock],
        },
        {
          title: '高并发接口怎样从入口到数据库逐层做容量保护？',
          summary: '结论：先用容量模型确定系统能承受多少流量，再按网关限流、应用舱壁、缓存削峰、MQ 异步和数据库约束逐层保护；任何降级都要保住核心数据正确性。',
          mechanism: '入口按租户/用户/接口限速并防突发，应用线程池和连接池必须有界，热点读用缓存但要防击穿，非核心写可异步削峰。数据库通过索引、短事务和条件更新守住事实。排队只转移压力，队列过长会把超时变成内存和延迟问题；限流阈值要以压测拐点、下游容量和 p99 SLO 为依据。',
          example: '秒杀入口先校验资格并限流，Redis 原子预扣后发送订单事件，数据库唯一键和条件更新兜底；系统过载时关闭推荐与统计但不突破库存。压测逐级提升 QPS，记录每层饱和点和降级后的数据守恒。',
          followUps: [
            { question: '为什么线程池队列不能无限大？', answer: '它会把过载隐藏为不断增长的排队时间和内存占用，最终请求全部超时。' },
            { question: '削峰后数据库仍可能被打满吗？', answer: '会，消费者吞吐和重试仍要按数据库容量限制，并保留积压监控和暂停能力。' },
          ],
          pitfalls: ['只回答“加 Redis、加 MQ”，不说明每层容量和失败边界。', '过载时继续无限排队，直到线程、连接和内存一起耗尽。'],
          sources: [COMMUNITY.baidu, OFFICIAL.adaptiveConcurrency, OFFICIAL.redisTransactions],
        },
        {
          title: '线上接口突然变慢应怎样沿调用链定位根因？',
          summary: '结论：先用时间线确认影响范围和变更，再把总延迟拆到网关、应用、缓存、数据库、MQ 与外部依赖；依靠指标、追踪、日志和剖析相互验证，不能只凭一条慢日志猜测。',
          mechanism: '先比较错误率、吞吐和 p50/p95/p99，按实例、机房、接口和版本切片；分布式追踪定位最长 span，再检查线程池/连接池等待、GC、CPU、锁、Redis 延迟、SQL 执行计划和下游超时。指标告诉“哪里异常”，追踪连接请求路径，结构化日志补业务上下文。建立假设后用回滚、限流或故障复现实验验证。',
          example: '发布后订单 p99 从 200ms 升到 2s，追踪显示数据库 span 未变但获取连接耗时激增；继续发现新代码事务内调用远程服务长期占连接。先回滚止损，再拆短事务并补连接池等待告警和回归压测。',
          followUps: [
            { question: '平均耗时正常为什么用户仍觉得慢？', answer: '平均值会掩盖长尾，应按分位数、用户/机房和具体路径切片观察。' },
            { question: '没有完整链路追踪怎么办？', answer: '先用统一 requestId 关联网关与服务日志，再结合阶段耗时、线程池和数据库指标缩小范围。' },
          ],
          pitfalls: ['只盯应用 CPU，忽略排队、连接池和外部依赖。', '同时修改多个参数“试试看”，导致无法验证真正根因。'],
          sources: [COMMUNITY.tencentShortLink, OFFICIAL.springObservability, OFFICIAL.mysqlExplain, OFFICIAL.redisLatency],
        },
      ],
    },
  ],
}

const CURATED_BY_QUESTION = [
  [CURATED.javaCollection, CURATED.javaCollection, CURATED.javaCollection, CURATED.javaCollection, CURATED.javaCollection, CURATED.javaJvm],
  [CURATED.xiaolinIndex, CURATED.mysql, CURATED.mysql, CURATED.xiaolinMysql, CURATED.xiaolinMvcc, CURATED.xiaolinLogs],
  [CURATED.xiaolinRedis, CURATED.redis, CURATED.xiaolinAof, CURATED.xiaolinRedisInterview, CURATED.redis, CURATED.xiaolinRedis],
  [CURATED.javaJvm, CURATED.javaJvm, CURATED.javaJvm, CURATED.javaJvm, CURATED.javaJvm, CURATED.javaJvm],
  [CURATED.spring, CURATED.spring, CURATED.spring, CURATED.spring, CURATED.springAuto, CURATED.spring],
  [CURATED.javaConcurrent, CURATED.javaConcurrent, CURATED.javaConcurrent, CURATED.javaConcurrent, CURATED.javaConcurrent, CURATED.javaConcurrent],
  [CURATED.messageQueue, CURATED.messageQueue, CURATED.messageQueue, CURATED.messageQueue, CURATED.messageQueue, CURATED.messageQueue],
  [CURATED.distributed, CURATED.distributed, CURATED.distributed, CURATED.distributed, CURATED.highPerformance, CURATED.highPerformance],
]

javaBackendInterviewBank.sections.forEach((section, sectionIndex) => {
  section.questions.forEach((question, questionIndex) => {
    const guide = CURATED_BY_QUESTION[sectionIndex]?.[questionIndex]
    if (!guide) throw new Error(`Missing curated guide for Java backend question ${sectionIndex + 1}.${questionIndex + 1}`)
    question.sources = [question.sources[0], guide, ...question.sources.slice(1)]
  })
})
